<script>/* Original CERN-OHL-S-2.0. Optional accessory inspection only. */
(async()=>{
while(!window.animation333)await new Promise(r=>setTimeout(r,30));const V=viewer,$=id=>document.getElementById(id),panel=document.createElement('details');panel.id='modularity-panel';document.querySelector('aside').append(panel);
const boundedNotes=document.createElement('style');boundedNotes.textContent='#state-note{max-height:86px;overflow:auto;overscroll-behavior:contain}';document.head.append(boundedNotes);
const L=(en,pt)=>V.language()==='en'?en:pt;
function inspect(){animation333.exit();V.applyState('MODULARITY STUDY');V.cameraPreset('INTERIOR');V.frame(V.installed.filter(m=>m.visible));}
function render(){panel.innerHTML=`<summary>${L('OPTIONAL MODULARITY','MODULARIDADE OPCIONAL')}</summary><button id="modularity-inspect" class="full">${L('BOARDS + CABLE ZONES','PLACAS + ZONAS DE CABOS')}</button><button id="modularity-assemble" class="full">${L('OPTIONAL ASSEMBLY STUDY','ESTUDO DE MONTAGEM OPCIONAL')}</button><p>${L('ACC01: one 100 × 120 × 12 mm family. Two generic removable clamps per selected board. Not included in minimum BOM, sheets, mass or packing. Actual clamps and impact-toy loads remain HOLD. No permanent holes are added.','ACC01: uma família 100 × 120 × 12 mm. Dois grampos removíveis genéricos por placa escolhida. Fora da BOM mínima, chapas, massa e embalagem. Grampos reais e cargas de impacto permanecem PENDENTES. Sem novos furos permanentes.')}</p><p>${L('Left low SIGNAL / right low ELV POWER are mechanical route zones. Backbox fold harness remains HOLD. PF geometric loop clearance does not resolve the missing primary 50° service support.','SINAL baixo à esquerda / POTÊNCIA ELV baixa à direita são zonas mecânicas. Chicote de dobra do backbox PENDENTE. Folga geométrica do laço PF não resolve o apoio primário de serviço em 50° ausente.')}</p>`;$('modularity-inspect').onclick=inspect;$('modularity-assemble').onclick=()=>animation333.start('assembly-18.2');}
for(const id of ['lang-en','lang-pt'])$(id).addEventListener('click',()=>setTimeout(render,0));render();window.modularity338={inspect};document.body.dataset.modularityReady='true';
})().catch(e=>{console.error(e);document.getElementById('error').hidden=false;document.getElementById('error').textContent=e.message;});</script>
