<script>/* CERN-OHL-S-2.0. Generic interchangeable user layouts; no CNC center authority. */
(async()=>{
while(!window.animation333)await new Promise(r=>setTimeout(r,30));const V=viewer,$=id=>document.getElementById(id),C=V.data.underfront,p=document.createElement('details');p.id='underfront-panel';document.querySelector('aside').append(p);let variant=C.default_variant;
const human=s=>s.replace(/(\d)(buttons|botões|mm)\b/g,'$1 $2').replace(/—(?=\d)/g,'— ').replace(/\+(?=\S)/g,'+ ');const L=o=>human(o[V.language()]||o.en),t=(a,b)=>V.language()==='en'?a:b;
function orient(){const b=new THREE.Box3();for(const m of V.installed.filter(m=>m.visible&&m.userData.meta.group==='underfront'))b.union(new THREE.Box3().setFromObject(m));const c=b.getCenter(new THREE.Vector3());V.controls.target.copy(c);V.camera.position.copy(c).add(new THREE.Vector3(-160,-260,-170));}
function isolate(){animation333.exit();window.landings3363?.cleanup();V.applyState('UNDERFRONT USER MODULE');orient();V.frame(V.installed.filter(m=>m.visible&&m.userData.meta.group==='underfront'));}
function pick(value){variant=value;isolate();}
function draw(){p.innerHTML=`<summary>${t('UNDERFRONT USER MODULE','MÓDULO DO USUÁRIO SOB A FRENTE')}</summary><label for="underfront-variant">${t('User layout — same mechanical bay','Configuração do usuário — mesmo alojamento')}</label><select id="underfront-variant">${C.variants.map(v=>`<option value="${v.id}">${L(v.names)} · ${v.status}</option>`).join('')}</select><button class="full" id="underfront-isolate">${t('ISOLATE USER MODULE','ISOLAR MÓDULO DO USUÁRIO')}</button><button class="full" id="underfront-remove">${t('REMOVE / SERVICE PLATE','RETIRAR / SERVIÇO DA PLACA')}</button><p>${t('Generic programmable controls; no permanent volume, mode or pairing function. Control symbols do not authorize drilled centers.','Controles programáveis genéricos; sem funções permanentes de volume, modo ou pareamento. Símbolos não autorizam centros de furação.')}</p><p class="hold">${t('HARDWARE_PENDING · button bore and USB cutout UNSELECTED · PURCHASE BEFORE CNC','HARDWARE_PENDING · furo do botão e recorte USB INDEFINIDOS · COMPRAR ANTES DO CNC')}</p>`;$('underfront-variant').value=variant;$('underfront-variant').onchange=e=>pick(e.target.value);$('underfront-isolate').onclick=isolate;$('underfront-remove').onclick=()=>animation333.start('service-underfront');}
window.underfront337={isolate,orient,pick,get variant(){return variant;}};for(const id of ['lang-en','lang-pt'])$(id).addEventListener('click',()=>setTimeout(draw,0));draw();V.refresh();document.body.dataset.underfrontReady='true';
})().catch(e=>{console.error(e);document.getElementById('error').hidden=false;document.getElementById('error').textContent=e.message;});</script>
