/* Original CERN-OHL-S-2.0. Rendering/documentation only; immutable CAD inputs. */
(async()=>{'use strict';
const $=id=>document.getElementById(id), D=await new Response(new Blob([Uint8Array.from(atob($('viewer-data').textContent.trim()),c=>c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('gzip'))).json();$('viewer-data').remove();
let language=new URLSearchParams(location.search).get('lang')==='pt-BR'?'pt-BR':'en',palette='original',state='PLAY',detailed=false,selected=null,isolated=null,stageFilter=null,assemblyThrough=null,manualStage=null,manualStep=0;
const t=(en,pt)=>language==='en'?en:pt,L=o=>o?.[language]||o?.en||'—',esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STATES=[['PLAY','PLAY','JOGO'],['INTERIOR INSPECTION','INTERIOR INSPECTION','INSPECIONAR INTERIOR'],['PLAYFIELD SERVICE 50°','PLAYFIELD SERVICE 50°','SERVIÇO DO PLAYFIELD 50°'],['PLAYFIELD LIFT-OUT','PLAYFIELD LIFT-OUT','RETIRADA DO PLAYFIELD'],['MATRIX REMOVAL','MATRIX REMOVAL','REMOÇÃO DA MATRIZ'],['BACKBOX REAR DOORS OPEN','BACKBOX REAR DOORS OPEN','PORTAS TRASEIRAS DO BACKBOX ABERTAS'],['BACKBOX INTERIOR','BACKBOX INTERIOR','INTERIOR DO BACKBOX'],['BACKBOX UNLOCKED','BACKBOX UNLOCKED','BACKBOX DESTRAVADO'],['BACKBOX FOLD 45°','BACKBOX FOLD 45°','DOBRA DO BACKBOX 45°'],['BACKBOX FOLD 90°','BACKBOX FOLD 90°','DOBRA DO BACKBOX 90°'],['EXPLODED OVERVIEW','EXPLODED — OVERVIEW','EXPLODIDA — VISÃO GERAL'],['EXPLODED DETAILED','EXPLODED — DETAILED','EXPLODIDA — DETALHADA']];
const CAMERAS=[['PLAYER','PLAYER','JOGADOR'],['FRONT','FRONT','FRENTE'],['REAR','REAR','TRASEIRA'],['LEFT','LEFT','ESQUERDA'],['RIGHT','RIGHT','DIREITA'],['TOP','TOP','TOPO'],['INTERIOR','INTERIOR','INTERIOR'],['BACKBOX REAR','BACKBOX REAR','BACKBOX TRASEIRO'],['BACKBOX FRONT','BACKBOX FRONT','BACKBOX FRONTAL']];
const ORIGINAL={shell:0xc9ad81,playfield:0xc69c58,supports:0xc69c58,shelves:0xddc79f,pc:0x548c70,mainfans:0x718797,ssf:0xd98a48,matrix:0x465c73,bbshell:0xc9ad81,bbglass:0x465c73,display:0x465c73,cassette:0xc9ad81,doors:0xc9ad81,bbfans:0x718797,bbhardware:0x83939d,hardware:0x83939d,future:0x8f9bc8,carrier:0xddc79f};
const ACCESSIBLE={shell:0xbdbdbd,playfield:0x0072b2,supports:0xe69f00,shelves:0xd4d0c8,pc:0x56b4e9,mainfans:0x8b949c,ssf:0xcc79a7,matrix:0x4a4a4a,bbshell:0xbdbdbd,bbglass:0x4a4a4a,display:0x4a4a4a,cassette:0xd4d0c8,doors:0xbdbdbd,bbfans:0x8b949c,bbhardware:0x4a4a4a,hardware:0x4a4a4a,future:0xf0e442,carrier:0xd4d0c8};
__LEGACY_PALETTE_FUNCTIONS__
function colorFor(m,v){return m.source?(v==='accessible'?ACCESSIBLE_PALETTE:ORIGINAL_PALETTE)[semanticRole(m.source,category(m.source))]:(v==='accessible'?ACCESSIBLE:ORIGINAL)[m.group];}
const statusPT={ONE_SIDE_CNC_READY:'CNC em uma face — preparação auditada',ONE_SIDE_CNC_PLUS_MANUAL_FINISH:'CNC em uma face + acabamento manual',PURCHASE_BEFORE_CNC:'COMPRAR ANTES DO CNC',PURCHASE_BEFORE_ASSEMBLY:'COMPRAR ANTES DA MONTAGEM',PROVISIONAL:'PROVISÓRIO',PROVISIONAL_HARDWARE:'FERRAGENS PROVISÓRIAS',WAITING_FOR_PHYSICAL_MEASUREMENT:'AGUARDANDO MEDIÇÃO FÍSICA',WAITING_FOR_COUPON:'AGUARDANDO CUPOM',OPTIONAL:'OPCIONAL',FROZEN:'CONGELADO',READY:'PRONTO',STRUCTURAL_PREMIUM:'ESTRUTURAL PREMIUM',MODULAR_SECONDARY:'MODULAR SECUNDÁRIO',REFERENCE_ONLY_NOT_FROZEN:'SOMENTE REFERÊNCIA — NÃO CONGELADO',TRULY_TBD:'REALMENTE INDEFINIDO',FORMULA_FROM_SELECTED_HARDWARE:'QUANTIDADE DEPENDE DA FERRAGEM SELECIONADA'};
const status=s=>language==='pt-BR'?(statusPT[s]||s):s;
function options(el,rows,value){el.innerHTML=rows.map(([k,en,pt])=>`<option value="${esc(k)}">${esc(t(en,pt))}</option>`).join('');el.value=value;}
const stageEl=$('stage'),viewWidth=()=>Math.max(200,stageEl.clientWidth-(!$('manual-panel').hidden&&innerWidth>1100?440:0)),scene=new THREE.Scene();scene.background=new THREE.Color('#e8edf0');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=THREE.sRGBEncoding;renderer.localClippingEnabled=true;stageEl.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(40,1,1,20000);camera.up.set(0,0,1);
const controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=20;controls.maxDistance=10000;
scene.add(new THREE.HemisphereLight(0xffffff,0x647386,.75));for(const [xyz,intensity] of [[[-700,-1000,1800],.8],[[1200,1600,1800],.35]]){const l=new THREE.DirectionalLight(0xffffff,intensity);l.position.set(...xyz);scene.add(l);}
const geoCache=new Map(),installed=[],detail=[],groupInputs={},hidden=new Set();let helper=null,edge=null,faceArrow=null;const partLabels=[];
function geometry(key){if(!geoCache.has(key)){const p=D.geometry[key];if(!p)throw Error('Missing geometry '+key);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p.vertices.flat(),3));g.setIndex(p.faces.flat());g.computeVertexNormals();g.computeBoundingBox();geoCache.set(key,g);}return geoCache.get(key);}
function make(entry,isDetail=false){const m=entry.meta;const glass=m.source==='CandidateGlass'||m.source==='BB_Backglass';const reserve=m.kind==='reference';const mat=new THREE.MeshStandardMaterial({color:colorFor(m,'original'),roughness:.7,metalness:m.kind==='hardware'?.32:0,side:THREE.DoubleSide,flatShading:true,transparent:glass||reserve,opacity:glass?.22:reserve?.23:1,depthWrite:!(glass||reserve)});mat.color.convertSRGBToLinear();const obj=new THREE.Mesh(geometry(entry.geometry),mat);obj.name=entry.key;obj.userData={entry,meta:m,baseGeometry:entry.geometry,baseOpacity:mat.opacity,absent:false,detail:isDetail};scene.add(obj);return obj;}
D.installed.forEach(e=>installed.push(make(e)));
function ensureDetail(){if(detail.length)return;D.detail.forEach(e=>detail.push(make(e,true)));setPalette(palette);}
function active(){return detailed?detail:installed;}
function resetGroups(){D.groups.forEach(g=>groupInputs[g.id].checked=!['future','pc'].includes(g.id));hidden.clear();isolated=null;}
for(const g of D.groups){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span');input.type='checkbox';input.checked=!['future','pc'].includes(g.id);input.dataset.group=g.id;input.onchange=()=>{isolated=null;refresh();};text.dataset.groupLabel=g.id;label.append(input,text);$('groups').append(label);groupInputs[g.id]=input;}
function setPalette(v){palette=v;$('palette').value=v;[...installed,...detail].forEach(m=>m.material.color.setHex(colorFor(m.userData.meta,v)).convertSRGBToLinear());}
function setLanguage(v){language=v;document.documentElement.lang=v;document.title=t('VPin · Assembly atlas V33.2','VPin · Atlas de montagem V33.2');document.querySelectorAll('[data-en]').forEach(e=>e.textContent=t(e.dataset.en,e.dataset.pt));$('lang-en').setAttribute('aria-pressed',v==='en');$('lang-pt').setAttribute('aria-pressed',v==='pt-BR');options($('service-state'),STATES,state);options($('camera-preset'),CAMERAS,$('camera-preset').value||'PLAYER');$('manual-stage').innerHTML=D.manual.stages.map(s=>`<option value="${s.id}">${s.id} · ${esc(L(s.title))}</option>`).join('');$('manual-stage').value=manualStage?.id||'00';document.querySelectorAll('[data-group-label]').forEach(e=>e.textContent=L(D.groups.find(g=>g.id===e.dataset.groupLabel).names));$('search').setAttribute('aria-label',t('Search part','Buscar peça'));$('toggle-controls').setAttribute('aria-label',t('Toggle controls','Mostrar/ocultar controles'));$('cut').setAttribute('aria-label',t('Cut position','Posição do corte'));$('scope').setAttribute('aria-label',t('Assembly scope','Conjunto'));selectionText();search();note();if(manualStage)renderManual();refresh();}
function refresh(){const isExploded=state.startsWith('EXPLODED');for(const m of [...installed,...detail]){const a=m.userData,meta=a.meta;let visible=a.detail===detailed&&!a.absent&&groupInputs[meta.group]?.checked&&!hidden.has(m.name)&&(!isolated||m===isolated);if(a.detail){const f=$('detail-filter').value,s=$('scope').value,sub=$('family-focus').value;visible=visible&&(f==='both'||meta.kind===f)&&(s==='ALL'||meta.scope===s)&&(!sub||(meta.source||'').includes(sub))&&(!meta.tray||$('tray').checked);if(stageFilter)visible=visible&&meta.stage===stageFilter;if(assemblyThrough!==null)visible=visible&&Number(meta.stage)<=assemblyThrough&&(meta.kind==='wood'||meta.classification==='REQUIRED_FLATPACK_HARDWARE')&&(!meta.tray||Number(meta.stage)===assemblyThrough);m.position.fromArray(a.entry.offset).multiplyScalar(isExploded?Number($('distance').value):0);if(meta.tray)m.position.fromArray(a.entry.offset);}
 else m.position.fromArray(isExploded?a.entry.overview:[0,0,0]);m.visible=!!visible;}
 if(helper){helper.update();helper.visible=!!selected?.visible;}if(edge){edge.position.copy(selected.position);edge.visible=!!selected.visible;}if(faceArrow)faceArrow.visible=!!selected?.visible;
 for(const l of partLabels)l.el.remove();partLabels.length=0;
 if(detailed&&($('family-focus').value||stageFilter))for(const m of active().filter(m=>m.visible).slice(0,40)){const el=document.createElement('span');el.className='part-label';el.textContent=m.userData.meta.id+(m.userData.meta.instance?' · '+m.userData.meta.instance:'');stageEl.append(el);partLabels.push({el,m});}
 $('visible-count').textContent=t(`${active().filter(m=>m.visible).length} visible parts` ,`${active().filter(m=>m.visible).length} peças visíveis`);clip();note();}
const foldEN='Locks released and parked; rear doors closed/latched; MAIN PLAYFIELD GLASS and MATRIX removed. Backbox glass and cassette retained. No routine electronics disconnection.';
const foldPT='Travas soltas e guardadas; portas traseiras fechadas/travadas; VIDRO PRINCIPAL e MATRIZ removidos. Vidro do backbox e cassete mantidos. Sem desconexão elétrica de rotina.';
function note(){let txt=t('PLAY · wood dowel seated in open cradles. Inspection visibility does not change the CAD.','JOGO · cavilha assentada nos berços abertos. A visibilidade de inspeção não altera o CAD.');if(state.includes('FOLD'))txt=t(foldEN,foldPT);else if(state.includes('SERVICE')||state.includes('LIFT-OUT'))txt=t('Main glass and matrix removed. 50° service / 48 mm lift-out are saved geometric states. Do not work under an unsupported playfield; physical load/support qualification remains pending.','Vidro principal e matriz removidos. Serviço 50° / retirada 48 mm são estados geométricos salvos. Não trabalhe sob playfield sem apoio; validação física de carga/apoio pendente.');else if(state==='BACKBOX UNLOCKED')txt=t('UPRIGHT · both doors open; two locks parked. Re-engage both locks before leaving upright for play. Close/latch doors and remove main glass/matrix before folding.','VERTICAL · portas abertas; duas travas guardadas. Reengate as travas antes de jogar. Feche/trave as portas e remova vidro principal/matriz antes de dobrar.');else if(state.includes('BACKBOX')||state==='BACKBOX INTERIOR')txt=t('UPRIGHT SERVICE · active leaf released before passive leaf; both doors at 100°. Front glass/display visibility is an inspection aid, not physical removal.','SERVIÇO VERTICAL · folha ativa liberada antes da passiva; portas a 100°. Visibilidade do vidro/monitor frontal auxilia inspeção, não representa remoção física.');else if(state==='MATRIX REMOVAL')txt=t('Main glass removed; release retainers, move forward and lift using the accepted matrix service path. Shown fully removed.','Vidro principal removido; solte retentores, avance e eleve pelo trajeto aceito da matriz. Mostrada totalmente removida.');else if(state==='INTERIOR INSPECTION')txt=t('INSPECTION · playfield, fixed cradles and matrix hidden. Shelves, PCBase, shell, fans and SSF retained. No service animation required.','INSPEÇÃO · playfield, berços fixos e matriz ocultos. Prateleiras, PCBase, estrutura, ventoinhas e SSF mantidos. Sem exigir animação de serviço.');if(state.startsWith('EXPLODED'))txt=t('DOCUMENTATION OFFSETS — not removal trajectories. Real manufacturing pieces; unlocated hardware shown as one labelled family sample in a separate tray. Quantities remain as catalogued. Fan/blank alternatives coexist in this parts inventory.','DESLOCAMENTOS DE DOCUMENTAÇÃO — não são trajetórias de retirada. Peças reais de fabricação; ferragens sem posição aparecem como amostra de família na bandeja separada. Quantidades seguem o catálogo. Alternativas ventoinha/tampa coexistem neste inventário de peças.');$('state-note').textContent=txt;$('mode-tag').textContent=(assemblyThrough!==null?t('MECHANICAL KIT AFTER STAGE ','KIT MECÂNICO APÓS ETAPA ')+String(assemblyThrough).padStart(2,'0'):L({en:STATES.find(s=>s[0]===state)?.[1], 'pt-BR':STATES.find(s=>s[0]===state)?.[2]}))+' · '+t('REVIEW — NOT FOR CNC','REVISÃO — NÃO USAR NO CNC');}
function applyState(value,{keepVisibility=false}={}){state=value;$('service-state').value=value;stageFilter=null;assemblyThrough=null;select(null);if(!keepVisibility)resetGroups();detailed=value==='EXPLODED DETAILED';if(detailed)ensureDetail();let s={'PLAYFIELD SERVICE 50°':'SERVICE','PLAYFIELD LIFT-OUT':'LIFT-OUT','MATRIX REMOVAL':'MATRIX REMOVED','BACKBOX REAR DOORS OPEN':'DOORS OPEN','BACKBOX INTERIOR':'DOORS OPEN','BACKBOX UNLOCKED':'UNLOCKED','BACKBOX FOLD 45°':'FOLD45','BACKBOX FOLD 90°':'BACKBOX FOLD'}[value]||'PLAY';const overrides={...D.states.PLAY,...D.states[s]};installed.forEach(m=>{const k=m.name;m.userData.absent=Object.hasOwn(overrides,k)&&overrides[k]===null;m.geometry=geometry(overrides[k]||m.userData.baseGeometry);});if(value==='INTERIOR INSPECTION')for(const g of ['playfield','supports','matrix'])groupInputs[g].checked=false;if(value==='BACKBOX INTERIOR'){groupInputs.bbglass.checked=false;groupInputs.display.checked=false;groupInputs.future.checked=true;groupInputs.playfield.checked=false;groupInputs.matrix.checked=false;}
 if(value.startsWith('EXPLODED'))$('explode-panel').open=true;refresh();search();}
function quickHide(supports=false){groupInputs.playfield.checked=false;if(supports)groupInputs.supports.checked=false;refresh();}
function boxVisible(ms=active().filter(m=>m.visible)){const b=new THREE.Box3();ms.forEach(m=>b.union(new THREE.Box3().setFromObject(m)));return b;}
function frame(ms){const b=boxVisible(ms);if(b.isEmpty())return;const c=b.getCenter(new THREE.Vector3()),sz=b.getSize(new THREE.Vector3());let dir=camera.position.clone().sub(controls.target).normalize();const vf=THREE.MathUtils.degToRad(camera.fov),hf=2*Math.atan(Math.tan(vf/2)*camera.aspect),dist=sz.length()*.5/Math.sin(Math.min(vf,hf)/2)*1.16;controls.target.copy(c);camera.position.copy(c).addScaledVector(dir,Math.max(dist,90));controls.update();}
function cameraPreset(p){$('camera-preset').value=p;const target=[300,650,620],positions={PLAYER:[-1650,-2050,1730],FRONT:[300,-2500,760],REAR:[300,3300,900],LEFT:[-2600,650,760],RIGHT:[3200,650,760],TOP:[300,650,3400],INTERIOR:[-1100,-300,2200],'BACKBOX REAR':[1400,2850,1580],'BACKBOX FRONT':[-700,-700,1550]};if(p==='INTERIOR')target.splice(0,3,300,740,270);if(p.startsWith('BACKBOX'))target.splice(0,3,300,1200,970);controls.target.set(...target);camera.position.set(...positions[p]);if(camera.aspect<1.1)camera.position.copy(controls.target.clone().add(camera.position.clone().sub(controls.target).multiplyScalar(1.1/camera.aspect)));controls.update();}
function select(m){if(selected)selected.material.emissive.setHex(0);for(const o of [helper,edge,faceArrow])if(o){scene.remove(o);o.geometry?.dispose();o.material?.dispose();}selected=m;helper=edge=faceArrow=null;if(m){m.material.emissive.setHex(0x202020);helper=new THREE.BoxHelper(m,0x172f3e);helper.material.depthTest=false;helper.renderOrder=50;scene.add(helper);edge=new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry,25),new THREE.LineBasicMaterial({color:0x172f3e,depthTest:false,transparent:true,opacity:1}));edge.position.copy(m.position);edge.renderOrder=51;scene.add(edge);if(m.userData.meta.face_A){const c=new THREE.Box3().setFromObject(m).getCenter(new THREE.Vector3());faceArrow=new THREE.ArrowHelper(new THREE.Vector3(...m.userData.meta.face_A),c,65,0x20313c,14,8);scene.add(faceArrow);}}for(const id of ['hide','isolate','focus'])$(id).disabled=!m;selectionText();refresh();}
function selectionText(){if(!selected){$('selection').textContent=t('Tap a part or search a canonical ID.','Toque em uma peça ou busque um ID canônico.');$('callout').hidden=true;return;}const m=selected.userData.meta;const rows=[[t('Part ID','ID da peça'),m.id],[t('English name','Nome em inglês'),m.names.en],[t('PT-BR name','Nome em PT-BR'),m.names['pt-BR']],[t('Assembly / stage','Conjunto / etapa'),L(D.manual.stages.find(s=>s.id===m.stage)?.title)+' · '+m.stage],[t('Material class','Classe do material'),status(m.material)||'—'],[t('Nominal thickness','Espessura nominal'),m.thickness?m.thickness+' mm':'—'],[t('BOM total quantity','Quantidade total na BOM'),m.quantity??t('TBD — not guessed','INDEFINIDA — não estimada')],[t('Manufacturing family','Família de fabricação'),m.families.join(', ')||'—'],[t('Instance / assembly ID','ID da instância / montagem'),(m.instances||[]).join(', ')||'—'],[t('Hardware ID','ID da ferragem'),m.hardware_id||'—'],[t('Manufacturing route','Rota de fabricação'),m.manufacturing_status.map(status).join('; ')||'—'],[t('Freeze / purchase status','Estado / compra'),status(m.status)],[t('Quantity authority','Autoridade da quantidade'),status(m.quantity_status)]];if(m.model_status)rows.push([t('CAD model authority','Autoridade do modelo CAD'),m.model_status]);if(m.formula)rows.push([t('Quantity formula','Fórmula da quantidade'),m.formula]);if(m.tray)rows.push([t('Location','Localização'),t('UNLOCATED FAMILY SAMPLE — not installed','AMOSTRA SEM POSIÇÃO — não instalada')]);if(m.face_A)rows.push(['FACE A / FACE B',t('Arrow = A outward; B = NO CNC','Seta = normal externa A; B = SEM CNC')]);$('selection').innerHTML=`<strong>${esc(m.id)} · ${esc(L(m.names))}</strong><dl>${rows.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p><a target="_blank" href="${m.hardware_id?'../hardware-v33/flatpack-bom-'+(language==='en'?'en':'pt-BR')+'.md':'../flatpack-v331/manufacturing-wood-bom-'+(language==='en'?'en':'pt-BR')+'.md'}">${t('BOM item / family','Item / família na BOM')}</a>${m.hardware_id?' · <a target="_blank" href="../../../config/hardware_catalog_v33.json">'+t('Hardware catalog','Catálogo de ferragens')+'</a>':''}</p><button id="part-manual" class="full">${t('Open manual stage ','Abrir etapa do manual ')+m.stage}</button>`;$('part-manual').onclick=()=>openManual(m.stage,0,false);$('callout').hidden=false;$('callout').textContent=m.id+' · '+(m.instance||m.hardware_id||L(m.names));}
function choose(key,detailMode=false){if(!detailMode&&detailed)applyState('PLAY');if(detailMode){if(!detailed)applyState('EXPLODED DETAILED');ensureDetail();}let m=active().find(m=>m.name===key);if(!m)return;if(m.userData.absent){applyState('PLAY');m=active().find(m=>m.name===key);}hidden.delete(key);groupInputs[m.userData.meta.group].checked=true;if(m.userData.meta.tray)$('tray').checked=true;$('scope').value='ALL';$('family-focus').value='';$('detail-filter').value='both';stageFilter=null;assemblyThrough=null;isolated=null;select(m);frame([m]);}
function search(){const q=$('search').value.toLowerCase().trim();const entries=[...D.installed.map(e=>[e,false]),...D.detail.map(e=>[e,true])];const seen=new Set();const matches=entries.filter(([e,d])=>{if(!q)return false;const m=e.meta;const hay=[e.key,m.id,m.source,m.hardware_id,...m.families,...m.instances,m.names.en,m.names['pt-BR']].join(' ').toLowerCase();if(!hay.includes(q))return false;const k=e.key;if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>{const rank=([e,d])=>e.key.toLowerCase()===q||e.meta.id.toLowerCase()===q?0:e.meta.families.some(f=>f.toLowerCase()===q)?1:2;return rank(a)-rank(b);}).slice(0,50);$('parts').innerHTML='';for(const [e,detailMode] of matches){const b=document.createElement('button');b.textContent=e.meta.id+' · '+L(e.meta.names)+(detailMode?' · '+(e.meta.instance||t('hardware detail','detalhe da ferragem')):'');b.onclick=()=>choose(e.key,detailMode);$('parts').append(b);}if(q&&!matches.length)$('parts').textContent=t('No matching ID.','Nenhum ID correspondente.');}
function clip(){const axis=$('axis').value;let planes=[];if(axis!=='none'){const b=boxVisible();if(!b.isEmpty()){const n={x:[-1,0,0],y:[0,-1,0],z:[0,0,-1]}[axis],i={x:0,y:1,z:2}[axis];planes=[new THREE.Plane(new THREE.Vector3(...n),b.min.getComponent(i)+(b.max.getComponent(i)-b.min.getComponent(i))*Number($('cut').value)/100)];}}for(const m of [...installed,...detail])m.material.clippingPlanes=planes;if(edge)edge.material.clippingPlanes=planes;}
function opacity(){for(const m of [...installed,...detail]){const v=['shell','bbshell'].includes(m.userData.meta.group)?Number($('opacity').value):m.userData.baseOpacity;m.material.opacity=v;m.material.transparent=v<1;m.material.depthWrite=v===1;}refresh();}
function openManual(id,step=0,view=true){manualStage=D.manual.stages.find(s=>s.id===id)||D.manual.stages[0];manualStep=Math.min(step,manualStage.steps.length-1);$('manual-stage').value=manualStage.id;$('manual-panel').hidden=false;renderManual();if(view)manualView(false);}
function manualView(explode){if(manualStage.id==='00'){applyState('PLAY');cameraPreset('PLAYER');return;}ensureDetail();detailed=true;state=explode?'EXPLODED DETAILED':'PLAY';resetGroups();stageFilter=explode&&manualStage.id!=='01'?manualStage.id:null;assemblyThrough=explode||manualStage.id==='01'?null:Number(manualStage.id);if(manualStage.id==='01')state='EXPLODED DETAILED';$('scope').value='ALL';$('detail-filter').value='both';$('family-focus').value='';$('tray').checked=true;$('service-state').value=state;select(null);refresh();frame();}
function renderManual(){const s=manualStage,step=s.steps[manualStep],hs=s.hardware.map(id=>D.hardware.find(h=>h.id===id));const quantities=hs.map(h=>{const q=D.quantity_overlay.find(q=>q.id===h.id);return h.id+' × '+(h.quantity??q?.formula??t('TBD','INDEFINIDA'))+' — '+status(h.freeze_status);});$('manual-panel').innerHTML=`<div class="row"><strong>${s.id} · ${esc(L(s.title))}</strong><button id="close-manual">${t('Close','Fechar')}</button></div><span class="badge hold">${esc(status(s.status))}</span><p class="muted">${t('FRAMEWORK ONLY · global/stage quantities, not repeated consumption.','SOMENTE ROTEIRO · quantidades globais/da etapa, não consumo repetido.')}</p><label>${t('Step','Passo')}<select id="manual-step">${s.steps.map((x,i)=>`<option value="${i}">${x.id} · ${esc(L(x.title))}</option>`).join('')}</select></label><h3>${step.id} · ${esc(L(step.title))}</h3><p>${esc(L(step.action))}</p><div class="checkpoint"><strong>${t('CHECKPOINT','VERIFICAÇÃO')}</strong><p>${esc(L(step.check))}</p></div><details><summary>${t('Parts, hardware and orientation','Peças, ferragens e orientação')}</summary><p>${esc(s.pieces.join(', ')||'—')}</p><p>${quantities.map(esc).join('<br>')}</p><p>${esc(L(step.orientation))}</p><p>${esc(L(step.faces))}</p><p>${esc(L(step.tools))}</p></details><p class="hold">${esc(L(step.hold))}</p><div class="row"><button id="step-parts">${t('Explode step parts','Explodir peças da etapa')}</button><button id="next-cad">${t('Next-state CAD','CAD após a etapa')}</button></div><button id="service-cad" class="full">${t('Service view: ','Vista de serviço: ')+esc(L({en:STATES.find(x=>x[0]===step.next_state)?.[1], 'pt-BR':STATES.find(x=>x[0]===step.next_state)?.[2]}))}</button><div class="row"><button id="prev-step">${t('Previous','Anterior')}</button><button id="next-step">${t('Next','Próximo')}</button></div><a href="../../../docs/${language==='en'?'ASSEMBLY_MANUAL.md':'ASSEMBLY_MANUAL.pt-BR.md'}#stage-${s.id}">${t('Full manual + all FACE A/B preparation cards','Manual completo + todas as fichas FACE A/B')}</a>`;$('manual-step').value=String(manualStep);$('manual-step').onchange=e=>{manualStep=Number(e.target.value);renderManual();};$('close-manual').onclick=()=>{$('manual-panel').hidden=true;resize();};$('step-parts').onclick=()=>manualView(true);$('next-cad').onclick=()=>manualView(false);$('service-cad').onclick=()=>{applyState(step.next_state);cameraPreset(Number(s.id)>=8&&Number(s.id)<=14?'BACKBOX REAR':'PLAYER');};$('prev-step').onclick=()=>{if(manualStep>0)manualStep--;else if(Number(s.id)>0){manualStage=D.manual.stages[Number(s.id)-1];manualStep=manualStage.steps.length-1;}renderManual();manualView(false);};$('next-step').onclick=()=>{if(manualStep<s.steps.length-1)manualStep++;else if(Number(s.id)<18){manualStage=D.manual.stages[Number(s.id)+1];manualStep=0;}renderManual();manualView(false);};resize();}
// Touch picking ignores drags; no hover-only operation.
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>7)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(active().filter(m=>m.visible));const hit=hits.find(h=>h.object.material.clippingPlanes.every(p=>p.distanceToPoint(h.point)>=0));select(hit?.object||null);});
$('lang-en').onclick=()=>setLanguage('en');$('lang-pt').onclick=()=>setLanguage('pt-BR');$('palette').onchange=e=>setPalette(e.target.value);$('service-state').onchange=e=>{applyState(e.target.value);if(state.startsWith('EXPLODED'))frame();};$('camera-preset').onchange=e=>cameraPreset(e.target.value);$('hide-pf').onclick=()=>quickHide();$('hide-supports').onclick=()=>quickHide(true);$('interior').onclick=()=>{applyState('INTERIOR INSPECTION');cameraPreset('INTERIOR');};$('bb-interior').onclick=()=>{applyState('BACKBOX INTERIOR');cameraPreset('BACKBOX REAR');};$('show-all').onclick=()=>{D.groups.forEach(g=>groupInputs[g.id].checked=true);hidden.clear();isolated=null;stageFilter=null;assemblyThrough=null;$('scope').value='ALL';$('family-focus').value='';$('detail-filter').value='both';refresh();};$('reset').onclick=()=>{applyState('PLAY');$('opacity').value=1;opacity();$('axis').value='none';clip();$('manual-panel').hidden=true;resize();$('scope').value='ALL';$('family-focus').value='';$('detail-filter').value='both';$('distance').value=1;cameraPreset('PLAYER');};$('search').oninput=search;$('hide').onclick=()=>{if(selected)hidden.add(selected.name);refresh();};$('isolate').onclick=()=>{isolated=selected;refresh();};$('focus').onclick=()=>selected&&frame([selected]);$('clear-selection').onclick=()=>{isolated=null;select(null);};$('opacity').oninput=opacity;$('axis').onchange=clip;$('cut').oninput=clip;$('distance').oninput=refresh;$('tray').onchange=refresh;
for(const id of ['scope','detail-filter','family-focus'])$(id).onchange=()=>{if(!detailed)applyState('EXPLODED DETAILED',{keepVisibility:true});stageFilter=null;assemblyThrough=null;refresh();if(id==='family-focus')frame();};$('frame-visible').onclick=()=>frame();$('open-manual').onclick=()=>openManual($('manual-stage').value);$('toggle-controls').onclick=()=>{document.body.classList.toggle('controls-hidden');$('toggle-controls').setAttribute('aria-expanded',!document.body.classList.contains('controls-hidden'));};$('capture').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='vpin-v332-review.png';a.click();};
function resize(){renderer.setSize(viewWidth(),stageEl.clientHeight);camera.aspect=viewWidth()/stageEl.clientHeight;camera.updateProjectionMatrix();$('state-note').style.maxWidth=Math.min(750,viewWidth()-24)+'px';$('mode-tag').style.maxWidth=(viewWidth()-24)+'px';}new ResizeObserver(resize).observe(stageEl);
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);const occupied=[];for(const l of partLabels){const p=new THREE.Box3().setFromObject(l.m).getCenter(new THREE.Vector3()).project(camera),x=(p.x+1)/2*viewWidth()+10,y=(1-p.y)/2*stageEl.clientHeight-12,w=l.el.offsetWidth||135,h=20;const rect=[x,y,x+w,y+h];l.el.hidden=p.z>1||p.z< -1||x<0||x+w>viewWidth()||y<45||y+h>stageEl.clientHeight-90||occupied.some(r=>rect[0]<r[2]&&rect[2]>r[0]&&rect[1]<r[3]&&rect[3]>r[1]);if(!l.el.hidden)occupied.push(rect);l.el.style.left=x+'px';l.el.style.top=y+'px';}
if(selected&&selected.visible){const p=new THREE.Box3().setFromObject(selected).getCenter(new THREE.Vector3()).project(camera);const e=$('callout');e.hidden=p.z>1||p.z< -1;e.style.left=Math.max(8,Math.min(viewWidth()-e.offsetWidth-8,(p.x+1)/2*viewWidth()+12))+'px';e.style.top=Math.max(44,Math.min(stageEl.clientHeight-e.offsetHeight-100,(1-p.y)/2*stageEl.clientHeight))+'px';}else $('callout').hidden=true;}
resize();setLanguage(language);applyState('PLAY');cameraPreset('PLAYER');if(innerWidth<650)document.body.classList.add('controls-hidden');
const params=new URLSearchParams(location.search);if(params.has('manual'))openManual(params.get('manual'),Math.max(0,Number((params.get('step')||'0.1').split('.')[1])-1));if(params.has('part')){const key=params.get('part'),d=D.detail.find(e=>e.key===key||e.meta.id===key);if(d)choose(d.key,true);}if(params.has('state'))applyState(params.get('state'));
window.viewer={scene,camera,renderer,controls,installed,detail,data:D,groups:groupInputs,active,applyState,cameraPreset,frame,choose,select,setLanguage,setPalette,refresh,openManual,manualView,language:()=>language,palette:()=>palette,currentState:()=>state,isDetailed:()=>detailed,selected:()=>selected,selectionEdges:()=>edge,geometryCache:geoCache};$('loading').hidden=true;document.body.dataset.viewerReady='true';animate();
})().catch(e=>{document.getElementById('loading').hidden=true;const el=document.getElementById('error');el.hidden=false;el.textContent='Viewer error / Erro: '+e.message;console.error(e);});
