"""Bilingual assembly framework editorial source. CERN-OHL-S-2.0."""
# Every tuple is canonical English / complete Brazilian Portuguese.
STAGES = [
('Before you start','Antes de começar',[],[
('Confirm the preparation holds','Confirme as pendências de preparação','Read the supplier profile and inventory the production lot. Do not cut full sheets until actual thickness, coupon clearance and hardware interfaces are approved.','Leia o perfil do fornecedor e identifique o lote de produção. Não corte chapas completas antes da aprovação da espessura real, folga do cupom e interfaces das ferragens.','Record the measured lot, coupon result and selected hardware; unresolved values stay HOLD.','Registre o lote medido, resultado do cupom e ferragens escolhidas; valores não resolvidos permanecem PENDENTES.'),
('Prepare ordinary assembly tools','Prepare as ferramentas comuns','Prepare clamps, square, tape, drill/driver, depth stop, selected bits and qualified angle guides. Exact drive sizes follow purchased hardware. Do not improvise precise angled drilling freehand.','Prepare grampos, esquadro, trena, furadeira/parafusadeira, limitador de profundidade, pontas selecionadas e guias angulares validadas. As medidas das pontas dependem das ferragens compradas. Não improvise furos angulares precisos à mão livre.','A qualified guide and finish procedure must exist before each affected manual operation.','Uma guia e um procedimento de acabamento validados devem existir antes de cada operação manual afetada.')]),
('Identify flatpack parts','Identifique as peças do kit',['00'],[
('Match manufacturing IDs and faces','Confira os IDs de fabricação e as faces','Match every M-family and P-instance against the 130-piece register. Use the orientation cards: FACE A is the finished machining datum; FACE B receives no CNC. Keep mirrored parts labelled.','Confira cada família M e instância P com o registro de 130 peças. Use as fichas de orientação: FACE A é a referência acabada de usinagem; FACE B não recebe CNC. Mantenha as peças espelhadas identificadas.','Count 130 pieces in 66 families. Do not mistake 93 installed assemblies for the cut-piece count.','Conte 130 peças em 66 famílias. Não confunda as 93 montagens instaladas com a quantidade de peças cortadas.'),
('Check CNC work and builder finish','Confira o CNC e o acabamento do montador','Use each piece’s preparation card. Check the contour and FACE A pockets first; then perform only the listed manual drilling, countersinking or corner/bevel finish after its holds clear. Depths refer to finished FACE A, including after face reduction.','Use a ficha de preparação de cada peça. Confira primeiro o contorno e os rebaixos da FACE A; depois execute somente a furação, escareamento ou acabamento manual de cantos/chanfros listado, após liberar suas pendências. As profundidades se referem à FACE A acabada, inclusive após redução de espessura.','Never request a second CNC face. Trial-fit without forcing thickness-dependent joints; physical coupon approval is mandatory.','Nunca solicite uma segunda face CNC. Teste os encaixes sem forçar juntas dependentes da espessura; a aprovação física do cupom é obrigatória.')]),
('Main cabinet shell','Caixa principal',['01'],[
('Dry-assemble sides and ends','Monte laterais e extremidades a seco','Orient SideL/SideR from the player position, front at Y0. Dry-assemble front and rear against the full-strength side structure. Keep the shell supported and unclamped enough to square.','Oriente SideL/SideR a partir da posição do jogador, frente em Y0. Monte frente e traseira a seco na estrutura integral das laterais. Mantenha a caixa apoiada, com os grampos ainda permitindo o esquadrejamento.','CABINET SQUARE CHECK: compare diagonals and seating on a flat reference. No numerical tolerance is released yet.','VERIFICAÇÃO DO ESQUADRO: compare diagonais e assentamento em uma referência plana. Nenhuma tolerância numérica foi liberada.'),
('Qualify permanent shell joints','Valide as juntas permanentes da caixa','Use the approved glue/fastener schedule when available. F06 and adhesive consumption G01 remain unresolved; this framework does not invent screw spacing. Keep joint faces free of finish until bonding is qualified.','Use o plano aprovado de colagem/fixação quando disponível. F06 e o consumo de adesivo G01 continuam indefinidos; este roteiro não inventa espaçamento de parafusos. Mantenha as faces das juntas sem acabamento até validar a colagem.','HOLD permanent assembly until the joint schedule and material/bond qualification are complete.','PENDÊNCIA: não faça a montagem permanente antes de concluir o plano das juntas e a validação do material/colagem.')]),
('Floor and structural supports','Fundo e apoios estruturais',['02'],[
('Seat floor, cleats and rear shelf','Assente o fundo, sarrafos e prateleira traseira','Fit the floor and its cleats to their exact mating shoulders. Install BBBase as the upright backbox bearing shelf; preserve the generic cable passage and lock receiver material.','Encaixe o fundo e seus sarrafos nos ressaltos correspondentes. Instale BBBase como prateleira de apoio vertical do backbox; preserve a passagem genérica de cabos e o material dos receptores das travas.','Confirm continuous floor support and the shelf’s broad bearing faces. Do not use screws to pull a distorted shell into alignment.','Confirme o apoio contínuo do fundo e as faces amplas de apoio da prateleira. Não use parafusos para alinhar uma caixa deformada.')]),
('Shelves, crossmembers and PCBase','Prateleiras, travessas e PCBase',['03'],[
('Install guides and shelf supports','Instale guias e apoios das prateleiras','Identify S1–S3 and T1–T3 with their matching supports/guides. Use the actual mounting interfaces; F05/F52/I14 are catalog hardware, not permission to guess unlocated holes.','Identifique S1–S3 e T1–T3 com seus apoios/guias correspondentes. Use as interfaces reais de montagem; F05/F52/I14 são ferragens do catálogo, não autorização para adivinhar furos sem posição definida.','SHELF HEIGHT CHECK: confirm left/right seats align and removable shelves/crossmembers can be extracted without forcing.','VERIFICAÇÃO DA ALTURA: confirme o alinhamento dos apoios esquerdo/direito e a retirada das prateleiras/travessas sem forçar.'),
('Secure removable boards','Fixe as placas removíveis','Fit shelf clamp hardware and PCBase flush floor anchors only after their stack is confirmed. PCBase is the accepted low board, not a drawer. Electronics payloads are optional later additions.','Instale as ferragens de aperto das prateleiras e ancoragens niveladas da PCBase somente após confirmar suas camadas. PCBase é a placa baixa aceita, não uma gaveta. As cargas eletrônicas são adições opcionais futuras.','Check positive retention and service removal; keep side-wall SSF zones unbridged.','Confira a retenção positiva e a remoção para manutenção; não crie travamentos nas zonas SSF das laterais.')]),
('Playfield wooden pivot supports','Apoios do pivô de madeira do playfield',['03','04'],[
('Install both open cradles','Instale os dois berços abertos','Place each 18 mm cradle directly on the cabinet floor and against its side. Preserve the open pivot relief and all six F01 coordinates. The screws retain against tipping/separation; vertical load bears on the floor.','Posicione cada berço de 18 mm diretamente no fundo e junto à lateral. Preserve o alívio aberto do pivô e as seis coordenadas F01. Os parafusos retêm contra tombamento/separação; a carga vertical se apoia no fundo.','CRADLE ALIGNMENT CHECK: both seats share the accepted axis and both feet bear continuously. Do not shim or relocate the axis without a new review.','VERIFICAÇÃO DOS BERÇOS: os dois assentos compartilham o eixo aceito e os pés se apoiam continuamente. Não calce nem reposicione o eixo sem nova revisão.')]),
('Playfield base, dowel and straps','Base do playfield, cavilha e abraçadeiras',['05'],[
('Capture the wooden dowel','Prenda a cavilha de madeira','Attach the Ø32 wooden dowel with four commercial saddle straps B01 and eight F02 screws to the playfield base. Retain the accepted replaceable adapter interface. No metal shaft or bearings.','Prenda a cavilha de madeira Ø32 com quatro abraçadeiras comerciais B01 e oito parafusos F02 na base do playfield. Preserve a interface aceita do adaptador substituível. Não use eixo metálico nem rolamentos.','Check strap seating, screw engagement and no splitting after purchased strap/material qualification.','Confira assentamento das abraçadeiras, engate dos parafusos e ausência de rachaduras após validar as abraçadeiras/material.'),
('Check seating and removal','Confira o assentamento e a retirada','Lower both dowel ends into the open seats. With main glass and matrix removed, demonstrate the accepted 48 mm vertical lift-out. The complete playfield assembly leaves together; fixed cradles remain.','Abaixe as duas pontas da cavilha nos assentos abertos. Com vidro principal e matriz removidos, demonstre a retirada vertical aceita de 48 mm. A montagem completa sai junta; os berços fixos permanecem.','DOWEL LIFT-OUT CHECK: no binding, approximately semicircular support retained. The 50° service pose is a geometric view; do not work beneath an unsupported raised assembly. Support/load qualification remains pending.','VERIFICAÇÃO DA RETIRADA: sem travamento, com apoio aproximadamente semicircular preservado. A posição de serviço de 50° é uma vista geométrica; não trabalhe sob a montagem levantada sem apoio. A validação de apoio/carga permanece pendente.')]),
('Main rear services and fans','Serviços traseiros e ventoinhas principais',['03'],[
('Fit rear door hardware','Instale as ferragens da porta traseira','Fit the main rear door, its two hinge assemblies, keeper and lock from the selected hardware. Main rear hinge hardware is separate from the backbox piano hinges. Keep selected-hardware quantities as formulas.','Instale a porta traseira principal, suas duas dobradiças, contra-fecho e fechadura com as ferragens selecionadas. Essas dobradiças são distintas das dobradiças contínuas do backbox. Mantenha as quantidades dependentes das ferragens como fórmulas.','REAR DOOR SWEEP CHECK: verify opening, latch engagement and ordinary tool access without forcing the flush door.','VERIFICAÇÃO DA PORTA TRASEIRA: confira abertura, engate do fecho e acesso com ferramenta comum sem forçar a porta nivelada.'),
('Prepare optional fan/filter stations','Prepare as estações opcionais de ventoinha/filtro','Assemble removable filter frames and selected guards. Fans are optional; M4 fastener lengths follow the actual station stack. Do not install loose fasteners into an unused opening or assume one bolt length fits every station.','Monte as molduras removíveis de filtro e grades selecionadas. As ventoinhas são opcionais; os comprimentos M4 dependem das camadas reais da estação. Não instale fixadores soltos em uma abertura sem uso nem suponha um comprimento único para todas as estações.','Filters remain serviceable; no fan or electronics purchase is required to understand the mechanical kit.','Os filtros devem permanecer acessíveis; não é necessário comprar ventoinhas ou eletrônica para compreender o kit mecânico.')]),
('Backbox shell','Estrutura do backbox',['03'],[
('Assemble the structural backbox','Monte a estrutura do backbox','Assemble 210 mm lower-depth sides, Y1146 straight-front floor, top and fixed rear frame. The side projection ahead of the floor is intentional. Maintain structural validity with both rear doors open.','Monte as laterais com profundidade inferior de 210 mm, fundo reto em Y1146, topo e quadro traseiro fixo. A projeção das laterais à frente do fundo é intencional. Preserve a integridade estrutural com ambas as portas abertas.','Confirm floor/side engagement and rear-frame squareness. F16 joint schedule and adhesive qualification remain HOLD.','Confirme o engate fundo/lateral e o esquadro do quadro traseiro. O plano de juntas F16 e a validação da colagem continuam PENDENTES.')]),
('WPC hardware and upright locks','Ferragens WPC e travas verticais',['05','08'],[
('Measure and install the WPC family','Meça e instale a família WPC','Measure 01-9011-L/R, 02-4352 and 4322-01139-12B before any final hinge drilling. The reference rotation axis is Y1066.8/Z508; it is not a released drill pattern. Do not substitute metric threads into purchased imperial hardware.','Meça 01-9011-L/R, 02-4352 e 4322-01139-12B antes de qualquer furação final. O eixo de referência é Y1066.8/Z508; ele não é um padrão de furação liberado. Não substitua roscas imperiais por métricas nas ferragens compradas.','HOLD installation until bends, floor-hole pattern, bushing and complete bolt stack are measured and validated.','PENDÊNCIA: aguarde a medição e validação das dobras, furos do fundo, bucha e conjunto completo do parafuso.'),
('Fit two rear-operated captive locks','Instale duas travas cativas operadas por trás','Retain H11 ×2 at L X130/Y1260 and R X470/Y1260 with metal-backed shelf receivers, loss protection, tethers and parking sockets. Exact purchased knob/receiver details remain provisional.','Mantenha H11 ×2 em L X130/Y1260 e R X470/Y1260 com receptores metálicos apoiados na prateleira, retenção contra perda, tirantes e alojamentos de estacionamento. Os detalhes exatos dos manípulos/receptores continuam provisórios.','UPRIGHT LOCK CHECK: floor bears broadly on shelf; both independent clamps engage and can be released/parked through open rear doors with cassette installed.','VERIFICAÇÃO DAS TRAVAS: o fundo se apoia amplamente na prateleira; os dois apertos independentes engatam e podem ser soltos/guardados pelas portas traseiras abertas com o cassete instalado.')]),
('Twin backbox rear doors','Portas traseiras duplas do backbox',['08','09'],[
('Fit hinge cleats and leaves','Instale os apoios das dobradiças e as folhas','Use the 18 mm cleats reduced from FACE A to the accepted 14 mm finished geometry. Preserve the hinge axis. Install one continuous hinge on each outer vertical edge; screw count follows the selected hinge hole schedule.','Use os apoios de 18 mm reduzidos pela FACE A à geometria acabada aceita de 14 mm. Preserve o eixo da dobradiça. Instale uma dobradiça contínua em cada borda vertical externa; a quantidade de parafusos depende do plano de furos selecionado.','No permanent center mullion. Both doors must reach the validated 100° service position upright.','Sem montante central permanente. Ambas as portas devem alcançar a posição de serviço validada de 100° com o backbox vertical.'),
('Fit passive bolts, astragal and active lock','Instale ferrolhos passivos, sobreposição e fechadura ativa','Secure passive upper/lower bolts first, then close the active leaf and keyed cam lock against the overlap. Fit replaceable perimeter and center gaskets. Open active leaf before passive leaf.','Trave primeiro os ferrolhos superior/inferior da folha passiva, depois feche a folha ativa e sua fechadura sobre a sobreposição. Instale vedações substituíveis no perímetro e no centro. Abra a folha ativa antes da passiva.','REAR DOOR SWEEP CHECK: no clash with fan bodies, loops, overlap or lock hardware. Doors are service closures, not structural shear panels.','VERIFICAÇÃO DO GIRO DAS PORTAS: sem colisões com ventoinhas, laços, sobreposição ou ferragens. As portas são fechamentos de serviço, não painéis estruturais de contraventamento.')]),
('Backbox ventilation','Ventilação do backbox',['10'],[
('Assemble intake baffles and filter frames','Monte defletores de entrada e molduras de filtro','Build each baffle from its face, top and two returns using the four actual manufacturing pieces. Keep the downward mouth open and filters removable. Qualified glue seams must not obstruct the throat.','Monte cada defletor com sua face, topo e duas laterais, usando as quatro peças reais. Mantenha aberta a saída inferior e os filtros removíveis. As juntas de cola validadas não podem obstruir a garganta.','Per door: preserve 220×80 mm inlet and 220×36 mm downward mouth before mesh effects. No thermal certification is implied.','Por porta: preserve a entrada de 220×80 mm e saída inferior de 220×36 mm antes dos efeitos da tela. Isso não implica certificação térmica.'),
('Choose blank or optional fan','Escolha tampa ou ventoinha opcional','Install the blank module for an unpowered station, or a selected 120 mm fan/accessory stack. For a moving fan, preserve the low-voltage flexible corridor and strain relief through full door motion; connectors remain builder-configurable.','Instale a tampa na estação sem ventilação ativa ou um conjunto selecionado de ventoinha/acessórios de 120 mm. Para ventoinha móvel, preserve o corredor flexível de baixa tensão e alívio de tração em todo o giro; conectores ficam a critério do montador.','Check ordinary screwdriver access with the door open; no display removal. Fine exhaust filters need later pressure-loss analysis.','Confira o acesso com chave comum e porta aberta, sem remover o monitor. Filtros finos na exaustão exigem análise posterior de perda de pressão.')]),
('Backglass carrier','Suporte do monitor do backbox',['08'],[
('Build rails, adjustable carriers and stops','Monte trilhos, suportes ajustáveis e batentes','Use the real monitor-stop bases and caps, glued on their broad faces after qualification. Fit depth shoes, clamping washers/nuts and replaceable VESA plate. Leave adjustments loose only during alignment.','Use as bases e tampas reais dos batentes, coladas pelas faces amplas após validação. Instale sapatas de profundidade, arruelas/porcas de aperto e placa VESA substituível. Deixe os ajustes soltos somente durante o alinhamento.','The mechanical carrier is retained without requiring a monitor purchase. No permanent display-specific hole pattern.','O suporte mecânico fica retido sem exigir a compra de um monitor. Sem padrão permanente de furos específico de tela.'),
('Explain later front installation and rear adjustment','Explique a instalação frontal e ajuste traseiro futuros','When selected, install the 31.5/32-inch display from the front, access alignment from the open rear doors and positively clamp every axis. VESA screws are user-adapter hardware and follow the display manufacturer.','Quando selecionado, instale o monitor de 31,5/32 polegadas pela frente, ajuste pelas portas traseiras abertas e aperte positivamente todos os eixos. Os parafusos VESA pertencem ao adaptador do usuário e seguem o fabricante do monitor.','No gravity-only hook, glass support or cassette support for display mass. Recheck retention through fold before use.','Sem gancho retido apenas pela gravidade, nem peso do monitor apoiado no vidro ou cassete. Verifique a retenção durante a dobra antes do uso.')]),
('Backbox front glass','Vidro frontal do backbox',['12'],[
('Fit liners and removable top retainer','Instale os revestimentos e retentor superior removível','Assemble the actual top-retainer cap and reduced strip. Fit side liners and padded lower support. After supplier confirmation, slide the nominal 3–4 mm tempered glass from top/front and positively secure the retainer.','Monte a tampa e tira reduzida reais do retentor superior. Instale revestimentos laterais e apoio inferior acolchoado. Após confirmação do fornecedor, deslize o vidro temperado nominal de 3–4 mm pelo topo/frente e fixe positivamente o retentor.','GLASS RETENTION CHECK: no bare plywood contact, no loose gravity-only retention. Backbox glass stays installed for normal fold; main playfield glass is different.','VERIFICAÇÃO DO VIDRO: sem contato direto com compensado e sem retenção solta apenas por gravidade. O vidro do backbox permanece na dobra normal; o vidro principal do playfield é distinto.')]),
('DMD and speaker cassette','Cassete DMD e alto-falantes',['09','12'],[
('Build and retain the removable cassette','Monte e retenha o cassete removível','Laminate each fixed cleat from two identical 12 mm layers. Install the frame, replaceable speaker baffles and DMD adapter/bezel. Preserve four positive cassette attachments and the separate monitor carrier.','Lamine cada apoio fixo com duas camadas idênticas de 12 mm. Instale quadro, baffles substituíveis dos alto-falantes e adaptador/moldura DMD. Preserve quatro fixações positivas do cassete e o suporte independente do monitor.','Confirm front removal, rear wiring access and clear normal lock access. F31 insert/baffle attachment count remains TBD; four cassette bolts do not resolve it.','Confirme remoção frontal, acesso traseiro à fiação e acesso livre às travas normais. A quantidade F31 das fixações de insertos/baffles continua indefinida; quatro parafusos do cassete não a resolvem.')]),
('Matrix mechanical carrier','Suporte mecânico da matriz',['06'],[
('Fit wood seats and removable retention','Instale assentos de madeira e retenção removível','Install the two fixed wood seats, inserts and removable retainer screws. The carrier is mechanical; LED panels and their model-specific fasteners remain future electronics. Follow the saved forward/lift removal path.','Instale os dois assentos fixos de madeira, insertos e parafusos removíveis de retenção. O suporte é mecânico; painéis LED e seus fixadores específicos são eletrônica futura. Siga o trajeto salvo de avanço/elevação.','Check both seats and removal before playfield service or backbox fold. Do not force the matrix past installed main glass.','Confira ambos os assentos e a retirada antes do serviço do playfield ou dobra do backbox. Não force a matriz com o vidro principal instalado.')]),
('Leg and lockdown interfaces','Interfaces dos pés e lockdown',['02','03'],[
('Laminate real leg-block layers','Lamine as camadas reais dos blocos dos pés','Identify each seven-layer stack bottom L1 to top L7. Front L3/L6 carry bores; rear L2 carries the lower bore and L5/L6 share the upper bore. Preserve the five distinct manufacturing profiles.','Identifique cada pilha de sete camadas de L1 inferior a L7 superior. Na frente L3/L6 contêm furos; atrás L2 contém o furo inferior e L5/L6 compartilham o superior. Preserve os cinco perfis distintos de fabricação.','HOLD diagonal drilling until the purchased leg plate/bolt pattern and a clamped drill guide are validated. Historical 58/57.15 mm disagreement is not resolved by this manual.','PENDÊNCIA: aguarde validar o padrão comprado de placa/parafusos e uma guia presa antes de furar diagonalmente. A divergência histórica 58/57,15 mm não é resolvida por este manual.'),
('Fit purchased legs and front interfaces','Instale os pés e interfaces frontais comprados','Use matched real pinball legs, bolts, backing plates and levelers. The 600 mm body uses the accepted custom-width lockdown strategy; exact receiver/fastener interfaces remain held. Mobility skates are optional external accessories.','Use pés reais de pinball com parafusos, chapas de apoio e niveladores compatíveis. A caixa de 600 mm usa a estratégia aceita de lockdown de largura personalizada; as interfaces exatas de receptor/fixadores permanecem pendentes. Patins de transporte são acessórios externos opcionais.','Keep cabinet securely supported until leg/load and attachment qualification is complete. No integrated wheels.','Mantenha a caixa apoiada com segurança até concluir a validação de carga dos pés e fixações. Sem rodas integradas.')]),
('Mechanical inspection and normal fold','Inspeção mecânica e dobra normal',['04','06','07','09','10','11','13','14','15','16'],[
('Perform the normal fold sequence','Execute a sequência normal de dobra','Open rear doors; release and park both rear-operated locks; close/latch the rear doors; remove MAIN PLAYFIELD GLASS and MATRIX; fold. Keep the cassette, secured display, DMD/speakers and backbox front glass installed. No routine electronics disconnection.','Abra as portas traseiras; solte e guarde ambas as travas traseiras; feche/trave as portas; remova o VIDRO PRINCIPAL DO PLAYFIELD e a MATRIZ; dobre. Mantenha cassete, monitor fixado, DMD/alto-falantes e vidro frontal do backbox instalados. Sem desconexão elétrica de rotina.','BACKBOX FOLD CHECK: geometry supports 0–90° pure rotation around Y1066.8/Z508. Check actual retention, cable slack, surroundings and handling only after physical qualification. Reverse the sequence and positively engage both locks upright.','VERIFICAÇÃO DA DOBRA: a geometria permite rotação pura de 0–90° em Y1066.8/Z508. Confira retenção real, folga dos cabos, entorno e manuseio somente após validação física. Inverta a sequência e engate positivamente as duas travas na vertical.'),
('Separate rare hinge maintenance','Separe a manutenção rara das dobradiças','Rare WPC hinge service may require lower-cassette removal and playfield lift-out/removal for side-pivot access. This is not the normal fold procedure. Keep all unqualified structural/ergonomic gates visible.','A manutenção rara das dobradiças WPC pode exigir remoção do cassete inferior e retirada do playfield para acessar o pivô lateral. Esse não é o procedimento normal de dobra. Mantenha visíveis todas as pendências estruturais/ergonômicas.','Final inspection is a checkpoint framework, not structural certification or manufacturing authorization.','A inspeção final é um roteiro de verificação, não certificação estrutural nem autorização de fabricação.')]),
('Future electronics overview','Visão geral da eletrônica futura',['17'],[
('Use reserved zones and replaceable adapters','Use zonas reservadas e adaptadores substituíveis','Add displays, PC, DMD, speakers, SSF, controllers or toys later using the reserved envelopes and replaceable mounting boards. Preserve both side toy zones and generic cable passage. No mandatory toy shelf or connector family.','Adicione monitores, PC, DMD, alto-falantes, SSF, controladores ou brinquedos depois, usando os volumes reservados e placas substituíveis. Preserve ambas as zonas laterais e a passagem genérica de cabos. Sem prateleira obrigatória para brinquedos ou família obrigatória de conectores.','Keep electronics separate from the mandatory mechanical kit. Heavy devices need positive retention; power/electrical design is outside this manual framework.','Mantenha a eletrônica separada do kit mecânico obrigatório. Dispositivos pesados exigem retenção positiva; o projeto de potência/elétrica está fora deste roteiro.')])
]
