"""V34 source/deviation ledger, bilingual assembly source and review report. CERN-OHL-S-2.0."""
from pathlib import Path
import json,copy,collections
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/backbox-v34';B=R/'exports/generated/service-productization-v338'
def read(p):return json.loads(Path(p).read_text())
def dump(p,j):Path(p).write_text(json.dumps(j,indent=2,ensure_ascii=False)+'\n')
def bi(a,b):return {'en':a,'pt-BR':b}
g=read(O/'geometry-validation.json');assert g['pass'];reg=read(O/'manufacturing-register.json');mass=read(O/'mass-counts.json');cat=read(R/'config/hardware_catalog_v34.json');C=read(R/'config/backbox_simplification_v34.json')
url='https://www.tukkari.eu/advisor/assembly-guide-vpin-cabinet-essential-flat-pack'
product='https://www.tukkari.eu/p/widebody-virtual-pinball-cabinet-vpin-essential-flat-pack-kit'
sources=[{'id':'TUKKARI_GUIDE','url':url,'accessed':'2026-10-03','status':'PUBLIC_MANUFACTURER_REFERENCE_VISUALLY_INSPECTED','license':'Copyright Tukkari; links only, no repository copy','evidence':'Steps1/5/9/13/14/15/16/19 reviewed. Flat slotted monitor board and four metal brackets; metal combined lower panel; direct top-to-side assembly. Text explicitly says backbox is not glued.'},{'id':'TUKKARI_PRODUCT','url':product,'accessed':'2026-10-03','status':'PUBLIC_MANUFACTURER_DESCRIPTION','license':'Copyright Tukkari; no CAD copied','evidence':'32-inch VESA75/100 support,15.6-inch combined metal DMD/speaker panel, glass-channel interface; proprietary5-axis/Lamello shell process.'}]
dev=[{'subsystem':'MONITOR','equivalent_found':True,'public_evidence':url,'equivalent':'Single slotted plate, four commodity corner brackets in public step15/16','our_conflict':'Owner explicitly requires top-inserted captured plate, no brackets; one-face CNC side guides are possible with14mm remaining side skin','why_direct_adaptation_fails':'Public bracket scheme conflicts with explicit owner service/capture correction; not falsely attributed to Tukkari','minimum_deviation':'Independent4mm guides,2 identical stops,top capture; no service rail or bracket','adopted':'One plate; bolts/spacers adjust monitor; front monitor service'}, {'subsystem':'DMD_SPEAKER','equivalent_found':True,'public_evidence':url+'#step14','equivalent':'One combined metal lower panel with display opening and speaker apertures','our_conflict':'Owner requires one flat plywood panel. A front visible cutout removes the central wood required at rear VESA75 boss coordinates. Old103mm speaker rear envelope conflicts with protected intake baffles when panel is rearward enough for fold.','why_direct_adaptation_fails':'Flat plywood cannot duplicate bent-metal rear mounting returns; no hidden rear adapter added','minimum_deviation':'Direct display on FRONT of structural panel, VESA screws from rear; selected speaker must fit60mm rear reserve.18mm follows12-first deflection screen.','adopted':'One off-cabinet preassembled lower module,4 direct side fasteners'}, {'subsystem':'BACKGLASS','equivalent_found':True,'public_evidence':product,'equivalent':'Front glass/channel seating interface documented; exact requested front tilt/top-strip mechanism not established by viewed guide','our_conflict':'Owner specifies tempered glass and front tilt removal with fixed top, not source acrylic/sliding assumption','why_direct_adaptation_fails':'Cannot claim unobserved source capture geometry; owner sequence governs independent fit','minimum_deviation':'Two shallow front rebates,one18mm bottom seat,one12mm upper strip.6mm lower lip exceeds3.8mm top travel.','adopted':'Simple padded front window with positive edge capture'}, {'subsystem':'TOP','equivalent_found':True,'public_evidence':url,'equivalent':'Direct top-to-sides; proprietary connector scheme; source says no backbox glue','our_conflict':'Owner allows glue, simple screws; supplier cannot5-axis edges; Kreg model unconfirmed','why_direct_adaptation_fails':'Unselected jig cannot release pocket offsets; proprietary connector cuts not used','minimum_deviation':'Existing shallow capture +glue +4 direct side screws; pocket alternative4 studied but not selected','adopted':'No corner cleats'}]
dump(O/'sources.json',sources);dump(O/'tukkari-first-audit.json',dev)
# Authoritative owner25-step order. Full old unrelated stages remain.
data=[
('Identify the two sides','Identifique as duas laterais',['BB_SideL','BB_SideR'],[],'Confirm inside FACE_A and front/back before drilling.','Confirme FACE_A interna e frente/trás antes de furar.'),
('Attach both fixed stops','Fixe os dois batentes',['BB_MONITOR_STOP_L','BB_MONITOR_STOP_R'],['F64'],'Use2 direct screws per12x40x30 stop; tops atZ854.','Use2 parafusos diretos por batente12x40x30; topo emZ854.'),
('Inspect inside guides','Inspecione as guias internas',['BB_SideL','BB_SideR'],[],'4mm capture; width follows measured plate and coupon. R2 bottom extension clears plate corners.','Captura4mm; largura conforme placa real e cupom. Extensão inferiorR2 libera os cantos.'),
('Join floor to sides','Una o fundo às laterais',['BB_Floor','BB_SideL','BB_SideR','BB_RearFrame'],['F54','F16'],'Preserve210mm lower side andY1146 floor.','Preserve lateral inferior210mm e fundoY1146.'),
('Square shell','Confira o esquadro',['BB_Floor','BB_SideL','BB_SideR'],[],'Dry fit; measure diagonals before fastening.','Monte a seco; confira diagonais antes da fixação.'),
('Lower monitor plate from TOP','Baixe a placa VESA pelo TOPO',['BB_MONITOR_PLATE'],[],'Top must not yet be installed. Plate is a permanent structural interface.','Topo ainda fora. A placa é interface estrutural permanente.'),
('Engage both guides','Engate as duas guias',['BB_MONITOR_PLATE'],[],'Keep plate square; never force coupon-unqualified fit.','Mantenha esquadro; não force encaixe sem validar cupom.'),
('Seat on both stops','Assente nos dois batentes',['BB_MONITOR_PLATE','BB_MONITOR_STOP_L','BB_MONITOR_STOP_R'],[],'Confirm both lower bearing contacts, no hanging corner.','Confirme ambos os apoios inferiores, sem canto suspenso.'),
('Install top','Instale o topo',['BB_Top'],[],'Top closes guide exits and captures plate.','Topo fecha as guias e captura a placa.'),
('Fasten top directly to sides','Fixe o topo diretamente às laterais',['BB_Top','BB_SideL','BB_SideR'],['F63','G01'],'Glue plus4 direct side screws; pilot/countersink qualified for actual stock. Pocket alternative not selected.','Cola e4 parafusos laterais diretos; piloto/escareado conforme material real. Alternativa pocket não selecionada.'),
('Check captured plate','Confira a placa capturada',['BB_MONITOR_PLATE','BB_Top'],[],'No upward removal with top installed; no extra L-brackets.','Sem saída superior com topo fixo; sem cantoneiras extras.'),
('Bring monitor from FRONT','Entre com o monitor pela FRENTE',['BB_Display32'],[],'Glass/strip out. Enter at+5mm height to clear bottom glass lip, then adjust from rear.','Vidro/tira fora. Entre5mm acima para liberar assento do vidro; depois ajuste por trás.'),
('Fit rear VESA bolts','Coloque os parafusos VESA por trás',['BB_MONITOR_PLATE','BB_Display32'],['F29','W13'],'Use one75 or100 pattern;4 bolts. Support monitor while loose.','Use padrão75 ou100;4 parafusos. Sustente o monitor enquanto solto.'),
('Set image height','Ajuste a altura da imagem',['BB_Display32'],['F29'],'Slots permit+/-5mm. Verify visible opening; selected monitor controls exact drilling.','Rasgos permitem+/-5mm. Confira janela; monitor real define furação.'),
('Set depth with spacers','Ajuste profundidade com espaçadores',['BB_Display32'],['B19'],'Study0/3/6/9/12mm. Verify engagement and no bottoming; never use wooden shoes.','Estudo0/3/6/9/12mm. Confira engate sem chegar ao fundo; sem sapatas de madeira.'),
('Tighten and check monitor','Aperte e confira o monitor',['BB_Display32'],['F29'],'Monitor retained through fold independently of glass. Purchased hardware load proof remains required.','Monitor retido na dobra independentemente do vidro. Ensaio de ferragens ainda obrigatório.'),
('Mount DMD on loose panel','Monte o DMD no painel solto',['BB_DMD_SPEAKER_PANEL','BB_DMDEnvelope'],['F33','W13'],'DMD sits in front of plate; rear VESA75, +/-2mm height. Body plus spacers must fit400x200x45 reserve.','DMD à frente da placa; VESA75 por trás, altura+/-2mm. Corpo com espaçadores dentro da reserva400x200x45.'),
('Mount both speakers','Monte os dois alto-falantes',['BB_DMD_SPEAKER_PANEL','BB_SpeakerEnvelopeL','BB_SpeakerEnvelopeR'],[],'Direct mounts; actual diameter/pitch pending. Maximum60mm rear body reserve.','Fixação direta; diâmetro/passo reais pendentes. Reserva traseira máxima60mm.'),
('Insert completed panel from FRONT','Insira o painel completo pela FRENTE',['BB_DMD_SPEAKER_PANEL','BB_DMDEnvelope','BB_SpeakerEnvelopeL','BB_SpeakerEnvelopeR'],[],'Electronics are optional; blank mechanical panel can be assembled first.','Eletrônica opcional; painel mecânico cego pode ser instalado primeiro.'),
('Locate panel in side seats','Posicione o painel nos rebaixos',['BB_DMD_SPEAKER_PANEL'],[],'Rear face seats atY1197; confirm4 attachment axes.','Face traseira assenta emY1197; confira4 eixos de fixação.'),
('Secure four panel bolts','Fixe os quatro parafusos do painel',['BB_DMD_SPEAKER_PANEL'],['F30','I12'],'Two each side; cross-dowels captive in panel. No cassette frame/cleats.','Dois por lado; porcas cilíndricas cativas. Sem quadro/cleats de cassete.'),
('Install glass from FRONT','Instale o vidro pela FRENTE',['BB_Backglass','BB_GLASS_BOTTOM_SEAT'],['G08','G09','G10'],'Reverse screened removal: approach tilted10degrees with bottom elevated7mm, lower6mm, tilt upright, lower1mm onto pads. Top stays fixed.','Inverta a remoção testada: aproxime inclinado10graus com base7mm acima, baixe6mm, incline à vertical e baixe1mm nos apoios. Topo fixo.'),
('Install upper retaining strip','Instale a tira superior',['BB_GLASS_TOP_RETAINER'],['F65','I08'],'One12mm strip overlaps upper edge8.2mm; two upward fasteners accessible from front/below.','Uma tira12mm sobrepõe borda8,2mm; dois fixadores para cima acessíveis pela frente/baixo.'),
('Tighten strip screws','Aperte os parafusos da tira',['BB_GLASS_TOP_RETAINER'],['F65'],'Do not clamp bare glass hard; fit liner and selected screw engagement.','Não comprima vidro nu; ajuste revestimento e engate dos parafusos.'),
('Verify retention in every orientation','Confira retenção em todas as orientações',['BB_Backglass','BB_GLASS_TOP_RETAINER'],[],'6mm bottom lip exceeds3.8mm top travel. Side overlap4mm. Geometry pass is not impact qualification.','Lábio inferior6mm excede curso superior3,8mm. Captura lateral4mm. Geometria aprovada não certifica impacto.')]
oldmanual=read(B/'assembly-manual.json');manual=copy.deepcopy(oldmanual);manual['version']='V34';manual['geometry_authority']='config/backbox_simplification_v34.json';manual['source_geometry_unchanged']=False;manual['manufacturing_release']=False;manual['current_manufacturing_register']='exports/generated/backbox-v34/manufacturing-register.json'
rowsby=collections.defaultdict(list)
for a in reg['parts']:rowsby[a['source_component']].append(a['instance_id'])
steps=[]
for i,(en,pt,names,hardware,act,actpt) in enumerate(data,1):
 sid=f'08.{i}';ids=[pid for n in names for pid in rowsby.get(n,[n])];steps.append({'id':sid,'title':bi(en,pt),'status':'WAITING_FOR_PHYSICAL_MEASUREMENT','component_ids':ids,'hardware_ids':hardware,'quantity_scope':'STAGE_TOTALS_NOT_REPEATED','orientation':bi('X left/right;Y rear;Z up. Use FACE_A card.','X esquerda/direita;Y trás;Z cima. Use ficha FACE_A.'),'faces':bi('FACE_A machined. FACE_B no CNC. Edge bores only with qualified manual guide.','FACE_A usinada. FACE_B sem CNC. Furos de borda somente com guia manual validada.'),'tools':bi('Square, clamps, selected screwdriver/hex drive, qualified drill guide/depth stop.','Esquadro, grampos, chave selecionada, guia de furação/limitador validados.'),'action':bi(act,actpt),'check':bi('Confirm stage fit and positive attachment before proceeding. '+act,'Confirme encaixe e fixação positiva antes de prosseguir. '+actpt),'hold':bi('Actual materials, coupon and purchased hardware required. No CNC release.','Material real, cupom e ferragens compradas obrigatórios. Sem liberação CNC.'),'next_state':'EXPLODED DETAILED','checkpoint':i in [3,5,8,11,16,21,25],'animation_id':'assembly-'+sid,'review_view':f'exports/generated/backbox-v34/{min(i+1,26):02d}-review.png'})
manual['stages']=[s for s in manual['stages'] if s['id'] not in ['08','12','13','14']]
manual['stages'].append({'id':'08','title':bi('Simplified backbox: captured plate, front service','Backbox simplificado: placa capturada, serviço frontal'),'depends_on':['03'],'status':'WAITING_FOR_PHYSICAL_MEASUREMENT','pieces':[a['instance_id'] for a in reg['parts'] if a['source_component'].startswith('BB_')],'hardware':['F63','F64','F65','F29','F30','I12','F33'],'steps':steps});manual['stages'].sort(key=lambda a:int(a['id']))
validids={a['instance_id'] for a in reg['parts']};retiredids={a['instance'] for a in reg['retired_rows']}
for st in manual['stages']:
 st['depends_on']=['08' if x in ['12','13','14'] else x for x in st.get('depends_on',[])];st['pieces']=[p for p in st.get('pieces',[]) if p not in retiredids]
 for t in st['steps']:
  t['component_ids']=[p for p in t['component_ids'] if p not in retiredids]
# Current operational vocabulary, preserving unrelated matrix cassette terminology.
raw=json.dumps(manual,ensure_ascii=False)
for old,new in [('backbox rail and hinge cleats','retained rear-door hinge cleats'),('with cassette installed','with lower panel installed'),('Keep the cassette,','Keep the lower panel,'),('lower-cassette removal','lower-panel removal'),('cassete inferior','painel inferior'),('cassete instalado','painel inferior instalado')]:raw=raw.replace(old,new)
manual=json.loads(raw)
# Preparation rebuilt from authoritative rows; no stale monitor ladder operations.
manual['hardware_quantity_overlay']=[{'id':h['id'],'quantity':h['quantity'],'status':h['quantity_status'],'notes':h['notes']} for h in cat['hardware'] if h.get('active',True) and h.get('design_status')!='RETIRED']
manual['v335_changed_part_preparation']=[a for a in manual.get('v335_changed_part_preparation',[]) if a.get('instance_id') in validids and a.get('instance_id') not in read(O/'manufacturing-delta.json')['changed_rows']]
manual['part_preparation']={a['instance_id']:{'id':a['manufacturing_part_id'],'source':a['source_component'],'FACE_A':a['face_A_outward_world'],'FACE_B':'NO CNC','status':a['manufacturing_status'],'manual_finish':a.get('manual_finish',[])} for a in reg['parts']}
dump(O/'assembly-manual.json',manual)
for lang,path in [('en','docs/ASSEMBLY_MANUAL.md'),('pt-BR','docs/ASSEMBLY_MANUAL.pt-BR.md')]:
 lines=['# '+('Assembly manual — V34 framework' if lang=='en' else 'Manual de montagem — roteiro V34'),'','**'+('NOT FOR CNC. Physical qualification, production-lot stock and coupon remain pending. Raised playfield support remains HOLD.' if lang=='en' else 'NÃO LIBERADO PARA CNC. Qualificação física, material do lote e cupom pendentes. Apoio do playfield elevado permanece PENDENTE.')+'**','',('Backbox plate: TOP insertion during assembly only. Monitor/glass/lower panel: FRONT service. No top disassembly for monitor replacement.' if lang=='en' else 'Placa do backbox: inserção pelo TOPO somente na montagem. Monitor/vidro/painel inferior: serviço pela FRENTE. Sem desmontar topo para trocar monitor.'),'']
 for st in manual['stages']:
  lines+=['## '+st['id']+' — '+st['title'][lang],'']
  for t in st['steps']:
   lines+=['### '+t['id']+' — '+t['title'][lang],'',t['action'][lang],'',('Parts' if lang=='en' else 'Peças')+': '+', '.join(t['component_ids'])+'.',('Hardware' if lang=='en' else 'Ferragens')+': '+(', '.join(t['hardware_ids']) or '—')+'.',('Quantity: ' if lang=='en' else 'Quantidade: ')+str(t.get('quantities','See authoritative catalog; never multiply repeated IDs.')),t['orientation'][lang],t['faces'][lang],t['tools'][lang],('Viewer: ' if lang=='en' else 'Viewer: ')+t.get('next_state','EXPLODED DETAILED'),('Check: ' if lang=='en' else 'Confira: ')+t['check'][lang],t['status']+' — '+t['hold'][lang],'']
 lines+=['## '+('CNC provided / builder finish' if lang=='en' else 'CNC fornecido / acabamento manual'),'']
 for a in reg['parts']:
  lines += ['- **'+a['instance_id']+' / '+a['manufacturing_part_id']+'** — FACE_A '+str(a['face_A_outward_world'])+'; FACE_B NO CNC. '+a['manufacturing_status']+'. '+'; '.join(op.get('operation','')+' / '+op.get('face_datum',op.get('face','FACE_A'))+' / '+str(op.get('depth_range_from_face_A_mm',op.get('depth_mm','HOLD')))+' — '+op.get('instruction','') for op in a.get('manual_finish',[]))+' [Exact local axes / eixos locais](../exports/generated/backbox-v34/assembly-manual.json)']
 lines+=['[V34 CAD review](../exports/generated/backbox-v34/review.html) · [BOM](../exports/generated/backbox-v34/manufacturing-bom.csv)','',('Quantities are stage totals, never multiply repeated mentions. Electronics remain optional; purchased hardware controls final bores and thread engagement.' if lang=='en' else 'Quantidades são totais da etapa; não multiplique menções repetidas. Eletrônica opcional; ferragens compradas definem furos e engate final.'),'','CERN-OHL-S-2.0 · Source Location: https://github.com/advpeterrobinson-hash/vpin-cabinet']
 (R/path).write_text('\n'.join(lines)+'\n')
print('V34_DOCUMENTATION',len(steps),'backbox steps',len(manual['stages']),'stages')
