"""V33.8 bilingual shop-block, support-hold and modularity manual. CERN-OHL-S-2.0."""
from pathlib import Path
import json,copy,csv,re
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/service-productization-v338'
def read(p):return json.loads((R/p).read_text())
def dump(p,v):(R/p).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def bi(en,pt):return {'en':en,'pt-BR':pt}
def fmt(x):
 if x is None:return 'HOLD'
 if isinstance(x,(int,float)):return f'{x:.3f}'.rstrip('0').rstrip('.') or '0'
 if isinstance(x,list):return ' / '.join(fmt(v) for v in x)
 return str(x)
C=read('config/service_productization_v338.json');reg=read(str(O.relative_to(R))+'/manufacturing-register.json');parts=reg['parts'];by={p['instance_id']:p for p in parts};cat=read('config/hardware_catalog_v338.json');manual=read('exports/generated/two-stock-user-module-v337/assembly-manual.json')
manual.update(version='V33.8',source_head=C['head_before'],source_geometry_unchanged=False,prior_unrelated_geometry_unchanged=True,geometry_authority='config/service_productization_v338.json',current_manufacturing_register=str(O.relative_to(R))+'/manufacturing-register.json',primary_service_support_status='HOLD_NO_DEFINED_PRIMARY_50_DEG_SUPPORT',safety_straps_promoted=False)
repl={f'P09{side}-Layer{i}':f'P09{side}-Solid' for side in [5,6] for i in [1,2,3]}
def ids(v):return list(dict.fromkeys(repl.get(x,x) for x in v))
for s in manual['stages']:
 s['pieces']=ids(s['pieces']);s['hardware']=[h for h in s['hardware'] if h!='F60']
 for t in s['steps']:t['component_ids']=ids(t['component_ids']);t['hardware_ids']=[h for h in t['hardware_ids'] if h!='F60']
steps={t['id']:t for s in manual['stages'] for t in s['steps']}
steps['05.2']['title']=bi('Review front-landing interfaces and holds','Revise interfaces e pendências dos apoios frontais')
steps['05.2']['action']=bi('Prepare the two SW02 shop-made solid landing bodies using step 06.0. No lamination, binder screw or glue-to-side operation remains. Preserve the eight side-retention screws and qualified M8/M6 interfaces. Do not install or drill until actual purchased hardware, wood quality and guide/coupon are qualified.', 'Prepare os dois corpos maciços SW02 de marcenaria conforme etapa 06.0. Não há laminação, parafuso de união ou colagem à lateral. Preserve os oito parafusos laterais e interfaces M8/M6 qualificadas. Não instale nem fure antes de qualificar ferragens compradas, madeira e guia/cupom.')
steps['05.2']['faces']=bi('SHOP TOP A / INNER B / FRONT — NO CNC. Side-specific template plus qualified clamped portable 90° drill guide and depth stop.', 'TOPO A / INTERNA B / FRENTE DE MARCENARIA — SEM CNC. Gabarito do lado correto mais guia portátil qualificada de 90° grampeada e limitador de profundidade.')
steps['06.2']['action']=bi('Remove the main playfield glass and matrix. With the assembly independently supported, release both captive retainers to their parked limits. Seat both ends of the Ø32 wooden dowel fully in the rear cradles, then lower onto the front pads at X72/X528, Y245. SW02 solid blocks replace the former three-layer bodies without moving the mating envelope. T1/T2/T3 remain intentionally clear and are not playfield supports. Preserve the 52 mm inset, 87 mm relief length, R8 transitions and 396 mm front width. Retention release is the existing 10.5 mm reference travel after unscrewing; exact purchased stack remains held.',
'Remova o vidro principal e a matriz. Com o conjunto sustentado independentemente, solte os dois retentores cativos até a posição liberada. Assente completamente as pontas da cavilha de madeira Ø32 nos berços traseiros e abaixe nos apoios frontais X72/X528, Y245. Blocos maciços SW02 substituem os antigos corpos laminados sem mover o envelope de contato. T1/T2/T3 continuam intencionalmente livres e não apoiam o playfield. Preserve recuo52 mm, comprimento87 mm, transições R8 e largura frontal396 mm. A liberação mantém curso de referência10,5 mm após desrosquear; a pilha real comprada continua pendente.')
steps['06.3']['action']=bi('Reproduce the unchanged 9.906669° PLAY pose with the rear dowel fully seated and equal left/right front height. Mechanical hardware travel remains ±3 mm, but the validated installed common-height geometry screen is only −1.9 to +0.9 mm about the reference, maintaining the requested 1 mm clearance. This is a setup/tolerance screen, not user-selectable angle adjustment or left/right twist permission. −3 mm hits the front button envelope; +3 mm hits the main glass. After qualified setup, lock both adjuster nuts and reset each captive M6 stop for the qualified receiver engagement; the original 7 mm reference is not a selected insert depth. Open the coin door and use the compact spanner to engage both original captive M6 ×100 hex-bolt retainers. Tool-free grip and quick-pin alternatives are not selected. Retainers resist uplift/rattle and do not replace broad pad support. For opening/lift-out, provide an independently qualified primary service support first, then release/park both retainers. The modeled 0–50° and 48 mm paths are geometric clearances only: CURRENT has no defined/proven primary support at 50°.',
'Reproduza a posição PLAY inalterada de9,906669° com cavilha traseira totalmente assentada e mesma altura frontal esquerda/direita. O curso mecânico continua ±3 mm, mas o teste geométrico instalado de altura comum valida somente−1,9 a+0,9 mm em torno da referência, com folga exigida1 mm. É teste de ajuste/tolerância, não seleção de inclinação nem permissão de torção esquerda/direita. −3 mm atinge o envelope dos botões; +3 mm atinge o vidro principal. Após ajuste qualificado, trave as contraporcas e redefina o batente M6 para o engate qualificado; referência7 mm não é profundidade de inserto selecionado. Abra a porta de moedas e use chave compacta para engatar ambos os parafusos sextavados cativos M6 ×100 originais. Manípulo e pino rápido não foram selecionados. Retentores resistem à elevação/vibração, sem substituir apoio nos contatos. Antes de abrir/remover, forneça apoio primário independente qualificado e solte/estacione os retentores. Trajetos modelados0–50° e48 mm são somente folgas geométricas: CURRENT não tem apoio primário definido/comprovado em50°.')
primary=bi('OPERATIONAL HOLD: do not service beneath a raised playfield until an independently qualified primary support is defined. No safety straps are promoted. Secondary straps must never replace the primary support or set the service angle. Hardware/material/load/coupon qualification and CNC remain blocked.',
'PENDÊNCIA OPERACIONAL: não trabalhe sob o playfield elevado até definir apoio primário independente qualificado. Nenhuma cinta de segurança foi promovida. Cintas secundárias nunca substituem o apoio principal nem definem o ângulo de serviço. Ferragens/material/carga/cupom e CNC continuam bloqueados.')
for sid in ['00.1','06.1','06.2','06.3','17.2']:
 steps[sid]['hold']=copy.deepcopy(primary)
steps['06.3']['check']=bi('CLOSED SUPPORT CHECK: rear seated, both pads in contact, crossmembers clear, both captive retainers engaged. SAFE ADJUSTMENT SCREEN: stay within −1.9/+0.9 mm only while reproducing the required nominal pose; purchased tolerances and differential leveling need physical verification. PRIMARY SERVICE SUPPORT HOLD before raising.',
'VERIFICAÇÃO FECHADA: traseira assentada, dois contatos apoiados, travessas livres e retentores cativos engatados. TESTE DE AJUSTE: limite−1,9/+0,9 mm apenas para reproduzir a posição nominal exigida; tolerâncias compradas e nivelamento diferencial exigem verificação física. APOIO PRIMÁRIO DE SERVIÇO PENDENTE antes de elevar.')
sw=copy.deepcopy(steps['06.2']);sw.update(id='06.0',title=bi('Prepare and install SW02 solid landing blocks','Prepare e instale os blocos maciços SW02'),status='WAITING_FOR_PHYSICAL_MEASUREMENT',component_ids=['P095-Solid','P096-Solid'],hardware_ids=['F59','F61','H27','I15','I16','I17','I18','W11','W12','B17'],animation_id='assembly-06.0',next_state='PLAYFIELD LANDINGS')
sw['faces']=bi('SHOP DATUM: square side/rear/top faces on the SW02 drawing. No CNC sheet or plywood lamination. Use the side-specific 1:1 paper center template only with its calibration bar and a qualified clamped 90° drill guide.','DATUM DE MARCENARIA: faces lateral/traseira/superior esquadrejadas no desenho SW02. Sem chapa CNC ou laminação. Use gabarito de centros em papel1:1 do lado correto apenas com barra de escala conferida e guia90° qualificada e grampeada.')
sw['action']=bi('Order two dry, stable, straight, knot-free solid-wood blanks to the actual 68 ×70 ×54 mm specification. Check square and grain orientation. The shop-made body reproduces the accepted external/mating union; obsolete binder holes are filled because there is no lamination. Drill only after actual M8 insert, M6 retention path and side screws are selected. Clamp the qualified guide and use depth stops; no precise freehand drilling. Preserve eight side screws and the original M8 adjusters/captive M6 retention. Four F60 binder screws and all lamination glue operations are removed. Do not glue the removable landing body to the cabinet side.',
'Encomende dois blocos de madeira maciça seca, estável, reta e sem nós na especificação real68 ×70 ×54 mm. Confira esquadro e direção das fibras. O corpo de marcenaria reproduz a união externa/de contato aceita; furos antigos de união são preenchidos porque não há laminação. Fure somente após escolher inserto M8, caminho de retenção M6 e parafusos laterais reais. Grampeie guia qualificada e use limitadores; sem furação precisa à mão livre. Preserve oito parafusos laterais, reguladores M8 e retenção M6 cativa originais. Quatro F60 e toda colagem de lâminas são eliminados. Não cole o apoio removível à lateral do gabinete.')
sw['check']=bi('Match the side-specific SW02 template and unchanged X72/X528, Y245 contact datum; verify full side contact and all selected insert/bolt bores before cabinet installation. No template is drilling release without actual hardware and coupon/guide qualification.',
'Confira gabarito SW02 do lado correto e datum de contato inalterado X72/X528, Y245; verifique contato lateral pleno e furos selecionados antes de instalar. O gabarito não libera furação sem ferragens reais e qualificação do cupom/guia.')
sw['validation']={'physical_trajectory_validated':False,'animation_class':'SCHEMATIC_ASSEMBLY_ANIMATION','evidence':'geometry-validation.json','manufacturing_release':False}
for stage in manual['stages']:
 if stage['id']=='06':stage['steps'].insert(0,sw)
opt=copy.deepcopy(steps['18.1']);opt.update(id='18.2',title=bi('Optional accessory boards and cable route zones','Placas opcionais e zonas de cabos'),status='OPTIONAL',component_ids=['ACC01-S2','ACC01-S3'],hardware_ids=[],animation_id='assembly-18.2',next_state='MODULARITY STUDY')
opt['action']=bi('Keep the open S1/S2/S3 and T1/T2/T3 architecture. Optional ACC01 is one 100 ×120 ×12 mm board family; sampled positions are S2 right with rear-edge clamps and S3 left with front-edge clamps. Use two physically selected removable screw clamps per chosen board, with the shelf carrying gravity load. No new permanent holes or dense grid. Small impact toys require separate retention/load qualification; this screen proves clearance only. Reuse 6 ×22 R3 strain-relief slots; retain compact existing backbox6 ×16 R3 and underfront4 ×12 R2 exceptions. Left low SIGNAL and right low ELV POWER routes are planning zones; protected mains routing remains separate.',
'Preserve arquitetura aberta S1/S2/S3 e T1/T2/T3. ACC01 opcional é uma família100 ×120 ×12 mm; exemplos ficam à direita de S2 com grampos na borda traseira e à esquerda de S3 com grampos frontais. Use dois grampos de parafuso removíveis fisicamente selecionados por placa, com carga vertical apoiada na prateleira. Sem novos furos permanentes ou grade densa. Brinquedos de impacto exigem validação própria de retenção/carga; este teste prova apenas folgas. Reuse rasgos6 ×22 R3; preserve exceções compactas6 ×16 R3 no backbox e4 ×12 R2 sob a frente. SINAL baixo à esquerda e POTÊNCIA ELV baixa à direita são zonas de planejamento; alimentação de rede protegida permanece separada.')
opt['check']=bi('Remove optional board/clamps before independent shelf extraction and release the S3 cable-anchor clamp. The current PF400 mm loop passes63 geometric states without routine service disconnection; primary raised support remains HOLD. Backbox generic passage/slots are retained, but no continuous selected fold harness is validated. Do not cut the held central VESA service window.',
'Remova placa/grampos opcionais antes de retirar a prateleira e solte o grampo de cabo em S3. Laço PF400 mm passa63 estados geométricos sem desconexão rotineira; apoio primário elevado continua PENDENTE. Passagem/rasgos genéricos do backbox são preservados, mas nenhum chicote contínuo de dobra selecionado foi validado. Não corte a janela central VESA pendente.')
opt['hold']=bi('OPTIONAL; excluded from minimum BOM, sheets, mass and packing. Clamp SKU/body/throat, payload rating, actual cable bends and supported backbox route remain HOLD. No electrical connector choice is prescribed.','OPCIONAL; fora da BOM mínima, chapas, massa e embalagem. SKU/corpo/garganta do grampo, capacidade de carga, curvaturas reais e rota apoiada do backbox permanecem PENDENTES. Nenhum conector elétrico é imposto.')
opt['validation']={'physical_trajectory_validated':False,'animation_class':'SCHEMATIC_ASSEMBLY_ANIMATION','evidence':'modularity-validation.json','manufacturing_release':False}
for stage in manual['stages']:
 if stage['id']=='18':stage['steps'].append(opt)
# Document remaining permanent layout holds rather than inventing side machining.
hold=bi('DRY-FIT DATUM HOLD: shelf support/cradle axes match side references. T-guide wall anchors have no matching side pilots; backbox rail and hinge cleats need qualified placement templates. Captured shell F06 reinforcement remains unresolved. Do not ask the builder to invent these permanent locations.',
'PENDÊNCIA DE DATUM NO AJUSTE SECO: eixos dos suportes/berços coincidem com referências laterais. Fixações dos guias T não têm pilotos correspondentes na lateral; sarrafos de trilhos/dobradiças do backbox precisam de gabaritos de posição qualificados. Reforço F06 da caixa capturada permanece indefinido. Não exija que o construtor invente essas posições permanentes.')
for lang in hold:steps['02.1']['hold'][lang]+=' '+hold[lang]
prepkeys=list(manual['part_preparation'][0]);manual['part_preparation']=[{k:p.get(k) for k in prepkeys+['manufacturing_class']} for p in parts]
manual['plywood_stock_policy']={'permitted_nominal_mm':[12,18],'actual_thickness_late_bound':True,'coupon_required':True,'explicit_solid_wood_ids':['SW01','SW02']}
manual['optional_accessories']={'family':'ACC01','in_minimum_bom':False,'qty':None,'selected_clamp_sku':None}
for stage in manual['stages']:
 for step in stage['steps']:
  for key in ['title','action','check','hold','tools','orientation','faces']:
   if isinstance(step.get(key),dict):step[key]={lang:re.sub(r'(\d)(mm|kg|°|states)\b',r'\1 \2',re.sub(r'(?<=[a-zÀ-ÿ])(?=\d)', ' ',text)) for lang,text in step[key].items()}
dump(str(O.relative_to(R))+'/assembly-manual.json',manual)
source=(R/'tools/build_structural_v335_metadata.py').read_text();source=source[source.index("fields=['instance_id'"):source.index("manifest={'version'")].replace('V33.5','V33.8')
source=source.replace("'CNC FACE_A · '+op.get('id','')", "(('REFERENCE ONLY / PURCHASE BEFORE CNC — final hardware interface unselected · ' if lang=='en' else 'SOMENTE REFERÊNCIA / COMPRAR ANTES DO CNC — interface final indefinida · ') if op.get('production_export_policy') or op.get('hardware_interface_status')=='PURCHASE_BEFORE_CNC' else 'CNC FACE_A · ')+op.get('id','')")
exec(compile(source,'V338 manual/BOM presentation','exec'),globals())
print('V338_METADATA_PASS',len(parts),'steps',sum(len(s['steps']) for s in manual['stages']))
