"""V33.6.3 bilingual front landing, adjustment and retention manual overlay.
CERN-OHL-S-2.0. Architecture gate and hardware freeze remain separate authorities.
"""
from pathlib import Path
import json,copy,csv
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/front-landings-v3363'
def read(p):return json.loads((R/p).read_text())
def dump(p,v):(R/p).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def bi(en,pt):return {'en':en,'pt-BR':pt}
def fmt(x):
 if x is None:return 'HOLD'
 if isinstance(x,(int,float)):return f'{x:.3f}'.rstrip('0').rstrip('.') or '0'
 if isinstance(x,list):return ' / '.join(fmt(v) for v in x)
 return str(x)
C=read('config/front_landings_v3363.json');reg=read('exports/generated/front-landings-v3363/manufacturing-register.json');parts=reg['parts'];by={p['instance_id']:p for p in parts};cat=read('config/hardware_catalog_v3363.json')
S=read('exports/generated/front-landings-v3363/support-validation.json');passed=bool(S['architecture_pass'])
manual=read('exports/generated/button-relief-v3361/assembly-manual.json');prev=read('exports/generated/playfield-rest-v3362/assembly-manual.json');prevsteps={t['id']:t for s in prev['stages'] for t in s['steps']};steps={t['id']:t for s in manual['stages'] for t in s['steps']}
manual.update(version='V33.6.3',source_head=C['head_before'],source_geometry_unchanged=False,geometry_authority='config/front_landings_v3363.json',current_manufacturing_register='exports/generated/front-landings-v3363/manufacturing-register.json',closed_position_support_valid=passed,closed_position_support_status='PASS' if passed else 'CLOSED_POSITION_SUPPORT_BLOCKED')
oldids={p['instance_id'] for p in read('exports/generated/playfield-rest-v3362/manufacturing-register.json')['parts']};newparts=[p for p in parts if p['instance_id'] not in oldids];newh=[h for h in cat['hardware'] if h['id'] not in {x['id'] for x in read('config/hardware_catalog_v335.json')['hardware']}]
woodids=[p['instance_id'] for p in newparts];hids=[h['id'] for h in newh]
# Keep the accepted52mm trim language but remove only its old missing-support sentence.
steps['06.1']['action']=copy.deepcopy(prevsteps['06.1']['action'])
for lang,sentence in [('en','This clearance edit does not add front support.'),('pt-BR','Esta alteração de folga não cria apoio frontal.')]:steps['06.1']['action'][lang]=steps['06.1']['action'][lang].replace(sentence,'').strip()
physical=bi('PHYSICAL QUALIFICATION STILL REQUIRED: selected adjusters, inserts, retention parts, mounting screws, actual plywood/display mass, coupon and load/rattle tests. Reference hardware geometry does not release purchased-hole dimensions or CNC. Do not work below an unsupported raised playfield.',
'VALIDAÇÃO FÍSICA AINDA NECESSÁRIA: reguladores, insertos, retenção, parafusos de montagem, compensado real/massa do monitor, cupom e ensaios de carga/vibração. Geometria de referência não libera dimensões das ferragens compradas nem CNC. Não trabalhe sob o playfield levantado sem apoio.')
blocked=bi('CLOSED_POSITION_SUPPORT_BLOCKED: the complete architecture gate has not passed. Do not use the CAD PLAY pose as proof of support.','CLOSED_POSITION_SUPPORT_BLOCKED: a arquitetura completa não passou. Não use a posição PLAY do CAD como prova de apoio.')
manual['engineering_blockers']=[] if passed else [{'id':'CLOSED_POSITION_SUPPORT_BLOCKED','status':'OPEN','description':blocked}]
manual['closed_support_authority']='exports/generated/front-landings-v3363/support-validation.json'
for sid in ['00.1','05.1','06.1','06.2','17.1','17.2']:
 t=steps[sid];t['hold']={lang:(physical[lang] if passed else blocked[lang]+' '+physical[lang]) for lang in physical};t.setdefault('validation',{})['closed_position_support']='ARCHITECTURE_PASS_PHYSICAL_QUALIFICATION_HOLD' if passed else 'BLOCKED'
# This replaces ambiguous seating instructions with the full rear/front load path.
steps['06.2']['title']=bi('Seat rear dowel and lower onto the front landings','Assente a cavilha traseira e abaixe nos apoios frontais')
steps['06.2']['component_ids']=list(dict.fromkeys(steps['06.2']['component_ids']+woodids));steps['06.2']['hardware_ids']=list(dict.fromkeys(steps['06.2']['hardware_ids']+hids))
steps['06.2']['action']=bi('Remove the main playfield glass and matrix. Release both captive closed-position retainers to their documented parked limits; keep the front support bodies installed. Support the module while seating both ends of the Ø32 dowel in the rear open cradles, then lower the front onto the two resilient adjuster contacts. Rear dowel/cradles define the rear support axis; the front landings carry the front load into the structural side walls. T1/T2/T3 remain cabinet structural crossmembers, intentionally clear by about22 mm normal to the base; none is a playfield landing. Keep the clean52 mm front inset,87 mm length,R8 transitions and396 mm front width.',
'Remova o vidro principal e a matriz. Solte as duas retenções cativas da posição fechada até os limites de estacionamento documentados; mantenha os corpos dos apoios frontais instalados. Sustente o módulo ao assentar as duas pontas da cavilha Ø32 nos berços traseiros e depois abaixe a frente sobre os dois contatos resilientes reguláveis. Cavilha/berços definem o eixo de apoio traseiro; os apoios frontais levam a carga às laterais estruturais. T1/T2/T3 são travessas estruturais do gabinete, com folga intencional de aproximadamente22 mm normal à base; nenhuma é apoio do playfield. Mantenha recuos frontais52 mm, comprimento87 mm, transiçõesR8 e largura frontal396 mm.')
steps['06.2']['check']=bi('REAR SEATING / FRONT CONTACT CHECK: both dowel ends fully seated; both front contacts loaded without rocking. No weight on glass, lockdown, buttons, electronics, cable or T1/T2/T3. Keep the module externally supported until the selected hardware/wood is qualified.',
'VERIFICAÇÃO DO APOIO TRASEIRO / CONTATO FRONTAL: ambas as pontas da cavilha assentadas; ambos os contatos frontais carregados, sem balanço. Nenhuma carga no vidro, lockdown, botões, eletrônica, cabo ou T1/T2/T3. Sustente externamente até qualificar ferragens/madeira.')
steps['06.2']['next_state']='SUPPORT LOAD PATH'
setup=bi(f"CURRENT setup: pad centers X{C['landing']['pad_left_x_mm']} / X{600-C['landing']['pad_left_x_mm']}, Y{C['search']['selected_pad_y_mm']} mm; retention axes are{C['retention']['axis_rearward_of_pad_mm']} mm rearward. Each body is{C['landing']['laminations']} × nominal18 mm plywood. M8 adjustment is±{C['landing']['selected_adjustment_plus_minus_mm']} mm of stack/tolerance compensation to reproduce the unchanged9.906669° PLAY pose, including the{C['landing']['pad_thickness_mm']} mm contact tip. Retention release travel is{C['retention']['release_drop_mm']} mm after unscrewing. These are reference packaging values, not purchased machining dimensions.", f"Ajuste CURRENT: centros das pontas X{C['landing']['pad_left_x_mm']} / X{600-C['landing']['pad_left_x_mm']}, Y{C['search']['selected_pad_y_mm']} mm; eixos de retenção{C['retention']['axis_rearward_of_pad_mm']} mm atrás. Cada corpo tem{C['landing']['laminations']} ×18 mm nominais. Curso M8±{C['landing']['selected_adjustment_plus_minus_mm']} mm de compensação de tolerâncias para reproduzir a posição PLAY inalterada de9,906669°, incluindo ponta de{C['landing']['pad_thickness_mm']} mm. Retenção recua{C['retention']['release_drop_mm']} mm após desrosquear. São valores de referência de ocupação, não dimensões de usinagem compradas.")
for lang in setup:steps['06.2']['action'][lang]+=' '+setup[lang]
steps['06.2']['tools']=bi('Compact spanner for the selected M6 hex-head retention bolt (reference10 mm across flats); exact tool size/access follow purchased hardware. Adjustment spanner and locknut tool also depend on the selected M8 family.', 'Chave compacta para o parafuso de retenção M6 sextavado (referência10 mm entre faces); tamanho/acesso finais dependem da ferragem comprada. Chaves do regulador e contraporca também dependem da família M8 selecionada.')
def newstep(template,id,title,action,check):
 t=copy.deepcopy(template);t.update(id=id,title=title,status='PROVISIONAL_HARDWARE',component_ids=woodids,hardware_ids=hids,action=action,check=check,hold={lang:physical[lang] if passed else blocked[lang]+' '+physical[lang] for lang in physical},next_state='PLAYFIELD LANDINGS',animation_id='assembly-'+id,checkpoint=True)
 t['validation']={'physical_trajectory_validated':False,'animation_class':'SCHEMATIC_ASSEMBLY_ANIMATION','closed_position_support':'ARCHITECTURE_PASS_PHYSICAL_QUALIFICATION_HOLD' if passed else 'BLOCKED','authority':'exports/generated/front-landings-v3363/support-validation.json'};return t
install=newstep(steps['05.1'],'05.2',bi('Install the front landing bodies and adjuster stacks','Instale os corpos dos apoios e os conjuntos reguladores'),bi('Identify the actual manufacturing members and handed placement from their FACE A cards. Assemble the front landing bodies at the CURRENT side-wall datums after the button/service zone. Glue the three laminations together and secure them with the two specified lamination screws. Mount each finished body with four positive side screws; do not glue the body to the wall or rely on wall friction. Fit metal threaded receivers, adjusters, locknuts and replaceable contact tips. The M025 blind metal-receiver bores are PURCHASE_BEFORE_CNC / hardware-dependent manual finish, not supplied holes; use a qualified rigid angle drill guide matching the9.906669° difference from the board normal and a depth stop. Qualify the actual bore, drill-point allowance and intact top skin on a coupon; the11.3 mm reference depth is a packaging limit, not a drilling instruction. Never thread a repeated structural retainer directly into plywood. Include the contact-pad thickness in the nominal stack. Keep the assembly replaceable and use no added shims or T1 shoes.',
'Identifique peças reais e orientação pelas fichas FACE A. Monte os apoios frontais nas referências CURRENT das laterais, após a zona de botões/serviço. Cole as três lâminas entre si e fixe-as com os dois parafusos de laminação especificados. Monte cada corpo pronto com quatro parafusos positivos na lateral; não cole o corpo na parede nem dependa de atrito. Instale receptores metálicos roscados, reguladores, contraporcas e pontas substituíveis. Os furos cegos dos receptores metálicos em M025 são PURCHASE_BEFORE_CNC / acabamento manual dependente da ferragem, não furos já fornecidos; use uma guia rígida qualificada para o ângulo de9,906669° em relação à normal da placa e limitador de profundidade. Qualifique furo real, ponta da broca e pele superior intacta em cupom;11,3 mm de referência é limite de ocupação, não instrução de furação. Nunca rosqueie retenção estrutural repetitiva diretamente no compensado. Inclua a espessura da ponta na altura nominal. Preserve substituição e não acrescente calços nem sapatas em T1.'),bi('Verify full body-to-side bearing, screw/receiver engagement, no exterior breakthrough, retained button/wire/tool access, and clearance to plunger, S1, legs and front service. Exact purchased dimensions remain HOLD.',
'Verifique apoio integral na lateral, engate de parafusos/receptores, ausência de perfuração externa, acesso a botões/fios/ferramentas e folgas ao plunger, S1, pernas e serviço frontal. Dimensões compradas continuam PENDENTES.'))
level=newstep(steps['06.2'],'06.3',bi('Reproduce the approved PLAY pose and engage retention','Reproduza a posição PLAY aprovada e engate a retenção'),bi('Leave both retainers released while adjusting. Start both front adjusters at the nominal CAD height. With the rear dowel fully seated, adjust left and right for equal transverse height while retaining the CURRENT fore/aft slope of9.906669°. The±3 mm travel compensates hardware/material tolerances only; it does not authorize a new playing height, slope or left/right twist. The complete−3 mm lowered pose collides with button envelopes and is forbidden. Include both contact tips and reproduce the exact nominal pose. Lock both adjuster locknuts, then reset each captive bolt stop for7 mm reference engagement, within the qualified6–8 mm purchased-hardware limits. Open the coin door to the validated110° service pose. Reach the two retention heads through that front service aperture with the compact spanner; no electronics removal is required. Use the spanner to engage the two captive M6-family hex bolts into the metal-backed receivers without lifting the base from its pads. Retainers resist uplift/rattle; they do not replace the landing load path. Check glass/lockdown clearance. For opening, remove main glass/matrix, support the module, release and park both retainers, then rotate to50°. Routine opening does not remove landing bodies. For complete removal, retainers stay released and the whole module lifts48 mm clear of the rear cradles.',
'Mantenha ambas as retenções soltas durante o ajuste. Inicie os reguladores na altura nominal do CAD. Com a cavilha traseira assentada, ajuste esquerda/direita para a mesma altura transversal e mantenha a inclinação longitudinal CURRENT de9,906669°. O curso±3 mm compensa apenas tolerâncias de ferragens/material; não autoriza nova altura, inclinação ou torção transversal. A posição inteira rebaixada−3 mm colide com os envelopes dos botões e é proibida. Inclua ambas as pontas e reproduza a posição nominal exata. Trave as contraporcas e reajuste cada batente de retenção para engate de referência7 mm, dentro dos limites6–8 mm qualificados na ferragem comprada. Abra a porta frontal de moedas na posição de serviço validada de110°. Alcance as duas cabeças de retenção por essa abertura com a chave compacta; não é necessário remover eletrônica. Use a chave para engatar os dois parafusos sextavados cativos da família M6 nos receptores metálicos sem retirar a base dos apoios. As retenções resistem à elevação/vibração e não substituem o apoio vertical. Confira folgas do vidro/lockdown. Para abrir, remova vidro principal/matriz, sustente o módulo, solte/estacione as duas retenções e gire até50°. Abertura normal não remove os apoios. Para retirada completa, deixe as retenções soltas e eleve o módulo48 mm para liberar os berços.'),bi('LEVEL / RETENTION CHECK: left–right level, intended fore/aft slope, both locknuts secured, both retainers positively engaged, no rocking. Then test release, clean early pad separation,50° service and48 mm lift under controlled handling. No uncontrolled drop and no pivot-friction assumption.',
'VERIFICAÇÃO DE NÍVEL / RETENÇÃO: nível transversal, inclinação longitudinal correta, contraporcas travadas, retenções engatadas e ausência de balanço. Teste soltura, separação inicial limpa, serviço50° e retirada48 mm com manuseio controlado. Não permita queda nem suponha retenção por atrito do pivô.'))
for st in manual['stages']:
 if st['id']=='05':st['steps'].append(install);st['pieces']+=woodids;st['hardware']=list(dict.fromkeys(st['hardware']+hids))
 if st['id']=='06':st['steps'].append(level);st['hardware']=list(dict.fromkeys(st['hardware']+hids))
prepkeys=list(manual['part_preparation'][0]);manual['part_preparation']=[{k:p.get(k) for k in prepkeys} for p in parts]
dump('exports/generated/front-landings-v3363/assembly-manual.json',manual)
source=(R/'tools/build_structural_v335_metadata.py').read_text();source=source[source.index("fields=['instance_id'"):source.index("manifest={'version'")].replace('V33.5','V33.6.3')
source=source.replace("'CNC FACE_A · '+op.get('id','')", "(('REFERENCE ONLY / PURCHASE BEFORE CNC — final bore/recess unselected · ' if lang=='en' else 'SOMENTE REFERÊNCIA / COMPRAR ANTES DO CNC — furo/rebaixo finais indefinidos · ') if op.get('production_export_policy') or op.get('hardware_interface_status')=='PURCHASE_BEFORE_CNC' else 'CNC FACE_A · ')+op.get('id','')")
exec(compile(source,'V3363 manual/BOM presentation','exec'),globals())
manifest={'version':'V33.6.3','head_before':C['head_before'],'current_register':'exports/generated/front-landings-v3363/manufacturing-register.json','current_BOM':'exports/generated/front-landings-v3363/manufacturing-bom.csv','CNC_filter':'manufacturing_class != SHOP_MADE_SOLID_WOOD_PART','shop_family':'SW01','installed_material_map':'config/wood_materials_v3363.json','release':False,'hardware_catalog':'config/hardware_catalog_v3363.json','button_positional_authority':'config/button_relief_v3361.json','button_final_bore_mm':None,'button_final_recess_mm':None,'closed_position_support':'PASS' if passed else 'CLOSED_POSITION_SUPPORT_BLOCKED'}
dump('config/manufacturing/flatpack_v3363.json',manifest)
print('V3363_METADATA_PASS',len(parts),'support architecture',passed)
