"""V33.7 bilingual two-stock and generic user-module manual. CERN-OHL-S-2.0."""
from pathlib import Path
import json,copy,csv,re
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/two-stock-user-module-v337'
def read(p):return json.loads((R/p).read_text())
def dump(p,v):(R/p).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def bi(en,pt):return {'en':en,'pt-BR':pt}
def fmt(x):
 if x is None:return 'HOLD'
 if isinstance(x,(int,float)):return f'{x:.3f}'.rstrip('0').rstrip('.') or '0'
 if isinstance(x,list):return ' / '.join(fmt(v) for v in x)
 return str(x)
C=read('config/underfront_user_module_v337.json');reg=read('exports/generated/two-stock-user-module-v337/manufacturing-register.json');parts=reg['parts'];by={p['instance_id']:p for p in parts};cat=read('config/hardware_catalog_v337.json');manual=read('exports/generated/front-landings-v3363/assembly-manual.json');oldparts=read('exports/generated/front-landings-v3363/manufacturing-register.json')['parts'];oldh={h['id'] for h in read('config/hardware_catalog_v3363.json')['hardware']};newh=[h for h in cat['hardware'] if h['id'] not in oldh]
manual.update(version='V33.7',source_head=C['head_before'],source_geometry_unchanged=False,prior_unrelated_geometry_unchanged=True,geometry_authority='config/underfront_user_module_v337.json',current_manufacturing_register='exports/generated/two-stock-user-module-v337/manufacturing-register.json')
moduleparts=[p for p in parts if p['source_component'].startswith('Underfront')];moduleids=[p['instance_id'] for p in moduleparts];hids=[h['id'] for h in newh]
steps={t['id']:t for s in manual['stages'] for t in s['steps']}
stock_note=bi('CURRENT plywood purchasing uses only nominal12 mm and18 mm stock. Measure each actual production lot and qualify the fit coupon before release. Finished local webs can be thinner after a documented FACE_A pocket/reduction; this does not create a6/8 mm purchase family. The backglass bezel deliberately retains its6 mm finished web by one-face reduction from12 mm stock because the glass/display gap is protected. SW01 solid leg blocks remain a separate solid-wood material, not a plywood stock exception.',
'A compra de compensado CURRENT usa somente chapas nominais12 mm e18 mm. Meça cada lote real e valide o cupom de encaixe antes da liberação. Trechos acabados podem ser mais finos após bolso/redução documentado pela FACE_A; isso não cria família de compra6/8 mm. A moldura do backglass mantém deliberadamente alma acabada6 mm por redução de uma face da chapa12 mm, preservando a folga vidro/monitor. Blocos de perna SW01 continuam em madeira maciça separada, não são exceção de chapa.')
for lang in stock_note:steps['00.1']['action'][lang]+=' '+stock_note[lang]
manual['hardware_interface_review']=copy.deepcopy(cat.get('v337_interface_review',[]))
stackhold=bi('V33.7 stack re-selection HOLD: F21 blank-station stack gains6 mm; F22 intake frame/baffle stack changes. Measure the selected hardware stack before assigning final lengths; no quantity or length is guessed. F12 main intake-filter interface is retained by4 mm underside counter-recesses in12 mm stock.',
'PENDÊNCIA de revisão das pilhas V33.7: F21 na estação cega ganha6 mm; a pilha F22 da moldura/defletor de entrada muda. Meça a montagem das ferragens selecionadas antes de fixar comprimentos; nenhuma quantidade ou medida é adivinhada. A interface F12 do filtro principal é preservada por rebaixos inferiores4 mm na chapa12 mm.')
for lang in stackhold:steps['11.1']['hold'][lang]+=' '+stackhold[lang]


# Supersede only the active fixed-function schematic paragraph. Historical V08 stays intact.
steps['18.1']['action']=bi('The underfront user module is a removable generic plate in the fixed front bay. The owner configuration may use five programmable buttons plus a dual USB module; four plus USB and a button-only configuration share the same bay. Functions are assigned by the builder; the permanent wood imposes no volume, operating-mode or pairing function. Button bores and USB cutout remain unselected and hardware-dependent. The conventional front-right plunger remains a separate provisional interface at X520/Z280. Displays, controllers, power interfaces and electronics remain optional, with generic carriers and service passage.',
'O módulo do usuário sob a frente é uma placa genérica removível no alojamento frontal fixo. A configuração do proprietário pode usar cinco botões programáveis e um módulo USB duplo; quatro mais USB e uma configuração só de botões usam o mesmo alojamento. O construtor atribui funções; a madeira permanente não impõe volume, modo de operação ou pareamento. Furos de botões e recorte USB continuam indefinidos e dependem das ferragens. O plunger frontal direito permanece interface provisória separada em X520/Z280. Monitores, controladoras, interfaces elétricas e eletrônica são opcionais, com suportes genéricos e passagem de serviço.')
steps['18.1']['check']=bi('USER CONFIGURATION CHECK: no final machining from schematic centers; buy and measure the actual controls first. Route a flexible service loop without selecting a connector family. Confirm reach, accidental-operation protection, rear body/nut space and removal with the chosen parts. USB thread compatibility through12 mm is unverified; any one-face rear pocket waits for physical dimensions and coupon. Keep at least the planned70 mm rear USB reserve.',
'VERIFICAÇÃO DA CONFIGURAÇÃO DO USUÁRIO: não usine a partir de centros esquemáticos; compre e meça os controles reais primeiro. Reserve laço flexível de serviço sem impor conectores. Confira alcance, proteção contra acionamento acidental, espaço traseiro de corpos/porcas e retirada com as peças escolhidas. Compatibilidade da rosca USB com12 mm não está verificada; eventual bolso traseiro por uma face aguarda medição física e cupom. Preserve a reserva USB traseira planejada de pelo menos70 mm.')
steps['18.1']['hold']=bi('HARDWARE_PENDING / PURCHASE BEFORE CNC: BUTTON_BORE_MM=null; USB_CUTOUT=null. Seller references are conflicting packaging evidence, not selected dimensions. The old fixed-function220×55 schematic is historical only.',
'HARDWARE_PENDING / COMPRAR ANTES DO CNC: BUTTON_BORE_MM=null; USB_CUTOUT=null. Referências conflitantes do vendedor são evidências de ocupação, não dimensões selecionadas. O antigo esquema220×55 com funções fixas é somente histórico.')
steps['18.1']['next_state']='UNDERFRONT USER MODULE';steps['18.1']['component_ids']=list(dict.fromkeys(steps['18.1']['component_ids']+moduleids));steps['18.1']['hardware_ids']=list(dict.fromkeys(steps['18.1']['hardware_ids']+hids))
module=copy.deepcopy(steps['07.1']);module.update(id='07.3',title=bi('Install the removable underfront user module','Instale o módulo removível do usuário sob a frente'),status='PROVISIONAL_HARDWARE',component_ids=moduleids,hardware_ids=hids,animation_id='assembly-07.3',next_state='UNDERFRONT USER MODULE',checkpoint=True)
module['action']=bi('Identify the existing structural18 mm FLOOR with its scoped underside bay and the removable12 mm plate from their FACE A cards. The bay is one-face machining in the existing floor, not a separate wooden box; preserve its authoritative underside-front datums. Retain the plate with the four positive machine-fastener/captive-insert interfaces, accessible from below. Fit a blank plate for the basic mechanical cabinet, or a replaceable user adapter after controls are selected. Alternative button/USB layouts use this same bay and are mutually exclusive. Keep a flexible harness/service-loop corridor and the rear component reserve; the electrical connector remains builder-configurable. Do not cut schematic button or USB holes into permanent wood.',
'Identifique o FLOOR estrutural existente18 mm com alojamento inferior localizado e a placa removível12 mm pelas fichas FACE A. O alojamento é usinado por uma face no fundo existente, não uma caixa de madeira separada; preserve suas referências oficiais sob a frente. Fixe a placa nas quatro interfaces positivas de parafuso de máquina/inserto cativo acessíveis por baixo. Use placa cega no gabinete mecânico básico ou adaptador substituível após selecionar controles. Arranjos alternativos de botões/USB usam o mesmo alojamento e são mutuamente exclusivos. Mantenha corredor de chicote/laço de serviço flexível e reserva traseira dos componentes; o conector elétrico é escolha do construtor. Não corte furos esquemáticos de botão/USB na madeira permanente.')
floorfamily=next(p['manufacturing_part_id'] for p in parts if p['source_component']=='FLOOR')
for lang in module['action']:module['action'][lang]=module['action'][lang].replace('FLOOR',f'FLOOR / {floorfamily}')
module['check']=bi('MODULE RETENTION / SERVICE CHECK: all four attachments positively secure the plate; no loose hardware can drop inside. Confirm underside tool access, selected control reach and clearance to front structure, coin door, plunger, legs, playfield and landing hardware. Support the plate during removal; release its four attachments and follow the documented path. Cable flex/connector disconnection is hardware-dependent, not a validated electrical instruction.',
'VERIFICAÇÃO DE RETENÇÃO / SERVIÇO: as quatro fixações seguram positivamente a placa; não deixe ferragens soltas caírem. Confira acesso inferior da ferramenta, alcance dos controles e folgas à frente, porta de moedas, plunger, pernas, playfield e seus apoios. Sustente a placa na retirada; solte as quatro fixações e siga o trajeto documentado. Flexão/desconexão de cabo depende das ferragens; não é instrução elétrica validada.')
module['hold']=copy.deepcopy(steps['18.1']['hold']);module['tools']=bi('Driver/hex tool for selected four machine fasteners; exact size pending purchase. Qualified locator/depth-stop tools for held inserts where specified.','Chave adequada aos quatro parafusos de máquina selecionados; medida após compra. Ferramentas de localização/limitador qualificadas para insertos pendentes quando especificado.')
module['validation']={'physical_trajectory_validated':False,'animation_class':'SCHEMATIC_ASSEMBLY_ANIMATION','authority':'config/underfront_user_module_v337.json','manufacturing_release':False}
for stage in manual['stages']:
 if stage['id']=='07':stage['steps'].append(module);stage['pieces']+=moduleids;stage['hardware']=list(dict.fromkeys(stage['hardware']+hids))
# Current piece cards, including exact one-face converted members and held operations.
prepkeys=list(manual['part_preparation'][0]);manual['part_preparation']=[{k:p.get(k) for k in prepkeys} for p in parts]
manual['plywood_stock_policy']={'permitted_nominal_mm':[12,18],'actual_thickness_late_bound':True,'coupon_required':True,'solid_wood_SW01_separate':True}
def prose(t):
 t=re.sub(r'([A-Za-zÀ-ÿ]{2,})(\d)',r'\1 \2',t);t=re.sub(r'(\d)(mm|kg|deg|buttons|botões)\b',r'\1 \2',t);return t.replace(' +dual',' + dual').replace('—5','— 5').replace('—6','— 6')
for stage in manual['stages']:
 for step in stage['steps']:
  for key in ['title','action','check','hold','tools','orientation']:
   if isinstance(step.get(key),dict):step[key]={lang:prose(text) for lang,text in step[key].items()}
dump('exports/generated/two-stock-user-module-v337/assembly-manual.json',manual)
source=(R/'tools/build_structural_v335_metadata.py').read_text();source=source[source.index("fields=['instance_id'"):source.index("manifest={'version'")].replace('V33.5','V33.7')
source=source.replace("'CNC FACE_A · '+op.get('id','')", "(('REFERENCE ONLY / PURCHASE BEFORE CNC — final hardware interface unselected · ' if lang=='en' else 'SOMENTE REFERÊNCIA / COMPRAR ANTES DO CNC — interface final indefinida · ') if op.get('production_export_policy') or op.get('hardware_interface_status')=='PURCHASE_BEFORE_CNC' else 'CNC FACE_A · ')+op.get('id','')")
exec(compile(source,'V337 manual/BOM presentation','exec'),globals())
print('V337_METADATA_PASS',len(parts),'steps',sum(len(s['steps']) for s in manual['stages']))
