/** V34 offline native/manual/retirement/browser regression. CERN-OHL-S-2.0. */
import {createRequire} from 'node:module';const {chromium}=createRequire(import.meta.url)('playwright');import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const R=process.cwd(),O=path.join(R,'exports/generated/backbox-v34'),checks=[],errors=[],network=[];
const J=n=>JSON.parse(fs.readFileSync(path.join(O,n),'utf8')),reg=J('manufacturing-register.json'),g=J('geometry-validation.json'),manual=J('assembly-manual.json');
const check=(v,n,d)=>{checks.push({name:n,pass:!!v,detail:d});if(!v)throw Error(n+' '+JSON.stringify(d));};
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
async function ready(ctx){const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))network.push(r.url());});await p.goto('file://'+path.join(R,'exports/generated/viewer-v32/index.html'));await p.waitForFunction(()=>document.body.dataset.modularityReady==='true',null,{timeout:90000});return p;}
try{
 const ctx=await browser.newContext({viewport:{width:1600,height:1050},offline:true}),p=await ready(ctx);
 check(await p.evaluate(()=>viewer.data.geometry_revision==='V34'),'V34 revision');check(await p.evaluate(()=>viewer.data.groups.length===22),'22 visibility groups');
 check(await p.evaluate(ns=>ns.every(n=>!viewer.installed.some(m=>m.name===n)),g.retired),'all retired installed objects absent');
 check(await p.evaluate(()=>viewer.installed.some(m=>m.name==='BB_MONITOR_PLATE')),'captured plate present');
 await p.evaluate(()=>{viewer.applyState('EXPLODED DETAILED');document.getElementById('scope').value='BACKBOX';viewer.refresh();});
 check(await p.evaluate(ids=>ids.every(id=>viewer.detail.some(m=>m.name===id)),reg.parts.map(a=>a.instance_id)),'76 actual manufacturing pieces');await p.screenshot({path:path.join(O,'viewer-01-exploded.png')});
 const steps=manual.stages.flatMap(s=>s.steps);check(await p.evaluate(ids=>ids.every(id=>animation333.data.clips.some(c=>c.id==='assembly-'+id)),steps.map(s=>s.id)),'all manual steps animated');
 check(await p.evaluate(()=>new Set(animation333.data.clips.map(c=>c.id)).size===animation333.data.clips.length),'unique animation IDs');
 for(const st of steps.filter(s=>s.id.startsWith('08.'))){await p.evaluate(id=>{animation333.start('assembly-'+id);animation333.seek(1);},st.id);check(await p.evaluate(()=>viewer.detail.some(m=>m.visible)),'assembly '+st.id+' visible');}
 for(const id of ['service-glass','service-display','service-cassette','service-fold']){await p.evaluate(id=>{animation333.start(id);animation333.seek(1);},id);check(await p.evaluate(()=>viewer.installed.some(m=>m.visible)),id+' visible');if(id==='service-display'){check(await p.evaluate(()=>viewer.installed.find(m=>m.name==='BB_MONITOR_PLATE').position.length()<1e-8),'plate remains fixed during monitor service');check(await p.evaluate(()=>viewer.installed.find(m=>m.name==='BB_Top').position.length()<1e-8),'top remains fixed during monitor service');}await p.screenshot({path:path.join(O,'viewer-'+id+'.png')});}
 await p.evaluate(()=>{viewer.applyState('PLAY');viewer.choose('BB_MONITOR_PLATE',false);});check(await p.locator('#selection').textContent().then(s=>s.includes('M074')&&s.includes('CAPTURED')),'M074 metadata captured and canonical');await p.screenshot({path:path.join(O,'viewer-02-metadata.png')});
 await p.evaluate(()=>{animation333.start('pack');animation333.seek(1);});check(await p.evaluate(n=>animation333.packingMeshes.length===n,reg.parts.length),'packing current 76 pieces');
 await ctx.close();const tc=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true,offline:true}),t=await ready(tc);await t.locator('#lang-pt').tap();await t.locator('#palette').selectOption('accessible');await t.evaluate(()=>{animation333.start('service-glass');animation333.seek(0);});await t.locator('#anim-play').tap();await t.waitForFunction(()=>animation333.progress>0,null,{timeout:10000});await t.locator('#anim-pause').tap();const progress=await t.evaluate(()=>animation333.progress);await t.waitForTimeout(150);check(await t.evaluate(()=>animation333.progress)===progress,'tablet play/pause');check(await t.locator('#animation-status').textContent().then(s=>s.includes('FRENTE')||s.includes('frente')),'PT-BR front glass service');check(await t.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'tablet no overflow');check(await t.locator('#anim-play').evaluate(e=>e.getBoundingClientRect().height>=44),'44px playback target');await t.screenshot({path:path.join(O,'viewer-03-tablet.png')});await tc.close();
 check(!errors.length,'no JavaScript errors',errors);check(!network.length,'offline zero network requests',network);
 const sha=crypto.createHash('sha256').update(fs.readFileSync(path.join(R,'exports/generated/viewer-v32/index.html'))).digest('hex');fs.writeFileSync(path.join(O,'browser-validation.json'),JSON.stringify({pass:true,checks,errors,network,viewer_sha256:sha,tablet:'EMULATED_TOUCH_PASS; physical tablet FPS not certified'},null,2)+'\n');console.log('V34_BROWSER_PASS',checks.length);
}finally{await browser.close();}
