/** V35 offline candidate viewer QA. CERN-OHL-S-2.0. */
import {createRequire} from 'node:module';const {chromium}=createRequire(import.meta.url)('playwright');import fs from 'node:fs';import path from 'node:path';
const O=path.join(process.cwd(),'exports/generated/widebody-v35'),checks=[],errors=[],network=[];const ck=(p,n)=>{checks.push({name:n,pass:!!p});if(!p)throw Error(n)};
const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{for(const tablet of [false,true]){const c=await b.newContext({viewport:tablet?{width:834,height:1194}:{width:1600,height:1050},hasTouch:tablet,offline:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))network.push(r.url())});await p.goto('file://'+O+'/viewer.html');await p.waitForFunction(()=>document.body.dataset.modularityReady==='true',null,{timeout:90000});
ck(await p.evaluate(()=>viewer.data.geometry_revision==='V35'),'V35 revision');ck(await p.evaluate(()=>viewer.detail.filter(m=>m.userData?.meta?.kind==='wood').length===66||viewer.data.detail.filter(m=>m.meta.kind==='wood').length===66),'66 flat pieces');
for(const s of ['PLAY','SERVICE','LIFT-OUT','BACKBOX FOLD','EXPLODED DETAILED']){await p.evaluate(s=>viewer.applyState(s),s);ck(await p.evaluate(()=>viewer.installed.some(m=>m.visible)||viewer.detail.some(m=>m.visible)),'visible '+s)}
await p.evaluate(()=>viewer.applyState('PLAY'));await p.locator('#gap-led').click();ck(await p.evaluate(()=>viewer.installed.filter(m=>m.name.startsWith('OptionalLEDEnvelope')&&m.visible).length===2),'optional LED envelopes');await p.locator('#gap-black').click();ck(await p.evaluate(()=>viewer.installed.filter(m=>m.name.startsWith('OptionalLEDEnvelope')&&m.visible).length===0),'black gap');
if(tablet){await p.locator('#lang-pt').tap();await p.locator('#palette').selectOption('accessible');ck(await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'tablet no overflow');ck(await p.locator('#gap-led').evaluate(e=>e.getBoundingClientRect().height>=44),'touch target44');}
await p.screenshot({path:O+'/viewer-'+(tablet?'tablet':'desktop')+'.png'});await c.close()}
ck(!errors.length,'zero JavaScript errors');ck(!network.length,'offline zero network');}catch(e){errors.push(String(e))}finally{await b.close();fs.writeFileSync(O+'/browser-validation.json',JSON.stringify({pass:checks.every(c=>c.pass)&&!errors.length,checks,errors,network},null,2));console.log(checks,errors)}
