/** Focused offline V33.6.2 changed-geometry and explicit-support-HOLD regression.
 * Existing controls/49-clip suite inherited from unchanged V33.6.1; not rerun.
 * CERN-OHL-S-2.0. */
import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const R=process.cwd(),O=path.join(R,'exports/generated/playfield-rest-v3362'),checks=[],errors=[],net=[],views=[];
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const check=(ok,name,details)=>{checks.push({name,pass:!!ok,details});if(!ok)throw Error(name+' '+JSON.stringify(details));};
const launch=()=>chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let browser=await launch();
async function ready(ctx){const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))net.push(r.url());});await p.goto('file://'+path.join(R,'exports/generated/viewer-v32/index.html'));await p.waitForFunction(()=>document.body.dataset.animationReady==='true',null,{timeout:90000});return p;}
try{
const ctx=await browser.newContext({viewport:{width:1600,height:1050},offline:true}),p=await ready(ctx);
async function shot(n,title){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:path.join(O,n+'.png')});views.push({image:n+'.png',title});}
check(await p.locator('#state-note').textContent().then(s=>s.includes('CLOSED_POSITION_SUPPORT_BLOCKED')&&s.includes('no front landing')),'PLAY identifies missing front support');
check(await p.evaluate(()=>viewer.data.geometry_revision==='V33.6.2'),'current viewer revision');
check(await p.evaluate(()=>animation333.data.clips.length===49),'49 inherited clips retained; full suite not repeated');
const widths=await p.evaluate(()=>{
 const test=m=>{const a=m.geometry.attributes.position.array,alpha=9.906669253650632*Math.PI/180,rows=[];for(let i=0;i<a.length;i+=3){const y=(a[i+1]-45)*Math.cos(alpha)+(a[i+2]-341.7292430523254)*Math.sin(alpha);if(Math.abs(y-20)<.002)rows.push(a[i]);}return Math.max(...rows)-Math.min(...rows);};
 const installed=test(viewer.installed.find(m=>m.name==='PF_BasePlywood'));viewer.applyState('EXPLODED DETAILED');const detail=test(viewer.detail.find(m=>m.name==='P034-Main'));return {installed,detail};
});check(Math.abs(widths.installed-396)<.002&&Math.abs(widths.detail-396)<.002,'installed and real manufacturing mesh front width396',widths);
await p.evaluate(()=>viewer.choose('P034-Main',true));check(await p.locator('#selection').textContent().then(s=>s.includes('V3362')&&s.includes('CLOSED_POSITION_SUPPORT_BLOCKED')),'M025 current authority and unresolved support metadata');await shot('viewer-01-base-detail','Current52mm inset M025 — closed support unresolved');
check(await p.evaluate(()=>['primary','secondary'].every((kind,i)=>['L','R'].every(side=>{const m=viewer.installed.find(m=>m.name==='LeafButton_'+kind+'_'+side);m.geometry.computeBoundingBox();const c=m.geometry.boundingBox.getCenter(new THREE.Vector3());return Math.abs(c.y-[89,127][i])<.001&&Math.abs(c.z-[350.593661971831,357.2302816901408][i])<.001;}))),'owner button centers unchanged');
async function endpoint(id,state){return await p.evaluate(({id,state})=>{
 animation333.exit();viewer.applyState(state);const m=viewer.installed.find(m=>m.name==='PF_BasePlywood'),r=m.geometry.attributes.position.array.slice();animation333.start(id);animation333.seek(1);m.updateMatrix();const a=m.geometry.attributes.position.array;let max=0;
 for(let i=0;i<a.length;i+=3){const v=new THREE.Vector3(a[i],a[i+1],a[i+2]).applyMatrix4(m.matrix);let nearest=Infinity;for(let j=0;j<r.length;j+=3)nearest=Math.min(nearest,Math.hypot(v.x-r[j],v.y-r[j+1],v.z-r[j+2]));max=Math.max(max,nearest);}return max;
},{id,state});}
for(const [id,state] of [['service-pf-service','PLAYFIELD SERVICE 50°'],['service-pf-lift','PLAYFIELD LIFT-OUT']]){const max=await endpoint(id,state);check(max<.002,'current PF animation endpoint '+id,max);check(await p.locator('#state-note').textContent().then(s=>s.includes('CLOSED_POSITION_SUPPORT_BLOCKED')),'support blocker visible '+id);}
await shot('viewer-02-lift','Existing lift path — clearance only, support qualification blocked');
await p.evaluate(()=>{animation333.start('assembly-06.1');animation333.seek(.55);});check(await p.locator('#state-note').textContent().then(s=>s.includes('CLOSED_POSITION_SUPPORT_BLOCKED')&&s.includes('SCHEMATIC')),'schematic assembly and missing support both explicit');await shot('viewer-03-assembly','Actual revised M025 in schematic assembly');
await p.evaluate(()=>{animation333.start('pack');animation333.seek(1);});check(await p.evaluate(()=>animation333.packingMeshes.length===101&&animation333.packingMeshes.every(m=>m.visible)),'packing101 members retained');
check(await p.evaluate(()=>{const m=animation333.packingMeshes.find(m=>m.name==='P034-Main'||m.userData?.meta?.instance==='P034-Main'||m.userData?.pack?.instance_id==='P034-Main');return !animation333.data.pieces['P034-Main'].packing_mesh&&!!m;}),'packing uses current detailed M025 without stale override');await shot('viewer-04-pack','Packing of current101-piece kit; no rest parts invented');
await ctx.close();await browser.close();browser=await launch();const touchctx=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true,offline:true}),touch=await ready(touchctx);
check(await touch.locator('#state-note').textContent().then(s=>s.includes('CLOSED_POSITION_SUPPORT_BLOCKED')),'tablet default support blocker');await touch.evaluate(()=>animation333.start('service-pf-service'));await touch.locator('#anim-play').tap();await touch.waitForFunction(()=>animation333.progress>0,null,{timeout:10000});await touch.locator('#anim-pause').tap();const at=await touch.evaluate(()=>animation333.progress);await touch.waitForTimeout(150);check(await touch.evaluate(()=>animation333.progress)===at,'tablet PLAY/PAUSE works');
await touch.locator('#lang-pt').tap();await touch.locator('#palette').selectOption('accessible');await touch.waitForTimeout(150);check(await touch.locator('#state-note').textContent().then(s=>s.includes('CLOSED_POSITION_SUPPORT_BLOCKED')&&s.includes('apoio frontal')),'Portuguese support blocker');check(await touch.locator('#anim-play').textContent()==='REPRODUZIR','PT-BR playback label');check(await touch.evaluate(()=>[...document.querySelectorAll('#animation-bar button,#animation-bar select')].filter(e=>e.getClientRects().length).every(e=>e.getBoundingClientRect().height>=44)),'tablet44px playback targets');check(await touch.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'tablet no horizontal overflow');await touch.screenshot({path:path.join(O,'viewer-05-tablet.png')});views.push({image:'viewer-05-tablet.png',title:'Tablet PT-BR/Accessible and unresolved closed support'});await touchctx.close();
check(!errors.length,'no JavaScript errors',errors);check(!net.length,'offline no network',net);
const prior='exports/generated/button-relief-v3361/browser-validation.json';const inherited=JSON.parse(fs.readFileSync(path.join(R,prior),'utf8'));check(inherited.pass,'inherited broad V33.6.1 suite passed');
fs.writeFileSync(path.join(O,'browser-validation.json'),JSON.stringify({pass:true,scope:'Focused V33.6.2 changed PF geometry/metadata/notes/endpoints/packing plus desktop and emulated tablet; unchanged broader49clip/UI suite inherited.',checks,errors,network:net,tablet_playback:'PASS_EMULATED_TOUCH_PHYSICAL_FPS_NOT_CERTIFIED',inherited:{path:prior,sha256:sha(path.join(R,prior)),checks:inherited.checks.length},viewer_sha256:sha(path.join(R,'exports/generated/viewer-v32/index.html'))},null,2)+'\n');fs.writeFileSync(path.join(O,'review-views.json'),JSON.stringify(views,null,2)+'\n');console.log('V3362_BROWSER_PASS',checks.length);
}finally{await browser.close();}
