/** Focused offline landing/manual/retention animation QA. CERN-OHL-S-2.0. */
import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const R=process.cwd(),O=path.join(R,'exports/generated/front-landings-v3363'),checks=[],errors=[],net=[],views=[];
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const J=f=>JSON.parse(fs.readFileSync(path.join(O,f),'utf8'));const VM=J('viewer-motion.json'),reg=J('manufacturing-register.json'),gate=J('support-validation.json');
const check=(ok,name,details)=>{checks.push({name,pass:!!ok,details});if(!ok)throw Error(name+' '+JSON.stringify(details));};
const launch=()=>chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let browser=await launch();
async function ready(ctx){const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))net.push(r.url());});await p.goto('file://'+path.join(R,'exports/generated/viewer-v32/index.html'));await p.waitForFunction(()=>document.body.dataset.landingsReady==='true',null,{timeout:90000});return p;}
try{
check(gate.architecture_pass,'root complete architecture gate passed');check(VM.closing.validated,'combined closing trajectory validated');const ctx=await browser.newContext({viewport:{width:1600,height:1050},offline:true}),p=await ready(ctx);
async function shot(n,title){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:path.join(O,n+'.png')});views.push({image:n+'.png',title});}
check(await p.evaluate(()=>viewer.data.geometry_revision==='V33.6.3'),'current viewer revision');check(await p.locator('#state-note').textContent().then(s=>s.includes('Closed support architecture validated')&&s.includes('CNC release remain HOLD')),'PLAY separates architecture pass from physical/CNC hold');
check(await p.evaluate(()=>viewer.data.groups.some(g=>g.id==='landings'&&g.names.en==='PLAYFIELD LANDINGS')),'dedicated landing visibility group');
await p.evaluate(()=>{document.getElementById('landings-panel').open=true;landings3363.isolate();});check(await p.evaluate(()=>viewer.installed.some(m=>m.visible)&&viewer.installed.filter(m=>m.visible).every(m=>m.userData.meta.group==='landings')),'isolate shows only landing assembly');await shot('viewer-01-landings','Front closed supports — actual bodies and reference hardware');
const layer=await p.evaluate(()=>viewer.installed.find(m=>m.name==='FrontLandingL_Layer1').name);await p.evaluate(n=>viewer.choose(n,false),layer);const selection=await p.locator('#selection').textContent();check(selection.toLowerCase().includes('front playfield closed support')&&await p.evaluate(()=>viewer.installed.find(m=>m.name==='FrontLandingL_Layer1').userData.meta.geometry_authority.status==='CURRENT_V3363'),'landing selection is functional and traceable',selection);await shot('viewer-02-selection','Landing IDs, material, hardware hold and native authority');
await p.evaluate(()=>landings3363.path());check(await p.locator('.packing-label').allTextContents().then(a=>a.some(s=>s.includes('FRONT:'))&&a.some(s=>s.includes('REAR:'))),'both explicit load paths');await shot('viewer-03-load-path','Rear dowel/cradles and front side landing load paths');
await p.evaluate(()=>{landings3363.cleanup();animation333.exit();viewer.applyState('EXPLODED DETAILED');document.getElementById('scope').value='PLAYFIELD';viewer.refresh();});check(await p.evaluate(()=>viewer.detail.filter(m=>m.userData.meta.group==='landings'&&m.userData.meta.kind==='wood').length===6),'six actual18mm landing manufacturing members');check(await p.evaluate(()=>viewer.detail.filter(m=>m.userData.meta.group==='landings'&&m.userData.meta.kind==='hardware').every(m=>m.userData.meta.hardware_id&&m.userData.meta.status==='PURCHASE_BEFORE_CNC')),'new hardware has IDs and purchased-dimension holds');await shot('viewer-04-exploded','Detailed landing wood and hardware with semantic offsets');
async function endpoint(id,state,names){return await p.evaluate(({id,state,names})=>{
 animation333.exit();viewer.applyState(state);const refs={};for(const n of names)refs[n]=viewer.installed.find(m=>m.name===n).geometry.attributes.position.array.slice();animation333.start(id);animation333.seek(1);let max=0;
 for(const n of names){const m=viewer.installed.find(m=>m.name===n);m.updateMatrix();const a=m.geometry.attributes.position.array,r=refs[n];for(let i=0;i<a.length;i+=3){const v=new THREE.Vector3(a[i],a[i+1],a[i+2]).applyMatrix4(m.matrix);let near=Infinity;for(let j=0;j<r.length;j+=3)near=Math.min(near,Math.hypot(v.x-r[j],v.y-r[j+1],v.z-r[j+2]));max=Math.max(max,near);}}return max;
},{id,state,names});}
const receivers=VM.playfield_moving_names.filter(n=>n.startsWith('FrontLanding'));
for(const [id,state,names] of [['service-pf-release','PLAYFIELD RETENTION RELEASED',VM.retention_moving_names],['service-pf-service','PLAYFIELD SERVICE 50°',['PF_BasePlywood',...receivers]],['service-pf-lift','PLAYFIELD LIFT-OUT',['PF_BasePlywood',...receivers]],['service-pf-close','PLAY',['PF_BasePlywood',...receivers,...VM.retention_moving_names]]]){const max=await endpoint(id,state,names);check(max<.003,'exact native endpoint '+id,max);}
check(await p.evaluate(()=>{const m=viewer.installed.find(m=>m.name==='CoinStudy_DoorLeaf');return Math.abs(m.quaternion.angleTo(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),-110*Math.PI/180)))<1e-6;}),'front coin door open for retention access');
await p.evaluate(()=>{animation333.start('service-pf-service');animation333.seek(.01);});check(await p.evaluate(()=>viewer.installed.filter(m=>m.userData.meta.group==='landings'&&!animation333.data.motions.pf_names.includes(m.name)).every(m=>m.quaternion.equals(new THREE.Quaternion())&&m.position.length()<1e-8)),'front landings stay fixed during opening');await shot('viewer-05-early-separation','Early opening — fixed front pads separate after retention release');
await p.evaluate(()=>{animation333.start('service-pf-close');animation333.seek(.4);});check(await p.evaluate(()=>{const m=viewer.installed.find(m=>m.name==='PF_WoodDowel');m.geometry.computeBoundingBox();m.updateMatrix();const c=m.geometry.boundingBox.getCenter(new THREE.Vector3()).applyMatrix4(m.matrix);return Math.abs(c.y-animation333.data.motions.pf_axis[1])<.001&&Math.abs(c.z-animation333.data.motions.pf_axis[2])<.001;}),'rear dowel seated before front lowers');await shot('viewer-06-rear-seating','Rear seating phase at2° before front landing approach');
await p.evaluate(()=>animation333.seek(.8));await shot('viewer-07-front-contact','Front on pads before positive retention engagement');await p.evaluate(()=>animation333.seek(1));await shot('viewer-08-closed','Closed supported architecture — reference hardware not CNC release');
for(const id of ['assembly-05.2','assembly-06.2','assembly-06.3']){await p.evaluate(id=>{animation333.start(id);animation333.seek(.65);},id);check(await p.locator('#mode-tag').textContent().then(s=>s.includes('SCHEMATIC')),'manual animation honestly schematic '+id);check(await p.evaluate(()=>viewer.detail.some(m=>m.visible&&m.userData.meta.group==='landings')),'landing parts in manual animation '+id);}
await shot('viewer-09-manual-step','Landing, seating, leveling and retention manual sequence');
await p.evaluate(()=>{animation333.start('pack');animation333.seek(1);});check(await p.evaluate(n=>animation333.packingMeshes.length===n&&animation333.packingMeshes.every(m=>m.visible),reg.parts.length),'all manufacturing members packed once');
await p.evaluate(()=>{animation333.exit();viewer.applyState('PLAY');});check(await p.evaluate(()=>['primary','secondary'].every((kind,i)=>['L','R'].every(side=>{const m=viewer.installed.find(m=>m.name==='LeafButton_'+kind+'_'+side);m.geometry.computeBoundingBox();const c=m.geometry.boundingBox.getCenter(new THREE.Vector3());return Math.abs(c.y-[89,127][i])<.001&&Math.abs(c.z-[350.593661971831,357.2302816901408][i])<.001;}))),'button authority unchanged');
await ctx.close();await browser.close();browser=await launch();const tc=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true,offline:true}),t=await ready(tc);
await t.locator('#lang-pt').tap();await t.locator('#palette').selectOption('accessible');await t.locator('#landings-panel').evaluate(e=>e.open=true);await t.locator('#landings-isolate').tap();check(await t.evaluate(()=>viewer.installed.filter(m=>m.visible).every(m=>m.userData.meta.group==='landings')),'tablet landing isolate');check(await t.locator('#landings-isolate').textContent()==='ISOLAR APOIOS FRONTAIS','Portuguese landing controls');check(await t.evaluate(()=>[...document.querySelectorAll('#landings-panel button')].every(e=>e.getBoundingClientRect().height>=44)),'tablet44px landing actions');
await t.locator('#landings-close').tap();await t.locator('#anim-play').tap();await t.waitForFunction(()=>animation333.progress>0,null,{timeout:10000});await t.locator('#anim-pause').tap();const at=await t.evaluate(()=>animation333.progress);await t.waitForTimeout(150);check(await t.evaluate(()=>animation333.progress)===at,'tablet closing play/pause');check(await t.locator('#animation-title').textContent().then(s=>s.includes('Assentar cavilha')),'Portuguese closing animation');check(await t.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'tablet no overflow');await t.screenshot({path:path.join(O,'viewer-10-tablet.png')});views.push({image:'viewer-10-tablet.png',title:'Tablet landing inspection/closing — PT-BR Accessible'});await tc.close();
check(!errors.length,'no JavaScript errors',errors);check(!net.length,'offline no network',net);const prior='exports/generated/playfield-rest-v3362/browser-validation.json';const inherited=JSON.parse(fs.readFileSync(path.join(R,prior),'utf8'));check(inherited.pass,'prior untouched controls passed');
fs.writeFileSync(path.join(O,'browser-validation.json'),JSON.stringify({pass:true,scope:'Focused new front support visibility, exact native release/service/lift/closing endpoints, manual steps, packing, EN/PT and emulated touch. Unchanged broader UI inherited.',checks,errors,network:net,tablet_playback:'PASS_EMULATED_TOUCH_PHYSICAL_FPS_NOT_CERTIFIED',inherited:{path:prior,sha256:sha(path.join(R,prior)),checks:inherited.checks.length},viewer_sha256:sha(path.join(R,'exports/generated/viewer-v32/index.html'))},null,2)+'\n');fs.writeFileSync(path.join(O,'viewer-review-views.json'),JSON.stringify(views,null,2)+'\n');console.log('V3363_BROWSER_PASS',checks.length);
}finally{await browser.close();}
