/** Focused V33.7 offline generic-module/two-stock UI QA. CERN-OHL-S-2.0. */
import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const R=process.cwd(),O=path.join(R,'exports/generated/two-stock-user-module-v337'),checks=[],errors=[],network=[],views=[];
const J=n=>JSON.parse(fs.readFileSync(path.join(O,n),'utf8')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const MM=J('module-motion.json'),reg=J('manufacturing-register.json');
const check=(v,n,d)=>{checks.push({name:n,pass:!!v,detail:d});if(!v)throw Error(n+' '+JSON.stringify(d));};
const launch=()=>chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let browser=await launch();
async function ready(ctx){const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))network.push(r.url());});await p.goto('file://'+path.join(R,'exports/generated/viewer-v32/index.html'));await p.waitForFunction(()=>document.body.dataset.underfrontReady==='true',null,{timeout:90000});return p;}
try{
 const ctx=await browser.newContext({viewport:{width:1600,height:1050},offline:true}),p=await ready(ctx);check(await p.evaluate(()=>viewer.data.geometry_revision==='V33.7'),'new current revision');
 check(await p.evaluate(()=>viewer.data.groups.some(g=>g.id==='underfront'&&g.names.en==='UNDERFRONT USER MODULE')),'dedicated user-module group');check(await p.evaluate(()=>!document.body.innerText.includes('MASTER VOLUME')&&!document.body.innerText.includes('OFF / AUDIO / PINBALL')&&!document.body.innerText.includes('BLUETOOTH PAIR')),'old fixed-function schematic absent');
 async function shot(n,title){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:path.join(O,n+'.png')});views.push({image:n+'.png',title});}
 await p.evaluate(()=>{document.getElementById('underfront-panel').open=true;underfront337.isolate();});
 for(const variant of MM.variants){await p.locator('#underfront-variant').selectOption(variant.id);const visible=await p.evaluate(()=>viewer.installed.filter(m=>m.visible).map(m=>m.name));const expected=[...new Set([...MM.common_names,...variant.object_names,'FLOOR'])].sort();check(JSON.stringify([...visible].sort())===JSON.stringify(expected),'only selected samebay variant '+variant.id,{visible,expected});await shot('viewer-variant-'+variant.id,variant.names.en);}
 await p.locator('#underfront-variant').selectOption(MM.default_variant);const key=MM.removable_names.find(n=>n.includes('Plate'));await p.evaluate(n=>viewer.choose(n,false),key);check(await p.locator('#selection').textContent().then(s=>s.includes('12')&&s.includes('M0')),'plate metadata nominal12mm and canonical family');await shot('viewer-module-selection','User plate metadata and hardware-dependent interface');
 await p.evaluate(()=>{animation333.exit();viewer.applyState('EXPLODED DETAILED');document.getElementById('scope').value='ALL';viewer.refresh();});const ids=reg.parts.filter(p=>p.nominal_stock_thickness_mm!==null).map(p=>[p.instance_id,p.nominal_stock_thickness_mm]);check(await p.evaluate(ids=>ids.every(([id,t])=>viewer.detail.find(m=>m.name===id)?.userData.meta.thickness===t),ids),'every detailed piece uses current nominal stock');check(ids.every(([,t])=>[12,18].includes(t)),'all plywood12or18only');await shot('viewer-two-stock-exploded','Two-stock detailed manufacturing inventory');
 await p.evaluate(()=>{animation333.start('assembly-07.3');animation333.seek(.7);});check(await p.locator('#mode-tag').textContent().then(s=>s.includes('SCHEMATIC')),'module assembly explicitly schematic');check(await p.evaluate(()=>viewer.detail.some(m=>m.visible&&m.userData.meta.group==='underfront')),'module actual flat pieces in assembly');await shot('viewer-module-assembly','Module assembly with actual blank plate');
 await p.evaluate(()=>{animation333.start('service-underfront');animation333.seek(1);});const poses=await p.evaluate(names=>names.map(n=>{const m=viewer.installed.find(m=>m.name===n);return {name:n,xyz:m?m.position.toArray():null};}),MM.removable_names);check(poses.every(r=>r.xyz&&r.xyz.every((x,i)=>Math.abs(x-MM.removal_vector_mm[i])<1e-6)),'module removal endpoint matches documented vector',poses);check(await p.locator('#animation-status').textContent().then(s=>s.includes(MM.rigid_removal_validated?'validated':'SCHEMATIC')),'removal validation classification honest');await shot('viewer-module-removal','Underfront plate removal; harness remains configurable');
 await p.evaluate(()=>{animation333.start('pack');animation333.seek(1);});check(await p.evaluate(n=>animation333.packingMeshes.length===n&&animation333.packingMeshes.every(m=>m.visible),reg.parts.length),'every packing member shown once');check(await p.evaluate(()=>{const Q=animation333.data,ids=new Set(Q.packaging.candidates.find(c=>c.target_kg===Q.packaging.preferred_target_kg).bundles.map(b=>b.id));return animation333.packingMeshes.every(m=>ids.has(m.userData.pack.bundle));}),'packing honors authoritative preferred target');await shot('viewer-packing','Current two-stock flatpack packing');
 for(const id of ['service-pf-release','service-pf-service','service-pf-lift','service-pf-close','service-fold']){await p.evaluate(id=>{animation333.start(id);animation333.seek(1);},id);check(await p.evaluate(()=>viewer.installed.some(m=>m.visible)),'inherited service state remains usable '+id);}
 await ctx.close();await browser.close();browser=await launch();const tc=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true,offline:true}),t=await ready(tc);await t.locator('#lang-pt').tap();await t.locator('#palette').selectOption('accessible');await t.locator('#underfront-panel').evaluate(e=>e.open=true);await t.locator('#underfront-isolate').tap();check(await t.locator('#underfront-isolate').textContent()==='ISOLAR MÓDULO DO USUÁRIO','PT-BR module controls');check(await t.evaluate(()=>[...document.querySelectorAll('#underfront-panel button,#underfront-panel select')].every(e=>e.getBoundingClientRect().height>=44)),'tablet touch targets44px');await t.locator('#underfront-remove').tap();await t.locator('#anim-play').tap();await t.waitForFunction(()=>animation333.progress>0,null,{timeout:10000});await t.locator('#anim-pause').tap();const progress=await t.evaluate(()=>animation333.progress);await t.waitForTimeout(150);check(await t.evaluate(()=>animation333.progress)===progress,'tablet module play/pause');check(await t.locator('#animation-title').textContent().then(s=>s.includes('módulo')),'PT-BR animation title');check(await t.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'tablet no overflow');await t.screenshot({path:path.join(O,'viewer-tablet.png')});views.push({image:'viewer-tablet.png',title:'Tablet module controls — PT-BR Accessible'});await tc.close();
 check(!errors.length,'noJavaScript errors',errors);check(!network.length,'offline no network',network);const prior='exports/generated/front-landings-v3363/browser-validation.json';check(JSON.parse(fs.readFileSync(path.join(R,prior))).pass,'unchanged broaderUI prior validated');
 fs.writeFileSync(path.join(O,'browser-validation.json'),JSON.stringify({pass:true,scope:'Focused new underfront variants, metadata, schematic assembly, native/documented removal endpoint, two-stock detailed/packing, inherited service smoke, EN/PT and emulated touch; broader prior UI inherited.',checks,errors,network,tablet_playback:'PASS_EMULATED_TOUCH_PHYSICAL_FPS_NOT_CERTIFIED',inherited:{path:prior,sha256:sha(path.join(R,prior))},viewer_sha256:sha(path.join(R,'exports/generated/viewer-v32/index.html'))},null,2)+'\n');fs.writeFileSync(path.join(O,'viewer-review-views.json'),JSON.stringify(views,null,2)+'\n');console.log('V337_BROWSER_PASS',checks.length);
}finally{await browser.close();}
