/** Focused V33.8 offline SW02/modularity/holds QA. CERN-OHL-S-2.0. */
import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const R=process.cwd(),O=path.join(R,'exports/generated/service-productization-v338'),checks=[],errors=[],network=[],views=[];
const J=n=>JSON.parse(fs.readFileSync(path.join(O,n),'utf8')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const reg=J('manufacturing-register.json'),manual=J('assembly-manual.json');
const check=(v,n,d)=>{checks.push({name:n,pass:!!v,detail:d});if(!v)throw Error(n+' '+JSON.stringify(d));};
const launch=()=>chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let browser=await launch();
async function ready(ctx){const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))network.push(r.url());});await p.goto('file://'+path.join(R,'exports/generated/viewer-v32/index.html'));await p.waitForFunction(()=>document.body.dataset.modularityReady==='true',null,{timeout:90000});return p;}
try{
 const ctx=await browser.newContext({viewport:{width:1600,height:1050},offline:true}),p=await ready(ctx);check(await p.evaluate(()=>viewer.data.geometry_revision==='V33.8'),'current revision V33.8');
 async function shot(n,title){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:path.join(O,n+'.png')});views.push({image:n+'.png',title});}
 check(await p.evaluate(()=>!viewer.installed.some(m=>m.visible&&m.userData.meta.optional_study)),'optional study defaults hidden');
 check(await p.evaluate(()=>viewer.data.groups.length===22),'22 independent visibility groups');
 check(await p.locator('#state-note').textContent().then(s=>s.includes('PRIMARY RAISED-PLAYFIELD SUPPORT: HOLD')&&s.includes('−1.9/+0.9')),'visible primary-support hold and safe setup screen');await shot('viewer-01-current','Current V33.8 and primary service-support hold');
 await p.evaluate(()=>{landings3363.isolate();viewer.choose('FrontLandingL_Block',false);});check(await p.locator('#selection').textContent().then(s=>s.includes('SW02')&&s.includes('SHOP')),'SW02 canonical metadata / shop-made');check(await p.evaluate(()=>viewer.installed.filter(m=>m.visible&&m.userData.meta.kind==='wood').length===2),'two solid landing blocks');check(await p.evaluate(()=>!viewer.installed.some(m=>/FrontLanding.*(Layer|LaminationScrew)/.test(m.name))),'retired layers and binder screws absent');await shot('viewer-02-sw02','SW02 supports and unchanged tool-operated retention');
 await p.evaluate(()=>{viewer.applyState('EXPLODED DETAILED');document.getElementById('scope').value='ALL';viewer.refresh();});check(await p.evaluate(()=>viewer.detail.filter(m=>['P095-Solid','P096-Solid'].includes(m.name)).length===2),'real SW02 detailed pieces');
 const ids=reg.parts.filter(p=>p.nominal_stock_thickness_mm!==null).map(p=>[p.instance_id,p.nominal_stock_thickness_mm]);check(ids.every(([,t])=>[12,18].includes(t))&&await p.evaluate(ids=>ids.every(([id,t])=>viewer.detail.find(m=>m.name===id)?.userData.meta.thickness===t),ids),'current nominal plywood 12/18 only');check(await p.evaluate(()=>!viewer.detail.some(m=>m.userData.meta.hardware_id==='F60')),'retired F60 excluded detailed inventory');
 const steps=manual.stages.flatMap(s=>s.steps);check(await p.evaluate(steps=>steps.length===36&&steps.every(s=>animation333.data.clips.some(c=>c.id==='assembly-'+s.id)),steps),'all 36 manual steps have clips');check(await p.evaluate(()=>new Set(animation333.data.clips.map(c=>c.id)).size===animation333.data.clips.length),'animation IDs unique');
 await p.evaluate(()=>{animation333.start('assembly-06.0');animation333.seek(.7);});check(await p.evaluate(()=>viewer.detail.filter(m=>m.visible&&['P095-Solid','P096-Solid'].includes(m.name)).length===2),'SW02 preparation uses real finished members');check(await p.locator('#animation-status').textContent().then(s=>s.includes('SCHEMATIC')&&s.includes('solid-wood')),'SW02 preparation honest schematic');await shot('viewer-03-sw02-assembly','SW02 assembly framework');
 await p.evaluate(()=>modularity338.inspect());check(await p.evaluate(()=>viewer.installed.filter(m=>m.visible&&m.userData.meta.optional_study&&m.userData.meta.kind==='wood').length===2),'optional boards inspection');check(await p.evaluate(()=>viewer.installed.filter(m=>m.visible&&m.userData.meta.group==='routes').length===2),'two low route planning zones');await p.evaluate(()=>viewer.choose('AccessoryBoardS2Right',false));check(await p.locator('#selection').textContent().then(s=>s.includes('ACC01')&&s.includes('OPTIONAL')),'optional ACC01 metadata');await shot('viewer-04-modularity','Optional boards, removable clamps and low route zones');
 await p.evaluate(()=>{animation333.start('assembly-18.2');animation333.seek(.7);});check(await p.evaluate(()=>viewer.detail.filter(m=>m.visible&&m.userData.meta.optional_study).length===2),'optional assembly reveals two study pieces');check(await p.locator('#animation-status').textContent().then(s=>s.includes('excluded from minimum')&&s.includes('HOLD')),'optional assembly notes exclude minimum and preserve holds');await shot('viewer-05-optional-assembly','Optional schematic assembly, not delivered minimum');
 await p.evaluate(()=>{animation333.start('assembly-01.1');animation333.seek(.7);});check(await p.evaluate(()=>!viewer.detail.some(m=>m.visible&&m.userData.meta.optional_study)),'minimum identification does not include optional boards');
 await p.evaluate(()=>{animation333.start('service-pf-service');animation333.seek(1);});check(await p.locator('#animation-status').textContent().then(s=>s.includes('PRIMARY RAISED-PLAYFIELD SUPPORT: HOLD')),'animated 50-degree pose primary support HOLD');check(await p.evaluate(()=>viewer.installed.find(m=>m.name==='FrontLandingL_Block').position.length()<1e-8),'SW02 fixed during playfield opening');await shot('viewer-06-service-hold','50° geometric state; primary service-support unresolved');
 for(const id of ['service-pf-lift','service-pf-close','service-fold','service-underfront']){await p.evaluate(id=>{animation333.start(id);animation333.seek(1);},id);check(await p.evaluate(()=>viewer.installed.some(m=>m.visible)),'preserved service endpoint '+id);}
 await p.evaluate(()=>{animation333.start('pack');animation333.seek(1);});check(await p.evaluate(n=>animation333.packingMeshes.length===n&&animation333.packingMeshes.every(m=>m.visible),reg.parts.length),'104 minimum packing pieces shown exactly once');check(await p.evaluate(()=>!animation333.packingMeshes.some(m=>m.userData.meta.optional_study)),'optional boards absent all packing bundles');
 check(await p.evaluate(()=>['P095-Solid','P096-Solid'].every(id=>{const m=animation333.packingMeshes.find(m=>m.name===id);m.geometry.computeBoundingBox();const s=m.geometry.boundingBox.getSize(new THREE.Vector3());return Math.abs(s.z-54)<1e-4&&Math.abs(s.x*s.y-68*70)<.01&&m.geometry.boundingBox.min.z>=0;})),'SW02 delivered blanks use correct package coordinates and 54mm height');await shot('viewer-07-packing','104-piece minimum packing with SW02 shop blanks');
 await ctx.close();await browser.close();browser=await launch();const tc=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true,offline:true}),t=await ready(tc);await t.locator('#lang-pt').tap();await t.locator('#palette').selectOption('accessible');await t.locator('#modularity-panel').evaluate(e=>e.open=true);await t.locator('#modularity-inspect').tap();check(await t.locator('#state-note').textContent().then(s=>s.includes('APOIO PRIMÁRIO')&&s.includes('PENDENTE')),'PT-BR support hold');check(await t.locator('#modularity-inspect').textContent()==='PLACAS + ZONAS DE CABOS','PT-BR optional controls');check(await t.evaluate(()=>[...document.querySelectorAll('#modularity-panel button')].every(e=>e.getBoundingClientRect().height>=44)),'tablet touch controls 44px');await t.locator('#modularity-assemble').tap();await t.locator('#anim-play').tap();await t.waitForFunction(()=>animation333.progress>0,null,{timeout:10000});await t.locator('#anim-pause').tap();const progress=await t.evaluate(()=>animation333.progress);await t.waitForTimeout(150);check(await t.evaluate(()=>animation333.progress)===progress,'tablet optional play/pause');check(await t.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'tablet no overflow');check(await t.evaluate(()=>{const a=document.getElementById('animation-bar').getBoundingClientRect(),b=document.getElementById('state-note').getBoundingClientRect();return a.bottom<=b.top||b.bottom<=a.top;}),'tablet playback and hold note do not overlap');await t.screenshot({path:path.join(O,'viewer-08-tablet.png')});views.push({image:'viewer-08-tablet.png',title:'Tablet optional study — PT-BR Accessible'});await tc.close();
 check(!errors.length,'no JavaScript errors',errors);check(!network.length,'offline no network',network);const prior='exports/generated/two-stock-user-module-v337/browser-validation.json';check(JSON.parse(fs.readFileSync(path.join(R,prior))).pass,'inherited broader V33.7 UI evidence');
 fs.writeFileSync(path.join(O,'browser-validation.json'),JSON.stringify({pass:true,scope:'Focused SW02 installed/detailed/delivered packing, optional module/route groups, 36-step clips, explicit primary-support hold, retained motion smoke, EN/PT and emulated touch. Broader unchanged UI inherits V33.7 hash evidence.',checks,errors,network,tablet_playback:'PASS_EMULATED_TOUCH_PHYSICAL_FPS_NOT_CERTIFIED',inherited:{path:prior,sha256:sha(path.join(R,prior))},viewer_sha256:sha(path.join(R,'exports/generated/viewer-v32/index.html'))},null,2)+'\n');fs.writeFileSync(path.join(O,'viewer-review-views.json'),JSON.stringify(views,null,2)+'\n');console.log('V338_BROWSER_PASS',checks.length);
}finally{await browser.close();}
