/** Offline browser regression and real review images. CERN-OHL-S-2.0. */
import {chromium} from 'playwright';
import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=process.env.VPIN_REPO||process.cwd(),out=path.join(root,'exports/generated/viewer-v332');
const checks=[],views=[],errors=[],network=[];
function expect(ok,name,details){checks.push({name,pass:!!ok,details});if(!ok)throw Error(name+' '+JSON.stringify(details));}
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-background-networking','--no-first-run','--allow-file-access-from-files','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const context=await browser.newContext({viewport:{width:1600,height:1050},offline:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
 const started=Date.now();await page.goto('file://'+path.join(root,'exports/generated/viewer-v32/index.html'));await page.waitForFunction(()=>document.body.dataset.viewerReady==='true',null,{timeout:60000});const loadMs=Date.now()-started;
 const evalv=fn=>page.evaluate(fn);
 async function shot(n,en,pt){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(out,n+'-review.png')});views.push({number:n,title:{en,'pt-BR':pt},image:n+'-review.png'});}
 expect(await evalv(()=>viewer.language()==='en'&&viewer.palette()==='original'),'English/original defaults');
 expect(await evalv(()=>viewer.installed.find(m=>m.name==='LeafButton_primary_L').material.color.clone().convertLinearToSRGB().getHex()===0x176eaa&&viewer.installed.find(m=>m.name==='CandidateGlass').material.color.clone().convertLinearToSRGB().getHex()===0x465c73),'Legacy Original palette assignments retained');
 expect(await evalv(()=>viewer.detail.length===0),'Detailed GPU objects are lazy');
 expect(await evalv(()=>Object.keys(viewer.groups).length===18),'18 independent visibility groups');
 expect(await evalv(()=>viewer.installed.filter(m=>m.visible&&/RetractedReserve/.test(m.name)).length===0),'Closed doors do not show retracted tongues');
 await shot('01','Default offline viewer','Visualizador offline padrão');
 await page.click('#interior');
 expect(await evalv(()=>['playfield','supports','matrix'].every(g=>!viewer.active().some(m=>m.visible&&m.userData.meta.group===g))),'Interior hides complete playfield, supports and matrix');
 expect(await evalv(()=>['PC_BASE','SHELF_1','SHELF_2','SHELF_3','FLOOR','SIDE_L','FloorIntakeFanL','SSF_Exciter1L'].every(n=>viewer.installed.find(m=>m.name===n)?.visible)),'Interior retains shell, shelves, PCBase, fan and SSF');await shot('02','Interior inspection','Inspeção do interior');
 await evalv(()=>{viewer.applyState('PLAY');viewer.cameraPreset('INTERIOR');});await page.click('#hide-pf');expect(await evalv(()=>!viewer.active().some(m=>m.visible&&m.userData.meta.group==='playfield')&&viewer.installed.find(m=>m.name==='PF_OpenCradleL').visible),'Hide playfield retains fixed supports');await shot('03','Playfield hidden','Playfield oculto');
 const cam=await evalv(()=>viewer.camera.position.toArray());await page.click('#hide-supports');expect(JSON.stringify(cam)===JSON.stringify(await evalv(()=>viewer.camera.position.toArray())),'Visibility action preserves camera');expect(await evalv(()=>!viewer.installed.find(m=>m.name==='PF_OpenCradleL').visible),'Hide fixed supports');await shot('04','Playfield and supports hidden','Playfield e apoios ocultos');
 await evalv(()=>{viewer.applyState('BACKBOX REAR DOORS OPEN');viewer.cameraPreset('BACKBOX REAR');});
 expect(await evalv(()=>['BB_CamTongueClosedReserve','BB_PassiveBoltClosedReserve0','BB_PassiveBoltClosedReserve1'].every(n=>!viewer.installed.find(m=>m.name===n).visible)&&viewer.installed.filter(m=>m.visible&&/RetractedReserve/.test(m.name)).length===3),'Door-open state replaces closed latch meshes with saved retracted meshes');await shot('05','Both backbox doors open 100°','Portas do backbox abertas 100°');
 await page.click('#bb-interior');expect(await evalv(()=>!viewer.installed.find(m=>m.name==='BB_Backglass').visible&&!viewer.installed.find(m=>m.name==='BB_Display32').visible&&viewer.installed.find(m=>m.name==='BB_MonitorCarrier0').visible),'Backbox interior exposes carrier and preserves cassette');await shot('06','Backbox interior inspection','Inspeção interna do backbox');
 for(const state of ['PLAYFIELD SERVICE 50°','PLAYFIELD LIFT-OUT','BACKBOX FOLD 45°','BACKBOX FOLD 90°']){
  await page.evaluate(s=>viewer.applyState(s),state);expect(await evalv(()=>!viewer.installed.find(m=>m.name==='CandidateGlass').visible&&!viewer.installed.find(m=>m.name==='MatrixCarrier').visible),state+' removes main glass and matrix');
  if(state.includes('FOLD'))expect(await evalv(()=>['BB_Backglass','BB_LowerCassetteFrame','BB_Display32','BB_DoorL','BB_DoorR'].every(n=>viewer.installed.find(m=>m.name===n).visible)&&document.getElementById('state-note').textContent.includes('Locks released and parked')),state+' retains populated backbox and correct prerequisites');
 }
 await evalv(()=>viewer.applyState('BACKBOX UNLOCKED'));expect(await evalv(()=>viewer.installed.find(m=>m.name==='BB_UprightLockLKnob').geometry.boundingBox.min.x>160),'Unlocked state has parked left knob');
 await evalv(()=>{viewer.applyState('EXPLODED OVERVIEW');viewer.cameraPreset('PLAYER');viewer.frame();});await shot('07','Exploded overview — semantic assemblies','Visão explodida geral — conjuntos');
 await evalv(()=>{viewer.applyState('EXPLODED DETAILED');viewer.frame();});expect(await evalv(()=>viewer.detail.filter(m=>m.userData.meta.kind==='wood').length===130),'Detailed view uses all 130 real manufacturing pieces');expect(await evalv(()=>new Set(viewer.detail.filter(m=>m.userData.meta.hardware_id).map(m=>m.userData.meta.hardware_id)).size===148),'All 148 V33 catalog families represented honestly');await shot('08','Detailed exploded — all assemblies','Explodida detalhada — todos os conjuntos');
 await page.selectOption('#detail-filter','wood');await evalv(()=>viewer.frame());expect(await evalv(()=>viewer.active().filter(m=>m.visible).length===130&&viewer.active().filter(m=>m.visible).every(m=>m.userData.meta.kind==='wood')),'Wood-only exposes exactly 130 pieces');await shot('09','Detailed exploded — wood only','Explodida detalhada — somente madeira');
 await page.selectOption('#detail-filter','hardware');await evalv(()=>viewer.frame());expect(await evalv(()=>viewer.active().filter(m=>m.visible).every(m=>m.userData.meta.kind==='hardware')),'Hardware-only excludes wood');await shot('10','Detailed exploded — hardware only','Explodida detalhada — somente ferragens');
 await page.selectOption('#detail-filter','both');await page.selectOption('#scope','PLAYFIELD');await evalv(()=>viewer.frame());expect(await evalv(()=>viewer.active().filter(m=>m.visible).every(m=>m.userData.meta.scope==='PLAYFIELD')),'Playfield assembly scope');await shot('11','Playfield exploded','Playfield explodido');
 await page.selectOption('#scope','BACKBOX');await evalv(()=>viewer.frame());await shot('12','Backbox exploded','Backbox explodido');
 await page.selectOption('#scope','ALL');await page.selectOption('#detail-filter','wood');await page.selectOption('#family-focus','LegBlock');expect(await evalv(()=>viewer.active().filter(m=>m.visible).length===28),'28 real leg laminations');await shot('13','Leg-block layers — 28 pieces','Camadas dos blocos dos pés — 28 peças');
 await page.selectOption('#family-focus','IntakeDownBaffle');expect(await evalv(()=>viewer.active().filter(m=>m.visible).length===8),'Eight actual intake-baffle pieces');await shot('14','Intake-baffle decomposition','Decomposição dos defletores de entrada');
 await page.selectOption('#family-focus','GlassTopRetainer');expect(await evalv(()=>viewer.active().filter(m=>m.visible).length===2),'Glass-retainer cap and strip');await shot('15','Glass-retainer cap and strip','Tampa e tira do retentor de vidro');
 await evalv(()=>viewer.choose('HW:BB_UprightLockLKnob',true));await page.locator('#selection').scrollIntoViewIfNeeded();expect(await evalv(()=>viewer.selectionEdges()?.visible&&document.getElementById('selection').textContent.includes('H11')),'Hardware callout has ID and non-color edge outline');await shot('16','H11 hardware callout','Chamada da ferragem H11');
 await page.fill('#search','SideL');expect(await page.locator('#parts button').count()>0,'Canonical SideL search');await page.locator('#parts button').first().click();await page.locator('#selection').scrollIntoViewIfNeeded();expect(await evalv(()=>document.getElementById('selection').textContent.includes('M001')&&document.getElementById('selection').textContent.includes('ONE_SIDE_CNC_PLUS_MANUAL_FINISH')),'Selected part metadata links M-family and route');await shot('17','Part selection and manufacturing metadata','Seleção e metadados de fabricação');
 for(const q of ['SideR','T1','S2','BBFloor','F01','H11','M019']){await page.fill('#search',q);expect(await page.locator('#parts button').count()>0,'Search '+q);}
 const snapshot=await evalv(()=>viewer.installed.map(m=>[m.name,m.geometry.uuid,m.position.toArray(),m.visible]));await evalv(()=>{viewer.setLanguage('pt-BR');viewer.setPalette('accessible');});expect(JSON.stringify(snapshot)===JSON.stringify(await evalv(()=>viewer.installed.map(m=>[m.name,m.geometry.uuid,m.position.toArray(),m.visible]))),'Language/palette do not change geometry or visibility');expect(await evalv(()=>viewer.installed.find(m=>m.name==='LeafButton_primary_L').material.color.clone().convertLinearToSRGB().getHex()===0x0072b2),'Legacy Accessible primary-control color retained');expect(await page.locator('#hide-supports').textContent()==='OCULTAR PLAYFIELD + SUPORTES','PT-BR quick actions');expect(await evalv(()=>viewer.selectionEdges()?.visible),'Accessible selection uses edges');
 await page.setViewportSize({width:1024,height:1366});await page.click('#reset');await page.locator('aside').evaluate(e=>e.scrollTop=0);await page.click('#interior');await shot('18','Tablet controls — PT-BR / Accessible','Controles de tablet — PT-BR / Acessível');
 const targets=await evalv(()=>[...document.querySelectorAll('button,select,summary,#groups label')].filter(e=>e.getClientRects().length&&!e.disabled).map(e=>({id:e.id||e.textContent.slice(0,25),height:e.getBoundingClientRect().height})));expect(targets.every(t=>t.height>=43.9),'All visible touch targets at least 44 px',targets.filter(t=>t.height<43.9));expect(await evalv(()=>document.documentElement.scrollWidth===innerWidth),'Tablet has no horizontal page overflow');
 await page.click('#toggle-controls');expect(await evalv(()=>document.body.classList.contains('controls-hidden')&&document.getElementById('stage').clientWidth===innerWidth),'Tablet full-width model toggle');await page.click('#toggle-controls');
 await page.setViewportSize({width:1600,height:1050});await evalv(()=>{viewer.setLanguage('en');viewer.setPalette('original');viewer.openManual('05',0,true);viewer.manualView(true);});await page.locator('aside').evaluate(e=>e.scrollTop=0);await shot('19','Assembly step — cradle supports','Passo de montagem — apoios dos berços');
 expect(await page.locator('#manual-panel').textContent().then(s=>s.includes('F01 × 6')&&s.includes('FACE A')),'Manual step connects exact hardware quantity and face authority');
 await evalv(()=>{viewer.openManual('17',0,false);viewer.applyState('BACKBOX FOLD 45°');viewer.cameraPreset('PLAYER');});await shot('20','Normal fold checkpoint','Verificação da dobra normal');
 expect(await page.locator('#manual-panel').textContent().then(s=>s.includes('No routine electronics disconnection')&&s.includes('MAIN PLAYFIELD GLASS')),'Manual normal-fold prerequisites');
 await evalv(()=>{viewer.setLanguage('pt-BR');viewer.openManual('17',0,false);});expect(await page.locator('#manual-panel').textContent().then(s=>s.includes('VERIFICAÇÃO')&&s.includes('Sem desconexão elétrica de rotina')),'PT-BR manual headings and instructions');
 await page.setViewportSize({width:834,height:1194});await page.click('#reset');await page.locator('aside').evaluate(e=>e.scrollTop=0);expect(await evalv(()=>document.documentElement.scrollWidth===innerWidth),'Portrait tablet no overflow');
 await evalv(()=>viewer.openManual('11',0,true));expect(await evalv(()=>viewer.active().filter(m=>m.visible).every(m=>m.userData.meta.kind==='wood'||m.userData.meta.classification==='REQUIRED_FLATPACK_HARDWARE')),'Cumulative mechanical manual excludes optional electronics/fans');
 const touchContext=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true,deviceScaleFactor:1,offline:true});
 const touch=await touchContext.newPage();await touch.goto('file://'+path.join(root,'exports/generated/viewer-v32/index.html'));await touch.waitForFunction(()=>document.body.dataset.viewerReady==='true');await touch.locator('#hide-supports').tap();expect(await touch.evaluate(()=>!viewer.installed.find(m=>m.name==='PF_OpenCradleL').visible),'Real touch-emulation quick action');await touch.locator('#toggle-controls').tap();expect(await touch.evaluate(()=>document.getElementById('stage').clientWidth===innerWidth),'Touch full-screen inspection');await touchContext.close();
 // Browser reports from the actual rendered scene, not only source-string assertions.
 const stats=await evalv(()=>({gpuGeometryCount:viewer.renderer.info.memory.geometries,renderTriangles:viewer.renderer.info.render.triangles,renderCalls:viewer.renderer.info.render.calls}));expect(errors.length===0,'No browser runtime errors',errors);expect(network.length===0,'No HTTP requests; network disabled',network);
 fs.writeFileSync(path.join(out,'browser-validation.json'),JSON.stringify({pass:true,viewer_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'exports/generated/viewer-v32/index.html'))).digest('hex'),checks,load_ms:loadMs,desktop:[1600,1050],tablets:[[1024,1366],[834,1194]],touch_target_min_px:44,offline:true,network_requests:network,errors,stats,physical_tablet_fps_certified:false},null,2)+'\n');fs.writeFileSync(path.join(out,'review-views.json'),JSON.stringify(views,null,2)+'\n');console.log('V332_BROWSER_PASS',checks.length,'checks;',views.length,'views; initial load',loadMs,'ms');
}finally{await browser.close();}
