"""Deterministic procurement records and writable measurement worksheets."""
import csv,html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
# These are project acceptance/recording targets, not vendor claims or purchase links.
# id: group, minimum spec, measurements, datum, source fields
DATA={
1:('BUY NOW','Production structural plywood main batch; door stock if different','Thickness at 9 distributed points per sheet; min/max; sheet dimensions; bow; face/core defects; grain direction; batch ID','Mark face A and front-left corner; thickness normal to face without crushing veneers','all active stock fields; config/cnc_detail_v25.json:stock'),
2:('BUY LATER','CNC shop consultation and physical coupon before release; not a hardware purchase','Actual cutter diameter; runout; pocket depth accuracy; accepted groove clearance; relief radius; two-face registration accuracy','Coupon face A and engraved zero corner','config/cnc_detail_v25.json:fit; tools/generate_cnc_coupon_v20.py'),
3:('BUY NOW','Four classic pinball legs with matching levelers and bolts; no integrated wheels','Both bolt center coordinates; hole/slot widths; corner included angle; flange width; leg mounting face flatness; bolt head seat; leveler travel; record all four legs','A=inside leg mounting faces seated on 90-degree test corner; B=leg upper edge; C=corner bisector','config/cabinet_service_v21.json:leg_corners; pending measured_patterns.HF-003'),
4:('BUY NOW','Four compact internal brackets; fit 95 x 95 x 150 mm planning corner volume including fasteners subject to measured review','Flange thickness; inner X at rear left/right when seated; full Y/Z extent; all hole centers/diameters; bolt/nut/washer stack; wrench access; backing contact area','A=inside cabinet wall plane; B=inside rear/front plane; C=bottom panel top; use measured-thickness corner fixture','config/cabinet_service_v21.json:leg_corners; config/cnc_detail_v25.json:leg_envelope'),
5:('BUY LATER','External removable skates compatible with selected legs','Leg engagement and stability before mobility use','Actual installed legs','No wood holes'),
6:('BUY NOW','Matched WPC-style hinge pair with matching bushings and pivot bolts; family label alone insufficient','Hole and slot centers; hole diameters; leaf outline/thickness; bend offsets; pivot center to both mounting faces; bushing OD/ID/flange/length; bolt shoulder and thread; full folded/upright sweep; left/right differences','A=each hinge mounting face; B=rear edge; C=bottom edge; pivot center separately recorded','config/structure_geometry_v14.json:wpc_hinges; measured_patterns.HF-006'),
7:('BUY NOW','Two positive upright locking bolts with captive receiving hardware','Thread; grip length; head/tool envelope; captive plate hole pattern; engagement; shelf/floor/gasket stack; X and Y after hinge fixture','A=rear shelf top; B=cabinet centerline; C=rear exterior plane; upright on fixture','config/structure_geometry_v14.json:upright_locking; measured_patterns.HF-007'),
8:('BUY NOW','Two UCFL202 housings with actual 15 mm bore; matched journal interface','Bore at each bearing; flange hole/slot centers and widths; casting outline; mounting-face to bore axis; housing thickness; axial protrusions; set-screw access; misalignment range documented by maker','A=flat mounting face; B=bore axis; C=line joining flange bolts; record both housings','config/playfield_mechanics_v18.json:pivot_interface; measured_patterns.HF-008'),
9:('LOCAL FAB','Two positively retained 15 mm journals and cheek plates; fit actual bearings','Journal fit/finish; engagement; shoulder; axial retention; plate-to-rail stack; bolt edge distances; shop drawing revision','Bearing axis and plate seating face; journal shoulder zero','config/playfield_mechanics_v18.json:pivot_interface; separate metal DXF/PDF after HF-008'),
10:('BUY NOW','Two straight captive steel props with lower pivot and upper captive pin/keeper; each assessed for full moving assembly load','Rod pin-to-pin length; section and end-eye geometry; lower clevis and upper receiver outlines/offsets/patterns; pin diameter and positive keeper engagement; stow-clip retention/pattern; complete swing; one-prop load capacity','A=each anchor mounting face; B=pivot pin center; C=stay center plane; both handed units','config/playfield_mechanics_v18.json:safety_stays; config/playfield_fixed_anchors_v19.json:safety_stay_fixed_anchor'),
12:('BUY NOW','Two compact closed-position latches plus resilient pads; positive retention','Latch and catch holes; closed grip range; travel/release envelope; pad footprint and loaded thickness; attachment geometry','A=seat/strike mounting surface; B=closed cradle rail underside; C=front end','config/playfield_mechanics_v18.json:closed_support; measured_patterns.HF-012'),
13:('BUY NOW','Matched 450 mm full-extension side-mount pair; minimum 30 kg pair rating in intended vertical mounting; positive stowed retainer separate','Body thickness each side; maker minimum/maximum side clearance; fixed/moving member outlines; hole and slot centers separately; travel; disconnect access; closed stop position; screw-head limits; rating conditions','A=fixed-member mounting face; B=closed rear end; C=lower edge; second sheet for moving member','config/cabinet_rear_cpu_shelf_v24.json:pc_shelf; measured_patterns.HF-013'),
14:('ADAPTER ONLY','Use already purchased 265 x 440 x 128 mm case; no new PC purchase','Mounting hole centers/diameters; foot heights; standoff stack; connector and GPU restraint access','A=case feet plane; B=installed front-left corner; X=265 direction; Y=440 direction','config/cabinet_rear_cpu_shelf_v24.json:pc_shelf.case_mounting; replaceable shelf only'),
15:('BUY NOW','Rear CPU door hinge allowing outward 105-degree opening at current overlap; same family may serve backbox if proven','Leaf widths/thickness; knuckle diameter; axis-to-leaf offsets; hole centers/diameters; screw heads; folded stack; available opening angle','A=leaf seating face; B=hinge end; C=knuckle axis; measure both leaves separately','config/cabinet_rear_cpu_shelf_v24.json:rear_service_door; measured_patterns.HF-015'),
16:('BUY NOW','Tool-controlled or keyed compression/quarter-turn latch and gasket','Body cutout; antirotation flat; fixing holes; cam reach; grip range; catch geometry; key/tool clearance; compressed gasket thickness','A=door outside face; B=latch body center; C=cam closed axis','config/cabinet_rear_cpu_shelf_v24.json:rear_service_door; measured_patterns.HF-016'),
17:('BUY NOW','Mains interface plus disconnect in enclosed touch-safe assembly fitting selected rear zone; procure mechanical sample with HF-027','Panel cutout; fixing holes; total depth; plug/cord bend space; disconnect travel; strain-relief footprint; mounting stack','A=carrier rear face; B=carrier lower-left; C=entry axis; no exposed terminals in service space','config/rear_utility_v26.json:A; measured_patterns.HF-017'),
18:('ADAPTER ONLY','Optional RJ45 or blank in 40 x 40 carrier over generic 24 x 24 wood aperture','Coupler/keystone aperture; clip retention; bend radius','Carrier outside lower-left corner','config/rear_utility_v26.json:A; carrier drawing only'),
19:('BUY NOW','Real pinball-style coin door fitting front and lockdown receiver zone','Required cutout contour/radii; flange coverage; all mounting holes; body/depth; hinge swing; lock/key access; coin mechanism protrusion','A=front mounting face; B=cutout lower-left; C=vertical centerline','config/cabinet_structure_v20.json front interface; measured_patterns.HF-019'),
20:('BUY NOW','One sample of each final flipper/start/launch button family; electronics unnecessary','Bore and flats; bezel OD; threaded length; nut/washer OD; switch depth; connector clearance; antirotation/pilot holes','A=panel outside face; B=button axis; C=key orientation','measured_patterns.HF-020; main-side/front CNC features'),
21:('LOCAL FAB','Siderail/glass channel profile mockup now; final length after fit','Bend radii; sheet thickness; glass capture; fastener flange; screw/head envelope; rail end relation to lockdown','Cabinet side top plane and glass edge','config/cabinet_structure_v20.json:siderails; metal drawing'),
22:('LOCAL FAB','600 mm custom lockdown and positive receiver prototype now before front hole freeze','Receiver/catch pattern; latch travel; glass engagement; front overlap; fastener access; loaded deflection','Cabinet front top and centerline; actual side/rail/glass mockup','config/cabinet_structure_v20.json:lockdown; metal drawing'),
23:('BUY LATER','Tempered safety glass after rail/lockdown mockup; no final glass order now','Finished supported opening; engagement and expansion clearances; thickness sample','Assembled supported glass plane','config/cabinet_structure_v20.json:playfield_glass'),
24:('ADAPTER ONLY','Display within 560 x 970 x 55 mm and 12 kg; buy later','VESA; connector access; completed moving mass and manual lifting force at the front grip','Cradle local axes and display mounting plane','display adapter; final manual lift check; no model-specific shell holes'),
25:('ADAPTER ONLY','Backglass within 740 x 450 x 100 mm service envelope; buy later','VESA; bezel; connector space; mass','Rail cage mounting plane','Backglass carrier only'),
26:('BUY NOW','Four identical steel angle clamps and underside backing plates plus positive shelf retainer; capacity checked for uplift','Both angle legs/length/thickness; bend radius; all holes; backing thickness/area/pattern; bolt grade/diameter/stack; retainer stroke/holes/access','A=bottom top face; B=rail face; C=clamp front edge; backing measured separately','config/cabinet_rear_cpu_shelf_v24.json:pc_shelf.support_detail; measured_patterns.HF-026'),
27:('BUY NOW','Same purchase assembly as HF-017; fully enclosed touch-safe mains box fitting selected zone','External bounds including mounts; lid screw/service clearance; cable gland projection; mounting hole pattern; protected entry','A=rear panel inside face; B=assembly lower-left; C=lid removal direction','config/rear_utility_v26.json:A; measured_patterns.HF-027'),
28:('BUY NOW','Measurement task bundled with HF-003/004/013/026; no separate purchase','Minimum actual rail-to-bracket gap including flange/bolt/nut/washer; bracket Y/Z extent; slide side clearance; clamp/backing bounds at both rear corners','Cabinet global X/Y/Z from measured-stock corner fixture; retain signed left/right coordinates','config/cnc_detail_v25.json:leg_envelope; pc_shelf support X coordinates'),
29:('BUY NOW','Backbox service-door hinge/lock/gasket sample; share family with CPU door if fit proven','Hinge leaves/axis/holes; lock body/catch/cutout; gasket compressed thickness; door clearance and opening sweep','A=backbox rear frame outer face; B=opening lower-left; C=door hinge edge','config/structure_geometry_v14.json:backbox.service_door; measured_patterns.HF-029'),
30:('BUY NOW','Selected mechanical/electronic plunger mechanism fits X500..540 Y18..220 Z195..235 body reserve','Front cutout contour; hole centers; sleeve/shaft diameter; flange and nut stack; stroke; handle projection; internal body/sensor depth; cable/connector sweep','A=front panel outside plane; B=plunger shaft axis; C=anti-rotation orientation; installed +Y inward','config/owner_services_v27.json:controls; measured_patterns.HF-030'),
31:('ADAPTER ONLY','Four panel-coupled SSF exciters; no speaker openings','Attachment footprint; adapter screw or adhesive specification; projection; cable bend and service clearance','Solid sidewall inside face; local adapter zero','config/owner_services_v27.json:ssf; local replaceable exciter adapters'),
32:('ADAPTER ONLY','Serviceable mesh/filter and later fan adapters; no fan-specific wood pattern','Filter compression and service clearance; fan thickness; grille/finger guard; fan pattern on adapter only','Generic cassette/adapter mounting face and project-designed mounting grid','config/owner_services_v27.json:bottom_intake/exhaust; replaceable adapter drawings'),
33:('ADAPTER ONLY','Backbox conventional speakers within replaceable 120 x 120 x 75 module reserve','Driver cutout; screw pattern; rear magnet/connector depth; baffle thickness; rail-cage adapter attachment','Removable speaker module front face; centerline','config/owner_services_v27.json:backbox.speaker_boxes_mm; replaceable baffle only')

}

def main():
 rows=list(csv.DictReader((ROOT/'bom/HARDWARE_FREEZE_V25.csv').open()))
 if not any(r['item_id']=='HF-029' for r in rows):
  rows.append(dict(item_id='HF-029',system='BB',item='Backbox service door hinge/lock/gasket',freeze_class='MEASURE_BEFORE_CNC',geometry_controls='rear frame and door hardware interfaces',status='OPEN',notes='Separate from CPU closure; same physical family permitted after fit check'))
  write(ROOT/'bom/HARDWARE_FREEZE_V25.csv',rows)
 result=[]
 for r in rows:
  i=int(r['item_id'][3:]);group,spec,measure,datum,updates=DATA[i]
  tool='0.01 mm digital caliper; square; steel rule; pin gauges for bores; depth rod; actual fasteners'
  tol='Record hole centers/stack to ±0.10 mm; outline to ±0.5 mm; repeat both parts. This is measurement uncertainty, NOT machining tolerance.'
  if i==1:tool='Micrometer or broad-jaw caliper; straightedge/feeler gauges';tol='Thickness recording ±0.05 mm; retain observed min/max; do not average away sheet variation.'
  if i in (8,9):tol='Bore/journal measurements ±0.02 mm with suitable gauges; hole centers ±0.10 mm; final fit from bearing/journal specification.'
  result.append(dict(item_id=r['item_id'],item=r['item'],group=group,controls=r['geometry_controls'],minimum_specification=spec,exact_measurements=measure,datum=datum,tool=tool,measurement_tolerance=tol,photos='Orthogonal front/rear/side with ruler in plane; detail of every hole and stack; assembled context; part label and maker specification',update_targets=updates,status='UNMEASURED',measured_values=''))
 write(ROOT/'bom/MEASURE_BEFORE_CNC_V25.csv',result)
 target=ROOT/'docs/measurement-templates';target.mkdir(exist_ok=True)
 for r in result:
  if r['group'] not in ('BUY NOW','LOCAL FAB'):continue
  text=''.join('<p><b>'+html.escape(k.replace('_',' '))+':</b> '+html.escape(r[k])+'</p>' for k in ('minimum_specification','controls','exact_measurements','datum','tool','measurement_tolerance','photos','update_targets'))
  page=f'''<!doctype html><meta charset="utf-8"><title>{r['item_id']} worksheet</title><style>body{{font:14px sans-serif;margin:25mm;max-width:900px}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #777;padding:9px}}svg{{width:100%;height:190px}}@media print{{body{{margin:10mm}}}}</style><h1>{r['item_id']} — {html.escape(r['item'])}</h1><p>MEASUREMENT WORKSHEET — SCHEMATIC, NOT A DRILL TEMPLATE. Do not derive hole positions from this drawing.</p>{text}<svg viewBox="0 0 800 190"><path d="M45 145V35H280V145Z M340 145V35H365V145Z M435 145V115H670V145Z" fill="none" stroke="#234" stroke-width="2"/><path d="M45 145H100 M45 145V90" stroke="#b44" stroke-width="3"/><text x="45" y="175">FRONT: mark datum A/B/C on photo</text><text x="325" y="175">SIDE / stack</text><text x="455" y="175">TOP / projection</text></svg><p>Owner/date: __________ Maker/part/lot: __________ Units: mm. Handed side: ______</p><table><tr><th>Feature ID</th><th>X from datum</th><th>Y from datum</th><th>Diameter/slot</th><th>Depth/stack</th><th>Repeat/uncertainty</th></tr>'''+('<tr>'+('<td>&nbsp;</td>'*6)+'</tr>')*10+'</table><p>Attach original photos and specifications. Do not use a photo scale as the only hole measurement. Mark uncertainty and inaccessible dimensions explicitly.</p>'
  (target/(r['item_id']+'.html')).write_text(page)
 print('MEASUREMENT_PACK_PASS',len(result),'hardware records')

def write(path,rows):
 with path.open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator='\n');w.writeheader();w.writerows(rows)
if __name__=='__main__':main()
