"""Human review index and final V33.3 report supplement. CERN-OHL-S-2.0."""
from pathlib import Path
import json,html,hashlib
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/assembly-v333'
read=lambda f:json.loads((O/f).read_text())
m=read('material-utilization.json');mass=read('mass-budget.json');pack=read('packaging.json');audit=read('assembly-validation.json');val=read('validation.json');browser=read('browser-validation.json');legacy=read('legacy-browser-validation.json');views=read('review-views.json')
lines=['<!-- V333_FINAL_SUPPLEMENT -->','','## Exact area accounting and purchase comparison','','All areas below are m². Spacing is the precise reserved area in this rectangle layout, not physical kerf loss. Cutouts are B-rep projected openings. Material removed by pockets, bores and face reduction is additionally itemized as volume in JSON. Potential reusable rectangles exclude cutout islands, profile scraps and final tabs.','',
 '| Thickness | Full sheet purchase | Usable | Border | Spacing reserve | Rectangle/profile loss | Cutouts | Net part area | Old/new potential reusable |','|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for s in m['stocks']:
 keys=['purchased_full_sheet_area_mm2','usable_area_mm2','hold_down_area_mm2','spacing_reserved_area_mm2','bounding_rectangle_contour_loss_mm2','cutout_area_mm2','projected_material_area_mm2']
 lines.append(f'| {s["thickness_mm"]:g} | '+' | '.join(f'{s[k]/1e6:.6f}' for k in keys)+f' | {s["previous_row_layout_reusable_offcut_mm2"]/1e6:.3f} / {s["reusable_rectangular_offcut_area_mm2"]/1e6:.3f} |')
lines+=['','| Thickness | Practical procurement envelope | Net utilization in smaller stock |','|---:|---|---:|']
for s in m['stocks']:lines.append(f'| {s["thickness_mm"]:g} | {s["practical_stock_rectangles_mm"]} mm | {s.get("practical_utilization_percent_net",s["utilization_percent_net"]):.2f}% |')
lines+=['','The full-sheet study recovers larger contiguous rectangles without reducing the six-sheet assumption. The separate small-stock search reduces procurement area. Neither search is an optimized production nesting; non-18 mm stock availability and small-stock retention require shop approval.','',
 '## Assembly screening result','','No geometry correction or speculative reorder was applied. The fixed manufacturing members are all present in the insertion report; the exact source operations/faces remain in the manual. There are '+str(len({i for s in audit['steps'] for i in s['both_face_normal_candidates_conflict']}))+' unique pieces with conflicts on both tested face-normal candidates. These do not exclude a different feasible assembly direction or bench subassembly. The current screen deliberately does not invent one.',
 f"There are {len(read('tool-screens.json'))} located Fxx driver reserves, of which {sum(bool(t['wood_conflicts']) for t in read('tool-screens.json'))} intersect final installed wood. All are recorded, including obstacle IDs/stages; some may be cleared by performing the operation earlier. An R10 ×100 reserve is not a selected tool or hand and cannot certify ergonomics.",
 '19 stage dependency checks and all31step evidence records are complete. **Full assembly-sequence/tool-access validation remains HOLD**: selected hardware/tool forms, joint fastener schedules, fixtures, and continuous insertion paths must be qualified. No new physically validated assembly steps are claimed. This is an explicit remaining blocker, not a manufacturing release.','',
 '## Animation and regression evidence','',
 f'-31schematic assembly/checkpoint clips,11service clips,2packing clips; exact130manufacturing meshes used for packing.',
 f'-{len(browser["checks"])} animation/offline/touch checks; {len(legacy["checks"])} retained viewer checks; {len(val["checks"])} conservation/containment/authority checks.',
 '-Touch playback: PASS in834×1194emulation. Physical tablet frame-rate qualification is not claimed.',
 '-Service endpoints compare planar parts within0.002mm; simplified cylindrical lock meshes use0.6mm vertex-sampling tolerance because retessellation changes vertices. The motion axes/routes come from the accepted CAD builders, not from vertex interpolation.',
 '-Current installed geometry, all130manufacturing pieces, hardware catalog and existing CNC/fit authority remain byte-identical. Entire V33.2 embedded geometry payload retained byte-for-byte.',
 '-Release/retainer/fastener details without a proven path are explicitly schematic; shelf removal is schematic. Door flexible-loop centerline uses the accepted constant-length construction; purchased cable bend properties remain unqualified.',
 '-Normal fold retains backbox glass/cassette and requires locks parked, rear doors latched, main playfield glass/matrix removed. Rare hinge service remains separate.',
 '', '[Review gallery](index.html) · [Offline interactive viewer](../viewer-v32/index.html) · [Machine-readable manual](assembly-manual.json)','',
 'HEAD AFTER is the commit containing this report; the exact resulting commit is supplied in the delivery response. Full-sheet CNC remains BLOCKED.','',
 '## Reproduction','','```sh\nfreecadcmd tools/assembly_v333_brep.py\nfreecadcmd tools/assembly_v333_motion.py\npython3 tools/build_assembly_v333.py\npython3 tools/build_viewer_v333.py\npython3 tools/check_assembly_v333.py\npython3 tools/check_metrics_v333.py\npython3 tools/check_current_v32.py\npython3 tools/package_assembly_v333.py\n```','',
 'Require positive V333_BREP_PASS and V333_MOTION_PASS sentinels: FreeCAD can return zero on Python exceptions. Browser checks require existing Playwright and Chrome; the delivered viewer itself needs no server/network.']
p=O/'README.md';base=p.read_text().split('<!-- V333_FINAL_SUPPLEMENT -->')[0].rstrip();p.write_text(base+'\n'+'\n'.join(lines)+'\n')
parts=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V33.3 review</title><style>body{font:16px system-ui;max-width:1250px;margin:30px auto;padding:0 20px;color:#20313c;background:#f2f5f6}a{color:#125b87}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(350px,1fr));gap:20px}figure{margin:0;background:white;padding:12px}img{width:100%;height:auto}figcaption{padding:10px}header{background:#20313c;color:white;padding:24px}header a{color:white}h1{font-size:25px}.hold{border-left:4px solid #986327;padding:12px;background:#fff1dd}</style><header><h1>V33.3 · Assembly, mass and flatpack planning</h1><p><a href="../viewer-v32/index.html">Open offline viewer / Abrir visualizador offline</a> · <a href="README.md">Detailed report</a></p></header><p class="hold">PRELIMINARY — NOT FOR CNC. CURRENT geometry unchanged. Assembly animations schematic unless an inherited geometric service route is explicitly identified. Manufacturing / physical qualification remains blocked.</p><div class="grid">']
for v in views:parts.append(f'<figure><a href="{v["image"]}"><img loading="lazy" src="{v["image"]}" alt="{html.escape(v["title"])}"></a><figcaption>{html.escape(v["title"])}</figcaption></figure>')
parts+=['</div><h2>Material study · PRELIMINARY — NOT FOR CNC</h2><div class="grid">']
for p in sorted(O.glob('*.svg')):parts.append(f'<figure><a href="{p.name}"><img loading="lazy" src="{p.name}" alt="{p.stem}"></a><figcaption>{p.stem}</figcaption></figure>')
parts+=['</div><p>CERN-OHL-S-2.0 · Source Location: https://github.com/advpeterrobinson-hash/vpin-cabinet</p></html>'];(O/'index.html').write_text('\n'.join(parts))
files=[p for p in O.iterdir() if p.is_file() and p.name!='artifact-index.json'];(O/'artifact-index.json').write_text(json.dumps({'status':'REVIEW_ONLY_FULL_SHEET_RELEASE_BLOCKED','files':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)]},indent=2)+'\n')
S=R/'studies/assembly-v333';S.mkdir(exist_ok=True,parents=True);(S/'README.md').write_text('# V33.3 assembly, mass and packaging\n\n[Full report](../../exports/generated/assembly-v333/README.md) · [Review gallery](../../exports/generated/assembly-v333/index.html) · [Offline viewer](../../exports/generated/viewer-v32/index.html).\n\n130 actual pieces, configurable density, three package mass targets,31step screening,44animations. Assembly insertion/tool qualification remains explicitly held; schematic clips are not motion proofs. CURRENT/CNC geometry and hardware quantities unchanged. Full-sheet release BLOCKED.\n\nCERN-OHL-S-2.0 · Source Location: https://github.com/advpeterrobinson-hash/vpin-cabinet\n')
print('V333_PACKAGE_PASS',len(files),'artifacts')
