"""Promote the validated V33.6 overlay; never release production drilling. CERN-OHL-S-2.0."""
from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/monitor-support-v336'
v=json.loads((O/'validation.json').read_text());assert v['pass'] and not v['manufacturing_ready'];assert v['native_sha256']==hashlib.sha256((O/'play.FCStd').read_bytes()).hexdigest();assert v['viewer_sha256']==hashlib.sha256((R/'exports/generated/viewer-v32/index.html').read_bytes()).hexdigest()
p=R/'config/current_v32.json';c=json.loads(p.read_text());c.update(structural_revision='V33.6',geometry_mesh='exports/generated/monitor-support-v336/mesh.json.gz',geometry_directory='exports/generated/monitor-support-v336',geometry_builder='tools/monitor_support_v336_entry.py',geometry_parameters='config/monitor_support_v336.json',source_head_before_promotion='7b84181f5c48c1a1e4a78f87319eec5512318492',structural_promotion_record='exports/generated/monitor-support-v336/validation.json',report='exports/generated/monitor-support-v336/README.md',manufacturing_register='config/manufacturing/flatpack_v336.json',side_button_positional_authority='config/monitor_support_v336.json',side_button_centers_yz_mm=[[255,270],[310,270]],side_button_final_bore_mm=None,side_button_final_recess_mm=None,playfield_base_horn_absent=True,backbox_source_note='V33.5 accepted architecture retained. V33.6 adds carrier strain-relief slots; central VESA-plate window NOT promoted. M067 and all existing adjustment/retention preserved.');p.write_text(json.dumps(c,indent=2)+'\n')
vm={'version':'V33.6','authority':'CURRENT_VALIDATED_POSITIONAL_AND_MONITOR_SERVICE_OVERLAY','source_head':c['source_head_before_promotion'],'viewer':'exports/generated/viewer-v32/index.html','builder':'tools/build_viewer_v336.py','validation':'exports/generated/monitor-support-v336/validation.json','manual_json':'exports/generated/monitor-support-v336/assembly-manual.json','manufacturing_register':'config/manufacturing/flatpack_v336.json','geometry_changed':True,'manufacturing_release':False};(R/'config/viewer_v336.json').write_text(json.dumps(vm,indent=2)+'\n')
p=R/'README.md';s=p.read_text();s=s.replace(s.splitlines()[0],'> CURRENT V33.6: [clean playfield contour, restored side-button datums and monitor service](exports/generated/monitor-support-v336/README.md). 97 CNC plywood pieces + 4 unchanged SW01 blocks = 101 pieces / 59 families. Side-button centers Y255/Y310, Z270; hardware bores remain HOLD. CNC remains BLOCKED. [Offline viewer](exports/generated/viewer-v32/index.html).',1);p.write_text(s)
p=R/'AGENTS.md';s=p.read_text();a=s.index('- **CURRENT V33.5');b=s.index('- **Under-front controls:**',a);s=s[:a]+'''- **CURRENT V33.6 geometry/manufacturing:** `config/current_v32.json`, `config/monitor_support_v336.json`, `config/manufacturing/flatpack_v336.json`; report `docs/MONITOR_SUPPORT_V336.md`. M025 has a clean rectangular outside contour with rear service window and two strain slots. Side-button positional authority is Y255/Y310, Z270 from front Y0; Y89/Y127 is superseded. Final bore/recess remains null / PURCHASE_BEFORE_CNC. Backbox carriers gain strain slots only; central VESA window is HOLD. M067 and all prior protected mechanisms remain. Counts: 101 wood / 97 CNC / 4 SW01 / 59 families; no 4 mm plywood.
- **CURRENT viewer:** `config/viewer_v336.json`; `tools/build_viewer_v336.py` and `tools/check_current_v32.py`. Every installed/detail object has geometry authority. Rebuild all named states, manufacturing and packing representations for changed parts; do not reuse historical M025 meshes. SW01/jig and retained M006/S3/T3 remain unchanged. CNC release remains BLOCKED.
''' +s[b:]
s=s.replace('- **Active owner correction gate:** stop unrelated development.', '- **Historical service-correction gate (side-button datums superseded by V33.6):**')
p.write_text(s)
for f in ['docs/NOTCH_FLOOR_FANS_V32.md','docs/OWNER_CORRECTION_REVIEW_V32.md']:
 p=R/f;s=p.read_text();banner='> HISTORICAL: Y89/Y127 and the horned M025 contour are superseded by [V33.6](MONITOR_SUPPORT_V336.md). CURRENT uses Y255/Y310, Z270 and the clean base. Historical numbers below are retained for audit; no final button drilling is released.\n\n'
 if not s.startswith(banner):p.write_text(banner+s)
print('V336_PROMOTION_PASS; CNC BLOCKED')
