"""Explicit owner-authorized promotion AFTER all V35.1 guards; never manufacturing release."""
from pathlib import Path
import json,shutil,subprocess,sys
R=Path(__file__).resolve().parents[1];O=R/'exports/generated/widebody-v351'
subprocess.run([sys.executable,str(R/'tools/check_widebody_v351_release.py')],check=True,cwd=R)
def read(p):return json.loads(p.read_text())
def put(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
cur=read(R/'config/current_v32.json');cur.update(geometry_directory='exports/generated/widebody-v351',geometry_builder='tools/rebuild_widebody_v351.py',geometry_parameters='config/widebody_v351.json',source_head_before_promotion='11822cb2dc9c7c7b511348df860cb76196d641be',report='docs/STANDARD_WIDEBODY_V351.md',structural_revision='V35.1',phase='STANDARD_WIDEBODY_REFERENCE_DESIGN_CANDIDATE',geometry_mesh='exports/generated/widebody-v351/viewer-native.json.gz',promotion_record='exports/generated/widebody-v351/promotion-validation.json',structural_promotion_record='exports/generated/widebody-v351/promotion-validation.json',manufacturing_register='config/manufacturing/flatpack_v351.json',hardware_catalog='config/hardware_catalog_v351.json',wood_material_map='config/wood_materials_v351.json',playfield_front_width_mm=424.65,body_outside_width_mm=628.65,body_nominal_inside_width_mm=592.65,body_length_mm=1308.1,assembly_centerline_mm=314.325,backbox_assembly_translation_mm=[14.325,0,0],backbox_local_source_unchanged=True,backbox_width_mm=780,front_landing_centers_xy_mm=[[72,245],[556.65,245]],playfield_dowel_length_mm=588.65,display_glass_normal_gap_mm=[7.5,7.5,7.5],display_glass_angle_difference_deg=0,commercial_interfaces='config/standard_interfaces_v351.json',side_rail_required=False,custom_lockdown=False,front_landings_authority='config/widebody_v351.json',closed_support_audit='exports/generated/widebody-v351/validation.json',backbox_service_geometry_status='V34.2 LOCAL SHAPES PRESERVED; V35.1 RIGID CENTERLINE PLACEMENT; physical fit/load HOLD',width_dependent_coordinate_authority='exports/generated/widebody-v351/width-audit.json; overrides X coordinates in historical subsystem configurations',manufacturing_ready=False,manufacturing_valid=False,physical_qualification_complete=False,raised_playfield_service_released=False)
cur['playfield_rear_glass_support']='Fixed commercial channel screwed to local angled lands in main RearBearingShelf, not moving BB_Floor; actual purchased profile and holes HOLD'
put(R/'config/current_v32.json',cur)
shutil.copyfile(O/'manufacturing-register.json',R/'config/manufacturing/flatpack_v351.json')
mat=read(R/'config/wood_materials_v342.json');mat['version']='V35.1';mat['parts']=[{k:a[k] for k in ['manufacturing_part_id','instance_id','source_component','material_class','nominal_stock_thickness_mm']} for a in read(O/'manufacturing-register.json')['parts']];put(R/'config/wood_materials_v351.json',mat)
for f in ['ASSEMBLY_MANUAL.md','ASSEMBLY_MANUAL.pt-BR.md']:shutil.copyfile(O/f,R/'docs'/f)
shutil.copyfile(O/'viewer.html',R/'exports/generated/viewer-v32/index.html')
vc=read(R/'config/viewer_v337.json');vc.update(version='V35.1',authority='STANDARD_WIDEBODY_REFERENCE_DESIGN_CANDIDATE',source_head=cur['source_head_before_promotion'],builder='tools/build_viewer_v351.py',validation='exports/generated/widebody-v351/promotion-validation.json',manual_json='exports/generated/widebody-v351/assembly-manual.json',manufacturing_register=cur['manufacturing_register'],hardware_catalog=cur['hardware_catalog'],unrelated_geometry_unchanged=True,width_migration=True);put(R/'config/viewer_v337.json',vc)
print('PROMOTED V35.1 REFERENCE DESIGN ONLY; CNC BLOCKED')
