"""Actual OCC mesh review views, isolated candidate only. CERN-OHL-S-2.0."""
from pathlib import Path
import json,math
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
R=Path(__file__).resolve().parents[2];O=R/'exports/generated/backbox-structure-v32';D=json.loads((O/'detail-mesh.json').read_text());B=json.loads((O/'mesh.json').read_text());Q=json.loads((O/'validation.json').read_text());old=json.loads((R/'exports/generated/backbox-floor-v32/mesh.json').read_text());parts={p['name']:p for p in B['parts']};axis=np.array(D['axis']);files=[]
plt.rcParams.update({'font.size':10,'figure.facecolor':'#f8fafc','axes.facecolor':'#f8fafc','font.family':'DejaVu Sans'})
def col(n):
 for k,c in [('OpenCradle','#ce3f52'),('Bearing','#299779'),('Shelf','#299779'),('BACKBOX_BASE','#299779'),('Floor','#d59b32'),('Side','#5485a6'),('SIDE_','#91a1ad'),('Channel','#dd6950'),('Lock','#9763b2'),('Hinge','#434f70'),('Pivot','#9763b2'),('Toy','#47a490')]:
  if k in n:return c
 return '#ae9272'
def vv(m,a=0):
 v=np.array(m['vertices']);t=math.radians(a);rot=np.array([[1,0,0],[0,math.cos(t),-math.sin(t)],[0,math.sin(t),math.cos(t)]]);return (v-axis)@rot.T+axis

def plot(ax,items,dims=(1,2),a=0,alpha=.65):
 for m in items:
  v=vv(m,a);ax.add_collection(PolyCollection(v[np.array(m['faces'])][:,:,dims],facecolors=col(m['name']),edgecolors=col(m['name']),linewidth=.25,alpha=alpha))
 ax.set_aspect('equal');ax.grid(alpha=.17);ax.set_xlabel('XYZ'[dims[0]]+' / mm');ax.set_ylabel('XYZ'[dims[1]]+' / mm')
def select(role,*names):return [m for m in D[role] if m['name'] in names]
def note(ax,text):ax.axis('off');ax.text(0,.96,text,va='top',linespacing=1.5,fontsize=11)
def finish(fig,n,title):
 fig.suptitle(f'{n:02}  '+title,x=.04,ha='left',fontweight='bold',fontsize=16);fig.text(.04,.025,'ISOLATED CANDIDATE • NOT PROMOTED • pivot / playfield cradle conflict • hardware drilling & manufacturing BLOCKED',fontsize=9,color='#9b2738');fig.subplots_adjust(top=.86,bottom=.13,left=.075,right=.97,wspace=.3);p=O/f'{n:02}-review.png';fig.savefig(p,dpi=155);plt.close(fig);files.append({'file':p.name,'title':title,'authority':'actual candidate CAD tessellation; hardware reserves provisional'})
def yz(ax,a=0,limits=((980,1340),(450,760)),side=True):
 plot(ax,select('fixed','SIDE_L','BACKBOX_BASE','CandidateGlassChannelL'),alpha=.25);plot(ax,select('wood','BB_Floor',*(['BB_SideL'] if side else [])),a=a);ax.plot(1066.8,508,'ko',ms=5);ax.set(xlim=limits[0],ylim=limits[1])
def scene(ax,a=0,full=False):
 if full:
  scene={**parts,**B['states']['PLAY' if a==0 else 'BACKBOX FOLD']};groups=[(m,False) for n,m in scene.items() if m and n!='SIDE_L' and n!='PF_BackboxCheckEnvelope' and not any(k in n.upper() for k in ['ENVELOPE','RESERVE','RESERVED','CANDIDATEPAYLOAD'])]
 else:groups=[(m,False) for m in D['fixed'] if m['name']!='SIDE_L']+[(m,True) for m in D['wood']]
 for m,moving in groups:
  v=vv(m,a if moving else 0);ax.add_collection3d(Poly3DCollection(v[np.array(m['faces'])],facecolor=col(m['name']),edgecolor='#39434d',linewidth=.08,alpha=.65 if m['name'].startswith('BB_') else .35))
 ax.set(xlim=(-110,710),ylim=(0 if full else 150,1350),zlim=(-30 if full else 380,1360),xlabel='X / mm',ylabel='Y / mm',zlabel='Z / mm');ax.set_box_aspect((820,1350,1390 if full else 980));ax.view_init(elev=24,azim=-52);ax.set_title('Left cabinet side hidden for inspection; glass / matrix removed at positive angles',fontsize=9)
fig,ax=plt.subplots(1,2,figsize=(13,7));yz(ax[0]);plot(ax[0],select('reserves','BB_HingeArmReserveL','BB_HingeFlangeReserveL'),alpha=.2);ax[0].plot(1270,508,'rx',ms=11);ax[0].annotate('SUPERSEDED Y1270',(1270,508),xytext=(1155,465),arrowprops={'arrowstyle':'->'});ax[0].annotate('VALIDATED Y1066.8',(1066.8,508),xytext=(988,700),arrowprops={'arrowstyle':'->'});note(ax[1],'Axis Z508, transverse X\n\nRear datum Y1308.1\nCorrect rear offset: 241.3 mm / 9.5 in\nOld rear offset: 38.1 mm / 1.5 in\nCorrection: 203.2 mm forward\n\nKinematic authority corrected in active configuration.\nNo final purchased-hardware holes released.\nAccepted CAD snapshots remain unchanged.');finish(fig,1,'Correct pivot vs superseded interpretation')
fig,ax=plt.subplots(1,2,figsize=(13,7));plot(ax[0],[m for m in old['wood'] if 'LeftSide' in m['name']],alpha=.22);plot(ax[0],select('wood','BB_SideL','BB_Floor'));ax[0].set(xlim=(1030,1340),ylim=(575,1340));note(ax[1],'210 mm lower side depth retained\nSide front: Y1098.1 at Z596.9\nFloor front: Y1146.0\nProjection ahead of floor: 47.9 mm\n\n18 mm plywood, 780 mm overall width\n6 mm floor capture stops at actual floor front\n12 mm residual skin alongside engaged floor\n18 mm full stock ahead of the floor\n\nNo extra rail, cleat or toy-specific holes.');finish(fig,2,'Accepted side outline / candidate floor and joint')
fig,ax=plt.subplots(1,2,figsize=(13,7));plot(ax[0],select('wood','BB_SideL','BB_Floor'),dims=(0,1));ax[0].set(xlim=(-105,-15),ylim=(1080,1320));pts=np.array(Q['joints']['L']['fastener_points_xyz_mm']);ax[0].plot(pts[:,0],pts[:,1],'ko');note(ax[1],'Per-side engagement: 156.1 mm\nShoulder: 6 × 156.1 = 936.6 mm²\nVertical face: 18 × 156.1 = 2809.8 mm²\nEnd shoulder: 108 mm²\n\nThree illustrative retention positions per side:\nY1171 / 1224.05 / 1277.1, Z605.9\n53.05 mm pitch, 25 mm longitudinal end distance\n9 mm thickness-edge center distance\n\nThese are planning markers, not drilled holes.\nNo screw SKU, pilot or certified capacity selected.');finish(fig,3,'Side / floor captured joint — left; right mirrored')
fig,ax=plt.subplots(1,2,figsize=(13,7));yz(ax[0],limits=((1080,1175),(580,705)));ax[0].annotate('47.9 mm projection',(1120,601),xytext=(1090,682),arrowprops={'arrowstyle':'->'});note(ax[1],'Full nominal 18 mm stock retained\nin the lower-front projection.\n\nBroad continuous side; no horn, finger or notch.\nThe sloped side grows deeper above the bottom.\nLower corner is not a heavy toy cantilever.\nUse generic side boards above the service zone.\n\nNo geometric need for an added crossmember.\nActual plywood and joint qualification remain open.');finish(fig,4,'Lower-front side projection — unused rabbet removed')
fig,ax=plt.subplots(1,2,figsize=(13,7));plot(ax[0],D['bearing'],dims=(0,1));ax[0].set(xlim=(-100,700),ylim=(1100,1330));note(ax[1],'Exact floor / shelf bearing: 65,672.4 mm²\n77.62% of previous 84,604.625877 mm²\nShelf top material retained: 83.03%\n\nBearing strips around generic passage:\nfront 42 mm; rear 42.1 mm; sides 152 mm\nShelf front remains Y1127.125\nFloor overlaps shelf from Y1146 to Y1290.1\n\nBroad connected ring; no thin local ligaments.\nBearing area is not strength certification.');finish(fig,5,'Upright shelf bearing')
fig,ax=plt.subplots(1,2,figsize=(13,7));cr=[parts['PF_OpenCradleL']];plot(ax[0],cr,alpha=.7);plot(ax[0],select('reserves','BB_PivotAccessReserveL'),alpha=.25);ax[0].plot(1066.8,508,'kx',ms=10);ax[0].set(xlim=(980,1110),ylim=(470,550));ax[0].set_title('Correct pivot lies within fixed cradle wood');plot(ax[1],cr,dims=(0,2),alpha=.7);plot(ax[1],select('reserves','BB_PivotAccessReserveL'),dims=(0,2),alpha=.25);ax[1].set(xlim=(-8,50),ylim=(475,550));ax[1].set_title('3 mm internal coaxial probe: 213.77 mm³ overlap\nBoth sides obstructed; hardware integration FAIL');finish(fig,6,'Updated hinge reserve — promotion blocker')
fig,ax=plt.subplots(1,2,figsize=(13,7));plot(ax[0],D['bearing'],dims=(0,1),alpha=.45);plot(ax[0],select('reserves','BB_LockWoodReserve1','BB_LockWoodReserve2'),dims=(0,1));ax[0].set(xlim=(0,600),ylim=(1120,1310));note(ax[1],'Two provisional positive lock zones\nCenters X120 / 480, Y1188\nWood reserve radius 30.7 mm\nWasher / backing reserve radius 20 mm\nUpper tool reserve radius 18 mm × 80 mm\n\nNearest outer edge: 42 mm from center\nPassage side: 50 mm from center\nWood and upper tool access checks pass\n\nNo lock SKU or final hole diameter selected.');finish(fig,7,'Two upright locking reserves')
fig,ax=plt.subplots(1,2,figsize=(13,7));plot(ax[0],select('wood','BB_Floor'),dims=(0,1));ax[0].set(xlim=(-100,700),ylim=(1100,1330));note(ax[1],'Generic service passage only\n260 mm width × 60 mm depth\nCenter X300 / Y1218\nSeparate width, depth, X and Y parameters\n\nFloor and shelf openings coincide.\nNo connector, gland or disconnect geometry.\nNo permanent toy or electronics hole pattern.\n\nBuilder configures all cable termination.\nChanging passage requires renewed structure checks.');finish(fig,8,'Mutable generic cable passage')
fig,ax=plt.subplots(1,2,figsize=(13,7));plot(ax[0],select('wood','BB_SideL'),alpha=.2);plot(ax[0],select('zones','AvailableToyAreaL'));ax[0].set(xlim=(1030,1340),ylim=(580,1340));note(ax[1],'210 mm lower side depth preserved\nGeneric mounting zone on each side:\n37,593.2 mm² from existing 210 mm study\n\nKeep lower hinge / service corridor accessible.\nRemovable boards remain the mounting strategy.\nNo chime, strobe, siren, beacon, relay,\ncontactor or control-board holes in permanent wood.\n\nThese zones indicate usable geometry,\nnot an approved payload mass.');finish(fig,9,'Generic side toy zones preserved')
fig,ax=plt.subplots(1,2,figsize=(13,7));yz(ax[0],a=1,side=False,limits=((1110,1175),(575,630)));s=next(r for r in Q['fold_samples'] if r['angle_deg']==1);note(ax[1],f'1° actual wood rotation about Y1066.8 / Z508\n\nFloor / shelf gap: {s["floor_shelf_distance_mm"]:.6f} mm\nFloor / shelf penetration: 0 mm³\nShelf bearing releases for every positive angle.\n\nGLASS REMOVED; MATRIX REMOVED\n\nWood trajectory is clear.\nPivot installation is still obstructed at upright.\nThis is not a validated complete hardware assembly.');finish(fig,10,'1° clean wood release — hinge integration still blocked')
for no,a in [(11,15),(12,45),(13,90)]:
 fig=plt.figure(figsize=(12,9));scene(fig.add_subplot(111,projection='3d'),a);finish(fig,no,f'{a}° candidate wood fold — hardware installation blocked')
for no,a in [(14,0),(15,90)]:
 fig=plt.figure(figsize=(12,10));scene(fig.add_subplot(111,projection='3d'),a,True);finish(fig,no,'Complete '+('upright' if a==0 else 'folded')+' V32 candidate — NOT CURRENT')
(O/'review-images.json').write_text(json.dumps({'images':files,'upstream_images_included':False,'source':'actual OCC tessellation from isolated candidate; reserves schematic','promoted':False},indent=2)+'\n');print('BACKBOX_STRUCTURE_IMAGES_PASS',len(files))
