<script>/* Original CERN-OHL-S-2.0 — semantic landing inspection, no new physical geometry. */
(async()=>{
while(!window.animation333)await new Promise(r=>setTimeout(r,30));const V=viewer,T=THREE,$=id=>document.getElementById(id),panel=document.createElement('details');panel.id='landings-panel';document.querySelector('aside').append(panel);let helpers=[],labels=[],ghosted=[];
function cleanup(){for(const m of ghosted){m.material.opacity=m.userData.baseOpacity;m.material.transparent=m.userData.baseOpacity<1;m.material.depthWrite=m.userData.baseOpacity===1;}ghosted=[];for(const h of helpers){V.scene.remove(h);h.geometry?.dispose();h.material?.dispose();}helpers=[];for(const l of labels)l.remove();labels=[];}
function lang(en,pt){return V.language()==='en'?en:pt;}
function isolate(){animation333.exit();cleanup();V.applyState('PLAYFIELD LANDINGS');V.cameraPreset('INTERIOR');V.frame(V.installed.filter(m=>m.visible));}
function path(){animation333.exit();cleanup();V.applyState('SUPPORT LOAD PATH');V.cameraPreset('INTERIOR');V.frame(V.installed.filter(m=>m.visible));
 const base=V.installed.find(m=>m.name==='PF_BasePlywood');if(base){base.material.opacity=.18;base.material.transparent=true;base.material.depthWrite=false;ghosted.push(base);}
 const front=V.installed.filter(m=>m.userData.meta.group==='landings'&&m.userData.meta.kind==='wood');const rear=V.installed.filter(m=>['PF_OpenCradleL','PF_OpenCradleR'].includes(m.name));
 for(const [list,text] of [[front,lang('FRONT: pad → landing → side wall','FRENTE: ponta → apoio → lateral')],[rear,lang('REAR: dowel → cradle → floor','TRASEIRA: cavilha → berço → fundo')]]){
  const left=list.filter(m=>{m.geometry.computeBoundingBox();return m.geometry.boundingBox.getCenter(new T.Vector3()).x<300;});if(!left.length)continue;const b=new T.Box3();for(const m of left)b.union(new T.Box3().setFromObject(m));const c=b.getCenter(new T.Vector3());c.z=b.max.z+25;const arrow=new T.ArrowHelper(new T.Vector3(0,0,-1),c,90,0x20313c,18,10);arrow.line.material.depthTest=false;arrow.cone.material.depthTest=false;arrow.renderOrder=70;V.scene.add(arrow);helpers.push(arrow);
  const label=document.createElement('div');label.className='packing-label';label.textContent=text;label.style.left='12px';label.style.top=(90+labels.length*37)+'px';$('stage').append(label);labels.push(label);
 }
}
function text(){panel.innerHTML=`<summary>${lang('PLAYFIELD LANDINGS','APOIOS FRONTAIS DO PLAYFIELD')}</summary><button id="landings-isolate" class="full">${lang('ISOLATE LANDINGS','ISOLAR APOIOS FRONTAIS')}</button><button id="landings-loadpath" class="full">${lang('REAR / FRONT LOAD PATH','CAMINHOS DE CARGA TRASEIRO / FRONTAL')}</button><button id="landings-close" class="full">${lang('SEAT / LOWER / RETAIN','ASSENTAR / ABAIXAR / RETER')}</button><p>${lang('Front pads reproduce the approved PLAY pose and transverse level. ±3 mm only compensates tolerances; it is not a new playing-height/tilt range. T1–T3 remain clear. Release both captive retainers before opening.','Pontas frontais reproduzem a posição PLAY aprovada e o nível transversal. ±3 mm compensa tolerâncias, não altera altura/inclinação. T1–T3 mantêm folga. Solte ambas as retenções cativas antes de abrir.')}</p>`;$('landings-isolate').onclick=isolate;$('landings-loadpath').onclick=path;$('landings-close').onclick=()=>{cleanup();animation333.start('service-pf-close');};}
for(const id of ['lang-en','lang-pt'])$(id).addEventListener('click',()=>setTimeout(()=>{text();cleanup();},0));$('service-state')?.addEventListener('change',cleanup);$('animation-open')?.addEventListener('click',cleanup);document.querySelector('#quick')?.addEventListener('click',cleanup);text();window.landings3363={isolate,path,cleanup};document.body.dataset.landingsReady='true';
})().catch(e=>{console.error(e);document.getElementById('error').hidden=false;document.getElementById('error').textContent=e.message;});</script>
